// Code generated by gen_persistence_mappers; DO NOT EDIT.
package mapper

import (
	entity "ThreeKingdoms/internal/player/entity"
	model "ThreeKingdoms/internal/player/infra/persistence/model"
)

func ResourceModelToEntity(m *model.Resource) *entity.ResourceEntity {
	if m == nil {
		return nil
	}
	var s entity.ResourceState
	s.Id = m.Id
	s.Rid = m.Rid
	s.Wood = m.Wood
	s.Iron = m.Iron
	s.Stone = m.Stone
	s.Grain = m.Grain
	s.Gold = m.Gold
	s.Decree = m.Decree
	return entity.HydrateResourceEntity(s)
}

func ResourceEntityToModel(e *entity.ResourceEntity) *model.Resource {
	if e == nil {
		return nil
	}
	s := e.Snapshot()
	out := &model.Resource{}
	out.Id = s.Id
	out.Rid = s.Rid
	out.Wood = s.Wood
	out.Iron = s.Iron
	out.Stone = s.Stone
	out.Grain = s.Grain
	out.Gold = s.Gold
	out.Decree = s.Decree
	return out
}

func RoleModelToEntity(m *model.Role) *entity.RoleEntity {
	if m == nil {
		return nil
	}
	var s entity.RoleState
	s.Rid = m.Rid
	s.Uid = m.Uid
	s.Status = entity.RoleStatus(m.Status)
	s.Headid = m.Headid
	s.Sex = m.Sex
	s.NickName = m.NickName
	s.Balance = m.Balance
	s.LoginTime = m.LoginTime
	s.LogoutTime = m.LogoutTime
	s.Profile = m.Profile
	s.CreatedAt = m.CreatedAt
	return entity.HydrateRoleEntity(s)
}

func RoleEntityToModel(e *entity.RoleEntity) *model.Role {
	if e == nil {
		return nil
	}
	s := e.Snapshot()
	out := &model.Role{}
	out.Rid = s.Rid
	out.Uid = s.Uid
	out.Status = int(s.Status)
	out.Headid = s.Headid
	out.Sex = s.Sex
	out.NickName = s.NickName
	out.Balance = s.Balance
	out.LoginTime = s.LoginTime
	out.LogoutTime = s.LogoutTime
	out.Profile = s.Profile
	out.CreatedAt = s.CreatedAt
	return out
}

func RoleAttributeModelToEntity(m *model.RoleAttribute) *entity.RoleAttributeEntity {
	if m == nil {
		return nil
	}
	var s entity.RoleAttributeState
	s.Id = m.Id
	s.Rid = m.Rid
	s.ParentId = m.ParentId
	s.CollectTimes = m.CollectTimes
	s.LastCollectTime = m.LastCollectTime
	s.PosTags = m.PosTags
	if hook, ok := any(&s).(interface{ PosTagsToPosTagArray() }); ok {
		hook.PosTagsToPosTagArray()
	}
	return entity.HydrateRoleAttributeEntity(s)
}

func RoleAttributeEntityToModel(e *entity.RoleAttributeEntity) *model.RoleAttribute {
	if e == nil {
		return nil
	}
	s := e.Snapshot()
	if hook, ok := any(&s).(interface{ PosTagArrayToPosTags() }); ok {
		hook.PosTagArrayToPosTags()
	}
	out := &model.RoleAttribute{}
	out.Id = s.Id
	out.Rid = s.Rid
	out.ParentId = s.ParentId
	out.CollectTimes = s.CollectTimes
	out.LastCollectTime = s.LastCollectTime
	out.PosTags = s.PosTags
	return out
}
