// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"fmt"
	"reflect"
	"sort"
)

const (
	FieldAlliance_id        Field = "id"
	FieldAlliance_worldId   Field = "worldId"
	FieldAlliance_name      Field = "name"
	FieldAlliance_notice    Field = "notice"
	FieldAlliance_majors    Field = "majors"
	FieldAlliance_members   Field = "members"
	FieldAlliance_applyList Field = "applyList"
)

var emptyAllianceEntity = &AllianceEntity{}

type AllianceEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type AllianceEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type AllianceEntityTrace struct {
	dirty              bool
	trace              map[Field]bool
	changes            map[Field]*AllianceEntityCollectionChangeInner
	childDirty_majors  map[PlayerID]struct{}
	childDirty_members map[PlayerID]struct{}
}

func (t *AllianceEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *AllianceEntityTrace) ensureChange(f Field) *AllianceEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*AllianceEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &AllianceEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *AllianceEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *AllianceEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *AllianceEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *AllianceEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *AllianceEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *AllianceEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *AllianceEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

func (t *AllianceEntityTrace) markChildDirty_majors(f Field, key PlayerID) {
	t.mark(f)
	if t.childDirty_majors == nil {
		t.childDirty_majors = make(map[PlayerID]struct{}, 8)
	}
	t.childDirty_majors[key] = struct{}{}
}

func (t *AllianceEntityTrace) clearChildDirty_majors(key PlayerID) {
	if t.childDirty_majors == nil {
		return
	}
	delete(t.childDirty_majors, key)
}

func (t *AllianceEntityTrace) childDirtyKeys_majors() []PlayerID {
	if len(t.childDirty_majors) == 0 {
		return nil
	}
	out := make([]PlayerID, 0, len(t.childDirty_majors))
	for key := range t.childDirty_majors {
		out = append(out, key)
	}
	sort.Slice(out, func(i, j int) bool { return fmt.Sprint(out[i]) < fmt.Sprint(out[j]) })
	return out
}

func (t *AllianceEntityTrace) markChildDirty_members(f Field, key PlayerID) {
	t.mark(f)
	if t.childDirty_members == nil {
		t.childDirty_members = make(map[PlayerID]struct{}, 8)
	}
	t.childDirty_members[key] = struct{}{}
}

func (t *AllianceEntityTrace) clearChildDirty_members(key PlayerID) {
	if t.childDirty_members == nil {
		return
	}
	delete(t.childDirty_members, key)
}

func (t *AllianceEntityTrace) childDirtyKeys_members() []PlayerID {
	if len(t.childDirty_members) == 0 {
		return nil
	}
	out := make([]PlayerID, 0, len(t.childDirty_members))
	for key := range t.childDirty_members {
		out = append(out, key)
	}
	sort.Slice(out, func(i, j int) bool { return fmt.Sprint(out[i]) < fmt.Sprint(out[j]) })
	return out
}

type AllianceState struct {
	Id        AllianceID
	WorldId   WorldID
	Name      string
	Notice    string
	Majors    map[PlayerID]MajorState
	Members   map[PlayerID]MemberState
	ApplyList []ApplyItemState
}

type AllianceEntitySnap struct {
	Version          uint64
	State            AllianceState
	DirtyFields      []Field
	Changes          map[Field]AllianceEntityCollectionChange
	MajorsDirtyKeys  []PlayerID
	MembersDirtyKeys []PlayerID
}

type AllianceEntity struct {
	id        AllianceID
	worldId   WorldID
	name      string
	notice    string
	majors    map[PlayerID]*MajorEntity
	members   map[PlayerID]*MemberEntity
	applyList []*ApplyItemEntity
	_dt       AllianceEntityTrace
}

func (e *AllianceEntity) copyMapMajors(in map[PlayerID]MajorState) map[PlayerID]MajorState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]MajorState, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (e *AllianceEntity) mapsEqualMajors(a, b map[PlayerID]MajorState) bool {
	if a == nil && b == nil {
		return true
	}
	return false
}

func (e *AllianceEntity) hydrateMapMajors(in map[PlayerID]MajorState) map[PlayerID]*MajorEntity {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]*MajorEntity, len(in))
	for k, v := range in {
		out[k] = HydrateMajorEntity(v)
	}
	return out
}

func (e *AllianceEntity) snapshotMapMajors(in map[PlayerID]*MajorEntity) map[PlayerID]MajorState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]MajorState, len(in))
	for k, v := range in {
		if v == nil {
			var z MajorState
			out[k] = z
			continue
		}
		out[k] = v.Save()
	}
	return out
}

func (e *AllianceEntity) copyMapMembers(in map[PlayerID]MemberState) map[PlayerID]MemberState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]MemberState, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (e *AllianceEntity) mapsEqualMembers(a, b map[PlayerID]MemberState) bool {
	if a == nil && b == nil {
		return true
	}
	return false
}

func (e *AllianceEntity) hydrateMapMembers(in map[PlayerID]MemberState) map[PlayerID]*MemberEntity {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]*MemberEntity, len(in))
	for k, v := range in {
		out[k] = HydrateMemberEntity(v)
	}
	return out
}

func (e *AllianceEntity) snapshotMapMembers(in map[PlayerID]*MemberEntity) map[PlayerID]MemberState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]MemberState, len(in))
	for k, v := range in {
		if v == nil {
			var z MemberState
			out[k] = z
			continue
		}
		out[k] = v.Save()
	}
	return out
}

func (e *AllianceEntity) hydrateSliceApplyList(in []ApplyItemState) []*ApplyItemEntity {
	if in == nil {
		return nil
	}
	out := make([]*ApplyItemEntity, len(in))
	for i, v := range in {
		out[i] = HydrateApplyItemEntity(v)
	}
	return out
}

func (e *AllianceEntity) snapshotSliceApplyList(in []*ApplyItemEntity) []ApplyItemState {
	if in == nil {
		return nil
	}
	out := make([]ApplyItemState, len(in))
	for i, v := range in {
		if v == nil {
			var z ApplyItemState
			out[i] = z
			continue
		}
		out[i] = v.Save()
	}
	return out
}

func (e *AllianceEntity) slicesEqualApplyList(a, b []ApplyItemState) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !reflect.DeepEqual(a[i], b[i]) {
			return false
		}
	}
	return true
}

func HydrateAllianceEntity(s AllianceState) *AllianceEntity {
	return &AllianceEntity{
		id:        s.Id,
		worldId:   s.WorldId,
		name:      s.Name,
		notice:    s.Notice,
		majors:    emptyAllianceEntity.hydrateMapMajors(s.Majors),
		members:   emptyAllianceEntity.hydrateMapMembers(s.Members),
		applyList: emptyAllianceEntity.hydrateSliceApplyList(s.ApplyList),
	}
}

func (e *AllianceEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *AllianceEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = AllianceEntityTrace{}
}

func (e *AllianceEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *AllianceEntity) DirtyChanges() map[Field]AllianceEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]AllianceEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := AllianceEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneAllianceEntityCollectionChange(in AllianceEntityCollectionChange) AllianceEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *AllianceEntity) Save() AllianceState {
	var s AllianceState
	if e == nil {
		return s
	}
	s.Id = e.id
	s.WorldId = e.worldId
	s.Name = e.name
	s.Notice = e.notice
	s.Majors = e.snapshotMapMajors(e.majors)
	s.Members = e.snapshotMapMembers(e.members)
	s.ApplyList = e.snapshotSliceApplyList(e.applyList)
	return s
}

func NewAllianceEntitySnap(version uint64, e *AllianceEntity) *AllianceEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &AllianceEntitySnap{
		Version:          version,
		State:            e.Save(),
		DirtyFields:      dirtyFields,
		Changes:          changes,
		MajorsDirtyKeys:  e._dt.childDirtyKeys_majors(),
		MembersDirtyKeys: e._dt.childDirtyKeys_members(),
	}
}

func (s *AllianceEntitySnap) Clone() *AllianceEntitySnap {
	if s == nil {
		return nil
	}
	out := &AllianceEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]AllianceEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneAllianceEntityCollectionChange(ch)
		}
	}
	out.MajorsDirtyKeys = append([]PlayerID(nil), s.MajorsDirtyKeys...)
	out.MembersDirtyKeys = append([]PlayerID(nil), s.MembersDirtyKeys...)
	out.State.Majors = emptyAllianceEntity.copyMapMajors(s.State.Majors)
	out.State.Members = emptyAllianceEntity.copyMapMembers(s.State.Members)
	out.State.ApplyList = append([]ApplyItemState(nil), s.State.ApplyList...)
	return out
}

func (e *AllianceEntity) Id() AllianceID {
	if e == nil {
		var z AllianceID
		return z
	}
	return e.id
}

func (e *AllianceEntity) SetId(v AllianceID) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldAlliance_id)
	return true
}

func (e *AllianceEntity) WorldId() WorldID {
	if e == nil {
		var z WorldID
		return z
	}
	return e.worldId
}

func (e *AllianceEntity) SetWorldId(v WorldID) bool {
	if e == nil {
		return false
	}
	if e.worldId == v {
		return false
	}
	e.worldId = v
	e._dt.mark(FieldAlliance_worldId)
	return true
}

func (e *AllianceEntity) Name() string {
	if e == nil {
		var z string
		return z
	}
	return e.name
}

func (e *AllianceEntity) SetName(v string) bool {
	if e == nil {
		return false
	}
	if e.name == v {
		return false
	}
	e.name = v
	e._dt.mark(FieldAlliance_name)
	return true
}

func (e *AllianceEntity) Notice() string {
	if e == nil {
		var z string
		return z
	}
	return e.notice
}

func (e *AllianceEntity) SetNotice(v string) bool {
	if e == nil {
		return false
	}
	if e.notice == v {
		return false
	}
	e.notice = v
	e._dt.mark(FieldAlliance_notice)
	return true
}

func (e *AllianceEntity) GetMajors(key PlayerID) (MajorState, bool) {
	var z MajorState
	if e == nil || e.majors == nil {
		return z, false
	}
	v, ok := e.majors[key]
	if !ok || v == nil {
		return z, false
	}
	return v.Save(), true
}

func (e *AllianceEntity) LenMajors() int {
	if e == nil || e.majors == nil {
		return 0
	}
	return len(e.majors)
}

func (e *AllianceEntity) ForEachMajors(fn func(key PlayerID, value MajorState)) {
	if e == nil || e.majors == nil || fn == nil {
		return
	}
	for k, v := range e.majors {
		if v == nil {
			continue
		}
		fn(k, v.Save())
	}
}

func (e *AllianceEntity) RangeMajors(fn func(key PlayerID, value MajorState) bool) {
	if e == nil || e.majors == nil || fn == nil {
		return
	}
	for k, v := range e.majors {
		if v == nil {
			continue
		}
		if !fn(k, v.Save()) {
			return
		}
	}
}

func (e *AllianceEntity) DirtyMajorsKeys() []PlayerID {
	if e == nil {
		return nil
	}
	return e._dt.childDirtyKeys_majors()
}

func (e *AllianceEntity) ReplaceMajors(v map[PlayerID]MajorState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualMajors(e.snapshotMapMajors(e.majors), v) {
		return false
	}
	e.majors = e.hydrateMapMajors(v)
	e._dt.markFullReplace(FieldAlliance_majors)
	return true
}

func (e *AllianceEntity) PutMajors(key PlayerID, value MajorState) bool {
	if e == nil {
		return false
	}
	if e.majors == nil {
		e.majors = make(map[PlayerID]*MajorEntity)
	}
	e.majors[key] = HydrateMajorEntity(value)
	e._dt.markMapSet(FieldAlliance_majors, fmt.Sprint(key), value)
	e._dt.markChildDirty_majors(FieldAlliance_majors, key)
	return true
}

func (e *AllianceEntity) PutMajorsMany(entries map[PlayerID]MajorState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.majors == nil {
		e.majors = make(map[PlayerID]*MajorEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		e.majors[k] = HydrateMajorEntity(v)
		e._dt.markMapSet(FieldAlliance_majors, fmt.Sprint(k), v)
		e._dt.markChildDirty_majors(FieldAlliance_majors, k)
		changed = true
	}
	return changed
}

func (e *AllianceEntity) UpdateMajors(key PlayerID, fn func(value *MajorEntity)) bool {
	if e == nil || fn == nil || e.majors == nil {
		return false
	}
	v, ok := e.majors[key]
	if !ok || v == nil {
		return false
	}
	fn(v)
	e._dt.markChildDirty_majors(FieldAlliance_majors, key)
	return true
}

func (e *AllianceEntity) DelMajors(key PlayerID) bool {
	if e == nil || e.majors == nil {
		return false
	}
	if _, ok := e.majors[key]; !ok {
		return false
	}
	delete(e.majors, key)
	e._dt.markMapDelete(FieldAlliance_majors, fmt.Sprint(key))
	e._dt.clearChildDirty_majors(key)
	return true
}

func (e *AllianceEntity) DelMajorsMany(keys []PlayerID) bool {
	if e == nil || e.majors == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.majors[key]; !ok {
			continue
		}
		delete(e.majors, key)
		e._dt.markMapDelete(FieldAlliance_majors, fmt.Sprint(key))
		e._dt.clearChildDirty_majors(key)
		changed = true
	}
	return changed
}

func (e *AllianceEntity) ClearMajors() bool {
	if e == nil {
		return false
	}
	if len(e.majors) == 0 {
		return false
	}
	e.majors = nil
	e._dt.markFullReplace(FieldAlliance_majors)
	e._dt.childDirty_majors = nil
	return true
}

func (e *AllianceEntity) GetMembers(key PlayerID) (MemberState, bool) {
	var z MemberState
	if e == nil || e.members == nil {
		return z, false
	}
	v, ok := e.members[key]
	if !ok || v == nil {
		return z, false
	}
	return v.Save(), true
}

func (e *AllianceEntity) LenMembers() int {
	if e == nil || e.members == nil {
		return 0
	}
	return len(e.members)
}

func (e *AllianceEntity) ForEachMembers(fn func(key PlayerID, value MemberState)) {
	if e == nil || e.members == nil || fn == nil {
		return
	}
	for k, v := range e.members {
		if v == nil {
			continue
		}
		fn(k, v.Save())
	}
}

func (e *AllianceEntity) RangeMembers(fn func(key PlayerID, value MemberState) bool) {
	if e == nil || e.members == nil || fn == nil {
		return
	}
	for k, v := range e.members {
		if v == nil {
			continue
		}
		if !fn(k, v.Save()) {
			return
		}
	}
}

func (e *AllianceEntity) DirtyMembersKeys() []PlayerID {
	if e == nil {
		return nil
	}
	return e._dt.childDirtyKeys_members()
}

func (e *AllianceEntity) ReplaceMembers(v map[PlayerID]MemberState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualMembers(e.snapshotMapMembers(e.members), v) {
		return false
	}
	e.members = e.hydrateMapMembers(v)
	e._dt.markFullReplace(FieldAlliance_members)
	return true
}

func (e *AllianceEntity) PutMembers(key PlayerID, value MemberState) bool {
	if e == nil {
		return false
	}
	if e.members == nil {
		e.members = make(map[PlayerID]*MemberEntity)
	}
	e.members[key] = HydrateMemberEntity(value)
	e._dt.markMapSet(FieldAlliance_members, fmt.Sprint(key), value)
	e._dt.markChildDirty_members(FieldAlliance_members, key)
	return true
}

func (e *AllianceEntity) PutMembersMany(entries map[PlayerID]MemberState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.members == nil {
		e.members = make(map[PlayerID]*MemberEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		e.members[k] = HydrateMemberEntity(v)
		e._dt.markMapSet(FieldAlliance_members, fmt.Sprint(k), v)
		e._dt.markChildDirty_members(FieldAlliance_members, k)
		changed = true
	}
	return changed
}

func (e *AllianceEntity) UpdateMembers(key PlayerID, fn func(value *MemberEntity)) bool {
	if e == nil || fn == nil || e.members == nil {
		return false
	}
	v, ok := e.members[key]
	if !ok || v == nil {
		return false
	}
	fn(v)
	e._dt.markChildDirty_members(FieldAlliance_members, key)
	return true
}

func (e *AllianceEntity) DelMembers(key PlayerID) bool {
	if e == nil || e.members == nil {
		return false
	}
	if _, ok := e.members[key]; !ok {
		return false
	}
	delete(e.members, key)
	e._dt.markMapDelete(FieldAlliance_members, fmt.Sprint(key))
	e._dt.clearChildDirty_members(key)
	return true
}

func (e *AllianceEntity) DelMembersMany(keys []PlayerID) bool {
	if e == nil || e.members == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.members[key]; !ok {
			continue
		}
		delete(e.members, key)
		e._dt.markMapDelete(FieldAlliance_members, fmt.Sprint(key))
		e._dt.clearChildDirty_members(key)
		changed = true
	}
	return changed
}

func (e *AllianceEntity) ClearMembers() bool {
	if e == nil {
		return false
	}
	if len(e.members) == 0 {
		return false
	}
	e.members = nil
	e._dt.markFullReplace(FieldAlliance_members)
	e._dt.childDirty_members = nil
	return true
}

func (e *AllianceEntity) LenApplyList() int {
	if e == nil {
		return 0
	}
	return len(e.applyList)
}

func (e *AllianceEntity) AtApplyList(index int) (ApplyItemState, bool) {
	var z ApplyItemState
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.applyList) {
		return z, false
	}
	v := e.applyList[index]
	if v == nil {
		return z, true
	}
	return v.Save(), true
}

func (e *AllianceEntity) ForEachApplyList(fn func(index int, value ApplyItemState)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.applyList {
		var state ApplyItemState
		if v != nil {
			state = v.Save()
		}
		fn(i, state)
	}
}

func (e *AllianceEntity) RangeApplyList(fn func(index int, value ApplyItemState) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.applyList {
		var state ApplyItemState
		if v != nil {
			state = v.Save()
		}
		if !fn(i, state) {
			return
		}
	}
}

func (e *AllianceEntity) ReplaceApplyList(v []ApplyItemState) bool {
	if e == nil {
		return false
	}
	if e.slicesEqualApplyList(e.snapshotSliceApplyList(e.applyList), v) {
		return false
	}
	e.applyList = e.hydrateSliceApplyList(v)
	e._dt.markFullReplace(FieldAlliance_applyList)
	return true
}

func (e *AllianceEntity) AppendApplyList(values ...ApplyItemState) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	for _, v := range values {
		rv := HydrateApplyItemEntity(v)
		e.applyList = append(e.applyList, rv)
		e._dt.markSliceAppend(FieldAlliance_applyList, v)
	}
	return true
}

func (e *AllianceEntity) SetApplyListAt(index int, value ApplyItemState) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.applyList) {
		return false
	}
	var oldState ApplyItemState
	if e.applyList[index] != nil {
		oldState = e.applyList[index].Save()
	}
	if reflect.DeepEqual(oldState, value) {
		return false
	}
	e.applyList[index] = HydrateApplyItemEntity(value)
	e._dt.markSliceSet(FieldAlliance_applyList, index, value)
	return true
}

func (e *AllianceEntity) UpdateApplyListAt(index int, fn func(value *ApplyItemEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if index < 0 || index >= len(e.applyList) {
		return false
	}
	v := e.applyList[index]
	if v == nil {
		return false
	}
	before := v.Save()
	fn(v)
	after := v.Save()
	if reflect.DeepEqual(before, after) {
		return false
	}
	e._dt.markSliceSet(FieldAlliance_applyList, index, after)
	return true
}

func (e *AllianceEntity) RemoveApplyListAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.applyList) {
		return false
	}
	e.applyList = append(e.applyList[:index], e.applyList[index+1:]...)
	e._dt.markSliceRemoveAt(FieldAlliance_applyList, index)
	return true
}

func (e *AllianceEntity) SwapRemoveApplyListAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.applyList) {
		return false
	}
	last := len(e.applyList) - 1
	if index != last {
		e.applyList[index] = e.applyList[last]
	}
	e.applyList = e.applyList[:last]
	e._dt.markSliceSwapRemoveAt(FieldAlliance_applyList, index)
	return true
}

func (e *AllianceEntity) ClearApplyList() bool {
	if e == nil {
		return false
	}
	if len(e.applyList) == 0 {
		return false
	}
	e.applyList = nil
	e._dt.markFullReplace(FieldAlliance_applyList)
	return true
}
