// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldApplyItem_playerId Field = "playerId"
	FieldApplyItem_nickName Field = "nickName"
)

var emptyApplyItemEntity = &ApplyItemEntity{}

type ApplyItemEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type ApplyItemEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type ApplyItemEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*ApplyItemEntityCollectionChangeInner
}

func (t *ApplyItemEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *ApplyItemEntityTrace) ensureChange(f Field) *ApplyItemEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*ApplyItemEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &ApplyItemEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *ApplyItemEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *ApplyItemEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *ApplyItemEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *ApplyItemEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *ApplyItemEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *ApplyItemEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *ApplyItemEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type ApplyItemState struct {
	PlayerId int
	NickName string
}

type ApplyItemEntitySnap struct {
	Version     uint64
	State       ApplyItemState
	DirtyFields []Field
	Changes     map[Field]ApplyItemEntityCollectionChange
}

type ApplyItemEntity struct {
	playerId int
	nickName string
	_dt      ApplyItemEntityTrace
}

func HydrateApplyItemEntity(s ApplyItemState) *ApplyItemEntity {
	return &ApplyItemEntity{
		playerId: s.PlayerId,
		nickName: s.NickName,
	}
}

func (e *ApplyItemEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *ApplyItemEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = ApplyItemEntityTrace{}
}

func (e *ApplyItemEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *ApplyItemEntity) DirtyChanges() map[Field]ApplyItemEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]ApplyItemEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := ApplyItemEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneApplyItemEntityCollectionChange(in ApplyItemEntityCollectionChange) ApplyItemEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *ApplyItemEntity) Save() ApplyItemState {
	var s ApplyItemState
	if e == nil {
		return s
	}
	s.PlayerId = e.playerId
	s.NickName = e.nickName
	return s
}

func NewApplyItemEntitySnap(version uint64, e *ApplyItemEntity) *ApplyItemEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &ApplyItemEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *ApplyItemEntitySnap) Clone() *ApplyItemEntitySnap {
	if s == nil {
		return nil
	}
	out := &ApplyItemEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]ApplyItemEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneApplyItemEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *ApplyItemEntity) PlayerId() int {
	if e == nil {
		var z int
		return z
	}
	return e.playerId
}

func (e *ApplyItemEntity) SetPlayerId(v int) bool {
	if e == nil {
		return false
	}
	if e.playerId == v {
		return false
	}
	e.playerId = v
	e._dt.mark(FieldApplyItem_playerId)
	return true
}

func (e *ApplyItemEntity) NickName() string {
	if e == nil {
		var z string
		return z
	}
	return e.nickName
}

func (e *ApplyItemEntity) SetNickName(v string) bool {
	if e == nil {
		return false
	}
	if e.nickName == v {
		return false
	}
	e.nickName = v
	e._dt.mark(FieldApplyItem_nickName)
	return true
}
