// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
	"time"
)

type BuildingDoc struct {
	Id           int       `bson:"id"`
	BuildingType int8      `bson:"building_type"`
	Level        int8      `bson:"level"`
	OPLevel      int8      `bson:"o_p_level"`
	X            int       `bson:"x"`
	Y            int       `bson:"y"`
	Name         string    `bson:"name"`
	Wood         int       `bson:"wood"`
	Iron         int       `bson:"iron"`
	Stone        int       `bson:"stone"`
	Grain        int       `bson:"grain"`
	Defender     int       `bson:"defender"`
	CurDurable   int       `bson:"cur_durable"`
	MaxDurable   int       `bson:"max_durable"`
	OccupyTime   time.Time `bson:"occupy_time"`
	EndTime      time.Time `bson:"end_time"`
	GiveUpTime   int64     `bson:"give_up_time"`
}

func BuildingStateToDoc(s entity.BuildingState) BuildingDoc {
	state := entity.HydrateBuildingEntity(s).Save()
	return BuildingDoc{
		Id:           state.Id,
		BuildingType: state.BuildingType,
		Level:        state.Level,
		OPLevel:      state.OPLevel,
		X:            state.X,
		Y:            state.Y,
		Name:         state.Name,
		Wood:         state.Wood,
		Iron:         state.Iron,
		Stone:        state.Stone,
		Grain:        state.Grain,
		Defender:     state.Defender,
		CurDurable:   state.CurDurable,
		MaxDurable:   state.MaxDurable,
		OccupyTime:   state.OccupyTime,
		EndTime:      state.EndTime,
		GiveUpTime:   state.GiveUpTime,
	}
}

func BuildingDocToState(d BuildingDoc) entity.BuildingState {
	state := entity.BuildingState{
		Id:           d.Id,
		BuildingType: d.BuildingType,
		Level:        d.Level,
		OPLevel:      d.OPLevel,
		X:            d.X,
		Y:            d.Y,
		Name:         d.Name,
		Wood:         d.Wood,
		Iron:         d.Iron,
		Stone:        d.Stone,
		Grain:        d.Grain,
		Defender:     d.Defender,
		CurDurable:   d.CurDurable,
		MaxDurable:   d.MaxDurable,
		OccupyTime:   d.OccupyTime,
		EndTime:      d.EndTime,
		GiveUpTime:   d.GiveUpTime,
	}
	return entity.HydrateBuildingEntity(state).Save()
}
