// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type CityDoc struct {
	Name  string `bson:"name"`
	Level int8   `bson:"level"`
}

func CityStateToDoc(s entity.CityState) CityDoc {
	state := entity.HydrateCityEntity(s).Save()
	return CityDoc{
		Name:  state.Name,
		Level: state.Level,
	}
}

func CityDocToState(d CityDoc) entity.CityState {
	state := entity.CityState{
		Name:  d.Name,
		Level: d.Level,
	}
	return entity.HydrateCityEntity(state).Save()
}
