// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type FacilityDoc struct {
	Id           int    `bson:"id"`
	Name         string `bson:"name"`
	PrivateLevel int8   `bson:"private_level"`
	FType        int8   `bson:"f_type"`
	UpTime       int64  `bson:"up_time"`
}

func FacilityStateToDoc(s entity.FacilityState) FacilityDoc {
	state := entity.HydrateFacilityEntity(s).Save()
	return FacilityDoc{
		Id:           state.Id,
		Name:         state.Name,
		PrivateLevel: state.PrivateLevel,
		FType:        state.FType,
		UpTime:       state.UpTime,
	}
}

func FacilityDocToState(d FacilityDoc) entity.FacilityState {
	state := entity.FacilityState{
		Id:           d.Id,
		Name:         d.Name,
		PrivateLevel: d.PrivateLevel,
		FType:        d.FType,
		UpTime:       d.UpTime,
	}
	return entity.HydrateFacilityEntity(state).Save()
}
