// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type GSkillDoc struct {
	Id    int `bson:"id"`
	Lv    int `bson:"lv"`
	CfgId int `bson:"cfg_id"`
}

func GSkillStateToDoc(s entity.GSkillState) GSkillDoc {
	state := entity.HydrateGSkillEntity(s).Save()
	return GSkillDoc{
		Id:    state.Id,
		Lv:    state.Lv,
		CfgId: state.CfgId,
	}
}

func GSkillDocToState(d GSkillDoc) entity.GSkillState {
	state := entity.GSkillState{
		Id:    d.Id,
		Lv:    d.Lv,
		CfgId: d.CfgId,
	}
	return entity.HydrateGSkillEntity(state).Save()
}
