// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type PlayerDoc struct {
	PlayerID   PlayerID             `bson:"player_id"`
	WorldID    WorldID              `bson:"world_id"`
	AllianceID AllianceID           `bson:"alliance_id"`
	CityID     CityID               `bson:"city_id"`
	Profile    RoleDoc              `bson:"profile"`
	Resource   ResourceDoc          `bson:"resource"`
	Attribute  RoleAttributeDoc     `bson:"attribute"`
	Buildings  []BuildingDoc        `bson:"buildings"`
	Armies     map[int]ArmyDoc      `bson:"armies"`
	Generals   map[int]GeneralDoc   `bson:"generals"`
	Facility   []FacilityDoc        `bson:"facility"`
	WarReports map[int]WarReportDoc `bson:"war_reports"`
	Skills     map[int]SkillDoc     `bson:"skills"`
	City       CityDoc              `bson:"city"`
}

func toDocSlice_buildings(in []entity.BuildingState) []BuildingDoc {
	if in == nil {
		return nil
	}
	out := make([]BuildingDoc, len(in))
	for i, v := range in {
		out[i] = BuildingStateToDoc(v)
	}
	return out
}

func toStateSlice_buildings(in []BuildingDoc) []entity.BuildingState {
	if in == nil {
		return nil
	}
	out := make([]entity.BuildingState, len(in))
	for i, v := range in {
		out[i] = BuildingDocToState(v)
	}
	return out
}

func toDocMap_armies(in map[int]entity.ArmyState) map[int]ArmyDoc {
	if in == nil {
		return nil
	}
	out := make(map[int]ArmyDoc, len(in))
	for k, v := range in {
		out[k] = ArmyStateToDoc(v)
	}
	return out
}

func toStateMap_armies(in map[int]ArmyDoc) map[int]entity.ArmyState {
	if in == nil {
		return nil
	}
	out := make(map[int]entity.ArmyState, len(in))
	for k, v := range in {
		out[k] = ArmyDocToState(v)
	}
	return out
}

func toDocMap_generals(in map[int]entity.GeneralState) map[int]GeneralDoc {
	if in == nil {
		return nil
	}
	out := make(map[int]GeneralDoc, len(in))
	for k, v := range in {
		out[k] = GeneralStateToDoc(v)
	}
	return out
}

func toStateMap_generals(in map[int]GeneralDoc) map[int]entity.GeneralState {
	if in == nil {
		return nil
	}
	out := make(map[int]entity.GeneralState, len(in))
	for k, v := range in {
		out[k] = GeneralDocToState(v)
	}
	return out
}

func toDocSlice_facility(in []entity.FacilityState) []FacilityDoc {
	if in == nil {
		return nil
	}
	out := make([]FacilityDoc, len(in))
	for i, v := range in {
		out[i] = FacilityStateToDoc(v)
	}
	return out
}

func toStateSlice_facility(in []FacilityDoc) []entity.FacilityState {
	if in == nil {
		return nil
	}
	out := make([]entity.FacilityState, len(in))
	for i, v := range in {
		out[i] = FacilityDocToState(v)
	}
	return out
}

func toDocMap_warReports(in map[int]entity.WarReportState) map[int]WarReportDoc {
	if in == nil {
		return nil
	}
	out := make(map[int]WarReportDoc, len(in))
	for k, v := range in {
		out[k] = WarReportStateToDoc(v)
	}
	return out
}

func toStateMap_warReports(in map[int]WarReportDoc) map[int]entity.WarReportState {
	if in == nil {
		return nil
	}
	out := make(map[int]entity.WarReportState, len(in))
	for k, v := range in {
		out[k] = WarReportDocToState(v)
	}
	return out
}

func toDocMap_skills(in map[int]entity.SkillState) map[int]SkillDoc {
	if in == nil {
		return nil
	}
	out := make(map[int]SkillDoc, len(in))
	for k, v := range in {
		out[k] = SkillStateToDoc(v)
	}
	return out
}

func toStateMap_skills(in map[int]SkillDoc) map[int]entity.SkillState {
	if in == nil {
		return nil
	}
	out := make(map[int]entity.SkillState, len(in))
	for k, v := range in {
		out[k] = SkillDocToState(v)
	}
	return out
}

func PlayerStateToDoc(s entity.PlayerState) PlayerDoc {
	state := entity.HydratePlayerEntity(s).Save()
	return PlayerDoc{
		PlayerID:   state.PlayerID,
		WorldID:    state.WorldID,
		AllianceID: state.AllianceID,
		CityID:     state.CityID,
		Profile:    RoleStateToDoc(state.Profile),
		Resource:   ResourceStateToDoc(state.Resource),
		Attribute:  RoleAttributeStateToDoc(state.Attribute),
		Buildings:  toDocSlice_buildings(state.Buildings),
		Armies:     toDocMap_armies(state.Armies),
		Generals:   toDocMap_generals(state.Generals),
		Facility:   toDocSlice_facility(state.Facility),
		WarReports: toDocMap_warReports(state.WarReports),
		Skills:     toDocMap_skills(state.Skills),
		City:       CityStateToDoc(state.City),
	}
}

func PlayerDocToState(d PlayerDoc) entity.PlayerState {
	state := entity.PlayerState{
		PlayerID:   d.PlayerID,
		WorldID:    d.WorldID,
		AllianceID: d.AllianceID,
		CityID:     d.CityID,
		Profile:    RoleDocToState(d.Profile),
		Resource:   ResourceDocToState(d.Resource),
		Attribute:  RoleAttributeDocToState(d.Attribute),
		Buildings:  toStateSlice_buildings(d.Buildings),
		Armies:     toStateMap_armies(d.Armies),
		Generals:   toStateMap_generals(d.Generals),
		Facility:   toStateSlice_facility(d.Facility),
		WarReports: toStateMap_warReports(d.WarReports),
		Skills:     toStateMap_skills(d.Skills),
		City:       CityDocToState(d.City),
	}
	return entity.HydratePlayerEntity(state).Save()
}
