// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type PlayerDoc struct {
	PlayerID  PlayerID         `bson:"player_id"`
	WorldID   WorldID          `bson:"world_id"`
	Profile   RoleDoc          `bson:"profile"`
	Resource  ResourceDoc      `bson:"resource"`
	Attribute RoleAttributeDoc `bson:"attribute"`
	X         int              `bson:"x"`
	Y         int              `bson:"y"`
	Buildings []BuildingDoc    `bson:"buildings"`
	Armies    []ArmyDoc        `bson:"armies"`
	Generals  []GeneralDoc     `bson:"generals"`
}

func toDocSlice_buildings(in []entity.BuildingState) []BuildingDoc {
	if in == nil {
		return nil
	}
	out := make([]BuildingDoc, len(in))
	for i, v := range in {
		out[i] = BuildingStateToDoc(v)
	}
	return out
}

func toStateSlice_buildings(in []BuildingDoc) []entity.BuildingState {
	if in == nil {
		return nil
	}
	out := make([]entity.BuildingState, len(in))
	for i, v := range in {
		out[i] = BuildingDocToState(v)
	}
	return out
}

func toDocSlice_armies(in []entity.ArmyState) []ArmyDoc {
	if in == nil {
		return nil
	}
	out := make([]ArmyDoc, len(in))
	for i, v := range in {
		out[i] = ArmyStateToDoc(v)
	}
	return out
}

func toStateSlice_armies(in []ArmyDoc) []entity.ArmyState {
	if in == nil {
		return nil
	}
	out := make([]entity.ArmyState, len(in))
	for i, v := range in {
		out[i] = ArmyDocToState(v)
	}
	return out
}

func toDocSlice_generals(in []entity.GeneralState) []GeneralDoc {
	if in == nil {
		return nil
	}
	out := make([]GeneralDoc, len(in))
	for i, v := range in {
		out[i] = GeneralStateToDoc(v)
	}
	return out
}

func toStateSlice_generals(in []GeneralDoc) []entity.GeneralState {
	if in == nil {
		return nil
	}
	out := make([]entity.GeneralState, len(in))
	for i, v := range in {
		out[i] = GeneralDocToState(v)
	}
	return out
}

func PlayerStateToDoc(s entity.PlayerState) PlayerDoc {
	state := entity.HydratePlayerEntity(s).Save()
	return PlayerDoc{
		PlayerID:  state.PlayerID,
		WorldID:   state.WorldID,
		Profile:   RoleStateToDoc(state.Profile),
		Resource:  ResourceStateToDoc(state.Resource),
		Attribute: RoleAttributeStateToDoc(state.Attribute),
		X:         state.X,
		Y:         state.Y,
		Buildings: toDocSlice_buildings(state.Buildings),
		Armies:    toDocSlice_armies(state.Armies),
		Generals:  toDocSlice_generals(state.Generals),
	}
}

func PlayerDocToState(d PlayerDoc) entity.PlayerState {
	state := entity.PlayerState{
		PlayerID:  d.PlayerID,
		WorldID:   d.WorldID,
		Profile:   RoleDocToState(d.Profile),
		Resource:  ResourceDocToState(d.Resource),
		Attribute: RoleAttributeDocToState(d.Attribute),
		X:         d.X,
		Y:         d.Y,
		Buildings: toStateSlice_buildings(d.Buildings),
		Armies:    toStateSlice_armies(d.Armies),
		Generals:  toStateSlice_generals(d.Generals),
	}
	return entity.HydratePlayerEntity(state).Save()
}
