// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type PlayerDoc struct {
	PlayerID   PlayerID             `bson:"player_id"`
	WorldID    WorldID              `bson:"world_id"`
	Profile    RoleDoc              `bson:"profile"`
	Resource   ResourceDoc          `bson:"resource"`
	Attribute  RoleAttributeDoc     `bson:"attribute"`
	X          int                  `bson:"x"`
	Y          int                  `bson:"y"`
	Buildings  []BuildingDoc        `bson:"buildings"`
	Armies     map[CityID][]ArmyDoc `bson:"armies"`
	Generals   []GeneralDoc         `bson:"generals"`
	Facility   []FacilityDoc        `bson:"facility"`
	WarReports map[int]WarReportDoc `bson:"war_reports"`
}

func toDocSlice_buildings(in []entity.BuildingState) []BuildingDoc {
	if in == nil {
		return nil
	}
	out := make([]BuildingDoc, len(in))
	for i, v := range in {
		out[i] = BuildingStateToDoc(v)
	}
	return out
}

func toStateSlice_buildings(in []BuildingDoc) []entity.BuildingState {
	if in == nil {
		return nil
	}
	out := make([]entity.BuildingState, len(in))
	for i, v := range in {
		out[i] = BuildingDocToState(v)
	}
	return out
}

func toDoc_armies(in map[CityID][]entity.ArmyState) map[CityID][]ArmyDoc {
	var out map[CityID][]ArmyDoc
	if in == nil {
		out = nil
	} else {
		out0 := make(map[CityID][]ArmyDoc, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				out0[k1] = nil
			} else {
				out3 := make([]ArmyDoc, len(v2))
				for i4, v5 := range v2 {
					out3[i4] = ArmyStateToDoc(v5)
				}
				out0[k1] = out3
			}
		}
		out = out0
	}
	return out
}

func toState_armies(in map[CityID][]ArmyDoc) map[CityID][]entity.ArmyState {
	var out map[CityID][]entity.ArmyState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[CityID][]entity.ArmyState, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				out0[k1] = nil
			} else {
				out3 := make([]entity.ArmyState, len(v2))
				for i4, v5 := range v2 {
					out3[i4] = ArmyDocToState(v5)
				}
				out0[k1] = out3
			}
		}
		out = out0
	}
	return out
}

func toDocSlice_generals(in []entity.GeneralState) []GeneralDoc {
	if in == nil {
		return nil
	}
	out := make([]GeneralDoc, len(in))
	for i, v := range in {
		out[i] = GeneralStateToDoc(v)
	}
	return out
}

func toStateSlice_generals(in []GeneralDoc) []entity.GeneralState {
	if in == nil {
		return nil
	}
	out := make([]entity.GeneralState, len(in))
	for i, v := range in {
		out[i] = GeneralDocToState(v)
	}
	return out
}

func toDocSlice_facility(in []entity.FacilityState) []FacilityDoc {
	if in == nil {
		return nil
	}
	out := make([]FacilityDoc, len(in))
	for i, v := range in {
		out[i] = FacilityStateToDoc(v)
	}
	return out
}

func toStateSlice_facility(in []FacilityDoc) []entity.FacilityState {
	if in == nil {
		return nil
	}
	out := make([]entity.FacilityState, len(in))
	for i, v := range in {
		out[i] = FacilityDocToState(v)
	}
	return out
}

func toDocMap_warReports(in map[int]entity.WarReportState) map[int]WarReportDoc {
	if in == nil {
		return nil
	}
	out := make(map[int]WarReportDoc, len(in))
	for k, v := range in {
		out[k] = WarReportStateToDoc(v)
	}
	return out
}

func toStateMap_warReports(in map[int]WarReportDoc) map[int]entity.WarReportState {
	if in == nil {
		return nil
	}
	out := make(map[int]entity.WarReportState, len(in))
	for k, v := range in {
		out[k] = WarReportDocToState(v)
	}
	return out
}

func PlayerStateToDoc(s entity.PlayerState) PlayerDoc {
	state := entity.HydratePlayerEntity(s).Save()
	return PlayerDoc{
		PlayerID:   state.PlayerID,
		WorldID:    state.WorldID,
		Profile:    RoleStateToDoc(state.Profile),
		Resource:   ResourceStateToDoc(state.Resource),
		Attribute:  RoleAttributeStateToDoc(state.Attribute),
		X:          state.X,
		Y:          state.Y,
		Buildings:  toDocSlice_buildings(state.Buildings),
		Armies:     toDoc_armies(state.Armies),
		Generals:   toDocSlice_generals(state.Generals),
		Facility:   toDocSlice_facility(state.Facility),
		WarReports: toDocMap_warReports(state.WarReports),
	}
}

func PlayerDocToState(d PlayerDoc) entity.PlayerState {
	state := entity.PlayerState{
		PlayerID:   d.PlayerID,
		WorldID:    d.WorldID,
		Profile:    RoleDocToState(d.Profile),
		Resource:   ResourceDocToState(d.Resource),
		Attribute:  RoleAttributeDocToState(d.Attribute),
		X:          d.X,
		Y:          d.Y,
		Buildings:  toStateSlice_buildings(d.Buildings),
		Armies:     toState_armies(d.Armies),
		Generals:   toStateSlice_generals(d.Generals),
		Facility:   toStateSlice_facility(d.Facility),
		WarReports: toStateMap_warReports(d.WarReports),
	}
	return entity.HydratePlayerEntity(state).Save()
}
