// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type PosTagDoc struct {
	X    int    `bson:"x"`
	Y    int    `bson:"y"`
	Name string `bson:"name"`
}

func PosTagStateToDoc(s entity.PosTagState) PosTagDoc {
	state := entity.HydratePosTagEntity(s).Save()
	return PosTagDoc{
		X:    state.X,
		Y:    state.Y,
		Name: state.Name,
	}
}

func PosTagDocToState(d PosTagDoc) entity.PosTagState {
	state := entity.PosTagState{
		X:    d.X,
		Y:    d.Y,
		Name: d.Name,
	}
	return entity.HydratePosTagEntity(state).Save()
}
