// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type ResourceDoc struct {
	Wood   int `bson:"wood"`
	Iron   int `bson:"iron"`
	Stone  int `bson:"stone"`
	Grain  int `bson:"grain"`
	Gold   int `bson:"gold"`
	Decree int `bson:"decree"`
}

func ResourceStateToDoc(s entity.ResourceState) ResourceDoc {
	state := entity.HydrateResourceEntity(s).Save()
	return ResourceDoc{
		Wood:   state.Wood,
		Iron:   state.Iron,
		Stone:  state.Stone,
		Grain:  state.Grain,
		Gold:   state.Gold,
		Decree: state.Decree,
	}
}

func ResourceDocToState(d ResourceDoc) entity.ResourceState {
	state := entity.ResourceState{
		Wood:   d.Wood,
		Iron:   d.Iron,
		Stone:  d.Stone,
		Grain:  d.Grain,
		Gold:   d.Gold,
		Decree: d.Decree,
	}
	return entity.HydrateResourceEntity(state).Save()
}
