// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
	"time"
)

type RoleDoc struct {
	Headid     int16     `bson:"headid"`
	Sex        int8      `bson:"sex"`
	NickName   string    `bson:"nick_name"`
	Balance    int       `bson:"balance"`
	LoginTime  time.Time `bson:"login_time"`
	LogoutTime time.Time `bson:"logout_time"`
	Profile    string    `bson:"profile"`
	CreatedAt  time.Time `bson:"created_at"`
}

func RoleStateToDoc(s entity.RoleState) RoleDoc {
	state := entity.HydrateRoleEntity(s).Save()
	return RoleDoc{
		Headid:     state.Headid,
		Sex:        state.Sex,
		NickName:   state.NickName,
		Balance:    state.Balance,
		LoginTime:  state.LoginTime,
		LogoutTime: state.LogoutTime,
		Profile:    state.Profile,
		CreatedAt:  state.CreatedAt,
	}
}

func RoleDocToState(d RoleDoc) entity.RoleState {
	state := entity.RoleState{
		Headid:     d.Headid,
		Sex:        d.Sex,
		NickName:   d.NickName,
		Balance:    d.Balance,
		LoginTime:  d.LoginTime,
		LogoutTime: d.LogoutTime,
		Profile:    d.Profile,
		CreatedAt:  d.CreatedAt,
	}
	return entity.HydrateRoleEntity(state).Save()
}
