// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
	"time"
)

type RoleAttributeDoc struct {
	ParentId        int       `bson:"parent_id"`
	CollectTimes    int8      `bson:"collect_times"`
	LastCollectTime time.Time `bson:"last_collect_time"`
	PosTags         string    `bson:"pos_tags"`
}

func RoleAttributeStateToDoc(s entity.RoleAttributeState) RoleAttributeDoc {
	state := entity.HydrateRoleAttributeEntity(s).Save()
	return RoleAttributeDoc{
		ParentId:        state.ParentId,
		CollectTimes:    state.CollectTimes,
		LastCollectTime: state.LastCollectTime,
		PosTags:         state.PosTags,
	}
}

func RoleAttributeDocToState(d RoleAttributeDoc) entity.RoleAttributeState {
	state := entity.RoleAttributeState{
		ParentId:        d.ParentId,
		CollectTimes:    d.CollectTimes,
		LastCollectTime: d.LastCollectTime,
		PosTags:         d.PosTags,
	}
	return entity.HydrateRoleAttributeEntity(state).Save()
}
