// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type SkillDoc struct {
	Id             int    `bson:"id"`
	CfgId          int    `bson:"cfg_id"`
	BelongGenerals string `bson:"belong_generals"`
	Generals       []int  `bson:"generals"`
}

func SkillStateToDoc(s entity.SkillState) SkillDoc {
	state := entity.HydrateSkillEntity(s).Save()
	return SkillDoc{
		Id:             state.Id,
		CfgId:          state.CfgId,
		BelongGenerals: state.BelongGenerals,
		Generals:       state.Generals,
	}
}

func SkillDocToState(d SkillDoc) entity.SkillState {
	state := entity.SkillState{
		Id:             d.Id,
		CfgId:          d.CfgId,
		BelongGenerals: d.BelongGenerals,
		Generals:       d.Generals,
	}
	return entity.HydrateSkillEntity(state).Save()
}
