// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type PlayerID = entity.PlayerID

type WorldID = entity.WorldID

type RoleStatus = entity.RoleStatus

type PosTag = entity.PosTag
