// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/player/entity"
)

type WarReportDoc struct {
	Id                int        `bson:"id"`
	Attacker          int        `bson:"attacker"`
	Defender          int        `bson:"defender"`
	BegAttackArmy     ArmyDoc    `bson:"beg_attack_army"`
	BegDefenseArmy    ArmyDoc    `bson:"beg_defense_army"`
	EndAttackArmy     ArmyDoc    `bson:"end_attack_army"`
	EndDefenseArmy    ArmyDoc    `bson:"end_defense_army"`
	BegAttackGeneral  GeneralDoc `bson:"beg_attack_general"`
	BegDefenseGeneral GeneralDoc `bson:"beg_defense_general"`
	EndAttackGeneral  GeneralDoc `bson:"end_attack_general"`
	EndDefenseGeneral GeneralDoc `bson:"end_defense_general"`
	Result            int        `bson:"result"`
	Rounds            string     `bson:"rounds"`
	AttackIsRead      bool       `bson:"attack_is_read"`
	DefenseIsRead     bool       `bson:"defense_is_read"`
	DestroyDurable    int        `bson:"destroy_durable"`
	Occupy            int        `bson:"occupy"`
	X                 int        `bson:"x"`
	Y                 int        `bson:"y"`
	CTime             int        `bson:"c_time"`
}

func WarReportStateToDoc(s entity.WarReportState) WarReportDoc {
	state := entity.HydrateWarReportEntity(s).Save()
	return WarReportDoc{
		Id:                state.Id,
		Attacker:          state.Attacker,
		Defender:          state.Defender,
		BegAttackArmy:     ArmyStateToDoc(state.BegAttackArmy),
		BegDefenseArmy:    ArmyStateToDoc(state.BegDefenseArmy),
		EndAttackArmy:     ArmyStateToDoc(state.EndAttackArmy),
		EndDefenseArmy:    ArmyStateToDoc(state.EndDefenseArmy),
		BegAttackGeneral:  GeneralStateToDoc(state.BegAttackGeneral),
		BegDefenseGeneral: GeneralStateToDoc(state.BegDefenseGeneral),
		EndAttackGeneral:  GeneralStateToDoc(state.EndAttackGeneral),
		EndDefenseGeneral: GeneralStateToDoc(state.EndDefenseGeneral),
		Result:            state.Result,
		Rounds:            state.Rounds,
		AttackIsRead:      state.AttackIsRead,
		DefenseIsRead:     state.DefenseIsRead,
		DestroyDurable:    state.DestroyDurable,
		Occupy:            state.Occupy,
		X:                 state.X,
		Y:                 state.Y,
		CTime:             state.CTime,
	}
}

func WarReportDocToState(d WarReportDoc) entity.WarReportState {
	state := entity.WarReportState{
		Id:                d.Id,
		Attacker:          d.Attacker,
		Defender:          d.Defender,
		BegAttackArmy:     ArmyDocToState(d.BegAttackArmy),
		BegDefenseArmy:    ArmyDocToState(d.BegDefenseArmy),
		EndAttackArmy:     ArmyDocToState(d.EndAttackArmy),
		EndDefenseArmy:    ArmyDocToState(d.EndDefenseArmy),
		BegAttackGeneral:  GeneralDocToState(d.BegAttackGeneral),
		BegDefenseGeneral: GeneralDocToState(d.BegDefenseGeneral),
		EndAttackGeneral:  GeneralDocToState(d.EndAttackGeneral),
		EndDefenseGeneral: GeneralDocToState(d.EndDefenseGeneral),
		Result:            d.Result,
		Rounds:            d.Rounds,
		AttackIsRead:      d.AttackIsRead,
		DefenseIsRead:     d.DefenseIsRead,
		DestroyDurable:    d.DestroyDurable,
		Occupy:            d.Occupy,
		X:                 d.X,
		Y:                 d.Y,
		CTime:             d.CTime,
	}
	return entity.HydrateWarReportEntity(state).Save()
}
