// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/alliance/entity"
)

type AllianceDoc struct {
	Id      AllianceID             `bson:"id"`
	WorldId WorldID                `bson:"world_id"`
	Name    string                 `bson:"name"`
	Notice  string                 `bson:"notice"`
	Majors  map[PlayerID]MajorDoc  `bson:"majors"`
	Members map[PlayerID]MemberDoc `bson:"members"`
}

func toDocMap_majors(in map[PlayerID]entity.MajorState) map[PlayerID]MajorDoc {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]MajorDoc, len(in))
	for k, v := range in {
		out[k] = MajorStateToDoc(v)
	}
	return out
}

func toStateMap_majors(in map[PlayerID]MajorDoc) map[PlayerID]entity.MajorState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]entity.MajorState, len(in))
	for k, v := range in {
		out[k] = MajorDocToState(v)
	}
	return out
}

func toDocMap_members(in map[PlayerID]entity.MemberState) map[PlayerID]MemberDoc {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]MemberDoc, len(in))
	for k, v := range in {
		out[k] = MemberStateToDoc(v)
	}
	return out
}

func toStateMap_members(in map[PlayerID]MemberDoc) map[PlayerID]entity.MemberState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]entity.MemberState, len(in))
	for k, v := range in {
		out[k] = MemberDocToState(v)
	}
	return out
}

func AllianceStateToDoc(s entity.AllianceState) AllianceDoc {
	state := entity.HydrateAllianceEntity(s).Save()
	return AllianceDoc{
		Id:      state.Id,
		WorldId: state.WorldId,
		Name:    state.Name,
		Notice:  state.Notice,
		Majors:  toDocMap_majors(state.Majors),
		Members: toDocMap_members(state.Members),
	}
}

func AllianceDocToState(d AllianceDoc) entity.AllianceState {
	state := entity.AllianceState{
		Id:      d.Id,
		WorldId: d.WorldId,
		Name:    d.Name,
		Notice:  d.Notice,
		Majors:  toStateMap_majors(d.Majors),
		Members: toStateMap_members(d.Members),
	}
	return entity.HydrateAllianceEntity(state).Save()
}
