// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/alliance/entity"
)

type MajorDoc struct {
	Id    PlayerID `bson:"id"`
	Name  string   `bson:"name"`
	Title int8     `bson:"title"`
}

func MajorStateToDoc(s entity.MajorState) MajorDoc {
	state := entity.HydrateMajorEntity(s).Save()
	return MajorDoc{
		Id:    state.Id,
		Name:  state.Name,
		Title: state.Title,
	}
}

func MajorDocToState(d MajorDoc) entity.MajorState {
	state := entity.MajorState{
		Id:    d.Id,
		Name:  d.Name,
		Title: d.Title,
	}
	return entity.HydrateMajorEntity(state).Save()
}
