// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/alliance/entity"
)

type MemberDoc struct {
	Id    PlayerID `bson:"id"`
	Name  string   `bson:"name"`
	Title int8     `bson:"title"`
	Pos   PosDoc   `bson:"pos"`
}

func MemberStateToDoc(s entity.MemberState) MemberDoc {
	state := entity.HydrateMemberEntity(s).Save()
	return MemberDoc{
		Id:    state.Id,
		Name:  state.Name,
		Title: state.Title,
		Pos:   PosStateToDoc(state.Pos),
	}
}

func MemberDocToState(d MemberDoc) entity.MemberState {
	state := entity.MemberState{
		Id:    d.Id,
		Name:  d.Name,
		Title: d.Title,
		Pos:   PosDocToState(d.Pos),
	}
	return entity.HydrateMemberEntity(state).Save()
}
