// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
)

type CellDoc struct {
	CellType int8   `bson:"cell_type"`
	Name     string `bson:"name"`
	Level    int8   `bson:"level"`
	Grain    int    `bson:"grain"`
	Wood     int    `bson:"wood"`
	Iron     int    `bson:"iron"`
	Stone    int    `bson:"stone"`
	Durable  int    `bson:"durable"`
	Defender int    `bson:"defender"`
}

func CellStateToDoc(s entity.CellState) CellDoc {
	state := entity.HydrateCellEntity(s).Save()
	return CellDoc{
		CellType: state.CellType,
		Name:     state.Name,
		Level:    state.Level,
		Grain:    state.Grain,
		Wood:     state.Wood,
		Iron:     state.Iron,
		Stone:    state.Stone,
		Durable:  state.Durable,
		Defender: state.Defender,
	}
}

func CellDocToState(d CellDoc) entity.CellState {
	state := entity.CellState{
		CellType: d.CellType,
		Name:     d.Name,
		Level:    d.Level,
		Grain:    d.Grain,
		Wood:     d.Wood,
		Iron:     d.Iron,
		Stone:    d.Stone,
		Durable:  d.Durable,
		Defender: d.Defender,
	}
	return entity.HydrateCellEntity(state).Save()
}
