// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
	"time"
)

type CityDoc struct {
	CityId     CityID    `bson:"city_id"`
	Name       string    `bson:"name"`
	UnionId    int       `bson:"union_id"`
	UnionName  string    `bson:"union_name"`
	ParentId   int       `bson:"parent_id"`
	X          int       `bson:"x"`
	Y          int       `bson:"y"`
	IsMain     bool      `bson:"is_main"`
	Level      int8      `bson:"level"`
	CurDurable int       `bson:"cur_durable"`
	MaxDurable int       `bson:"max_durable"`
	OccupyTime time.Time `bson:"occupy_time"`
}

func CityStateToDoc(s entity.CityState) CityDoc {
	state := entity.HydrateCityEntity(s).Save()
	return CityDoc{
		CityId:     state.CityId,
		Name:       state.Name,
		UnionId:    state.UnionId,
		UnionName:  state.UnionName,
		ParentId:   state.ParentId,
		X:          state.X,
		Y:          state.Y,
		IsMain:     state.IsMain,
		Level:      state.Level,
		CurDurable: state.CurDurable,
		MaxDurable: state.MaxDurable,
		OccupyTime: state.OccupyTime,
	}
}

func CityDocToState(d CityDoc) entity.CityState {
	state := entity.CityState{
		CityId:     d.CityId,
		Name:       d.Name,
		UnionId:    d.UnionId,
		UnionName:  d.UnionName,
		ParentId:   d.ParentId,
		X:          d.X,
		Y:          d.Y,
		IsMain:     d.IsMain,
		Level:      d.Level,
		CurDurable: d.CurDurable,
		MaxDurable: d.MaxDurable,
		OccupyTime: d.OccupyTime,
	}
	return entity.HydrateCityEntity(state).Save()
}
