// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
)

type GarrisonDoc struct {
	Owner  int    `bson:"owner"`
	ArmyId ArmyID `bson:"army_id"`
}

func GarrisonStateToDoc(s entity.GarrisonState) GarrisonDoc {
	state := entity.HydrateGarrisonEntity(s).Save()
	return GarrisonDoc{
		Owner:  state.Owner,
		ArmyId: state.ArmyId,
	}
}

func GarrisonDocToState(d GarrisonDoc) entity.GarrisonState {
	state := entity.GarrisonState{
		Owner:  d.Owner,
		ArmyId: d.ArmyId,
	}
	return entity.HydrateGarrisonEntity(state).Save()
}
