// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
	"time"
)

type MarchDoc struct {
	PlayerID PlayerID  `bson:"player_id"`
	ArmyID   ArmyID    `bson:"army_id"`
	From     PosDoc    `bson:"from"`
	To       PosDoc    `bson:"to"`
	StartAt  time.Time `bson:"start_at"`
	ArriveAt time.Time `bson:"arrive_at"`
}

func MarchStateToDoc(s entity.MarchState) MarchDoc {
	state := entity.HydrateMarchEntity(s).Save()
	return MarchDoc{
		PlayerID: state.PlayerID,
		ArmyID:   state.ArmyID,
		From:     PosStateToDoc(state.From),
		To:       PosStateToDoc(state.To),
		StartAt:  state.StartAt,
		ArriveAt: state.ArriveAt,
	}
}

func MarchDocToState(d MarchDoc) entity.MarchState {
	state := entity.MarchState{
		PlayerID: d.PlayerID,
		ArmyID:   d.ArmyID,
		From:     PosDocToState(d.From),
		To:       PosDocToState(d.To),
		StartAt:  d.StartAt,
		ArriveAt: d.ArriveAt,
	}
	return entity.HydrateMarchEntity(state).Save()
}
