// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
)

type PosDoc struct {
	X int `bson:"x"`
	Y int `bson:"y"`
}

func PosStateToDoc(s entity.PosState) PosDoc {
	state := entity.HydratePosEntity(s).Save()
	return PosDoc{
		X: state.X,
		Y: state.Y,
	}
}

func PosDocToState(d PosDoc) entity.PosState {
	state := entity.PosState{
		X: d.X,
		Y: d.Y,
	}
	return entity.HydratePosEntity(state).Save()
}
