// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
)

type WorldID = entity.WorldID

type PlayerID = entity.PlayerID

type CityID = entity.CityID
