// Code generated by gen_entities; DO NOT EDIT.
package model

import (
	entity "ThreeKingdoms/internal/world/entity"
)

type WorldDoc struct {
	WorldId      WorldID                         `bson:"world_id"`
	CityByPlayer map[PlayerID]map[CityID]CityDoc `bson:"city_by_player"`
	WorldMap     []CellDoc                       `bson:"world_map"`
}

func toDoc_cityByPlayer(in map[PlayerID]map[CityID]entity.CityState) map[PlayerID]map[CityID]CityDoc {
	var out map[PlayerID]map[CityID]CityDoc
	if in == nil {
		out = nil
	} else {
		out0 := make(map[PlayerID]map[CityID]CityDoc, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				out0[k1] = nil
			} else {
				out3 := make(map[CityID]CityDoc, len(v2))
				for k4, v5 := range v2 {
					out3[k4] = CityStateToDoc(v5)
				}
				out0[k1] = out3
			}
		}
		out = out0
	}
	return out
}

func toState_cityByPlayer(in map[PlayerID]map[CityID]CityDoc) map[PlayerID]map[CityID]entity.CityState {
	var out map[PlayerID]map[CityID]entity.CityState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[PlayerID]map[CityID]entity.CityState, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				out0[k1] = nil
			} else {
				out3 := make(map[CityID]entity.CityState, len(v2))
				for k4, v5 := range v2 {
					out3[k4] = CityDocToState(v5)
				}
				out0[k1] = out3
			}
		}
		out = out0
	}
	return out
}

func toDocSlice_worldMap(in []entity.CellState) []CellDoc {
	if in == nil {
		return nil
	}
	out := make([]CellDoc, len(in))
	for i, v := range in {
		out[i] = CellStateToDoc(v)
	}
	return out
}

func toStateSlice_worldMap(in []CellDoc) []entity.CellState {
	if in == nil {
		return nil
	}
	out := make([]entity.CellState, len(in))
	for i, v := range in {
		out[i] = CellDocToState(v)
	}
	return out
}

func WorldStateToDoc(s entity.WorldState) WorldDoc {
	state := entity.HydrateWorldEntity(s).Save()
	return WorldDoc{
		WorldId:      state.WorldId,
		CityByPlayer: toDoc_cityByPlayer(state.CityByPlayer),
		WorldMap:     toDocSlice_worldMap(state.WorldMap),
	}
}

func WorldDocToState(d WorldDoc) entity.WorldState {
	state := entity.WorldState{
		WorldId:      d.WorldId,
		CityByPlayer: toState_cityByPlayer(d.CityByPlayer),
		WorldMap:     toStateSlice_worldMap(d.WorldMap),
	}
	return entity.HydrateWorldEntity(state).Save()
}
