// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
	"time"
)

const (
	FieldMarch_playerId   Field = "playerId"
	FieldMarch_allianceId Field = "allianceId"
	FieldMarch_armyID     Field = "armyID"
	FieldMarch_from       Field = "from"
	FieldMarch_to         Field = "to"
	FieldMarch_startAt    Field = "startAt"
	FieldMarch_arriveAt   Field = "arriveAt"
)

var emptyMarchEntity = &MarchEntity{}

type MarchEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type MarchEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type MarchEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*MarchEntityCollectionChangeInner
}

func (t *MarchEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *MarchEntityTrace) ensureChange(f Field) *MarchEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*MarchEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &MarchEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *MarchEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *MarchEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *MarchEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *MarchEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *MarchEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *MarchEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *MarchEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type MarchState struct {
	PlayerId   PlayerID
	AllianceId AllianceID
	ArmyID     ArmyID
	From       PosState
	To         PosState
	StartAt    time.Time
	ArriveAt   time.Time
}

type MarchEntitySnap struct {
	Version     uint64
	State       MarchState
	DirtyFields []Field
	Changes     map[Field]MarchEntityCollectionChange
}

type MarchEntity struct {
	playerId   PlayerID
	allianceId AllianceID
	armyID     ArmyID
	from       *PosEntity
	to         *PosEntity
	startAt    time.Time
	arriveAt   time.Time
	_dt        MarchEntityTrace
}

func HydrateMarchEntity(s MarchState) *MarchEntity {
	return &MarchEntity{
		playerId:   s.PlayerId,
		allianceId: s.AllianceId,
		armyID:     s.ArmyID,
		from:       HydratePosEntity(s.From),
		to:         HydratePosEntity(s.To),
		startAt:    s.StartAt,
		arriveAt:   s.ArriveAt,
	}
}

func (e *MarchEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	if e.from != nil && e.from.Dirty() {
		return true
	}
	if e.to != nil && e.to.Dirty() {
		return true
	}
	return false
}

func (e *MarchEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = MarchEntityTrace{}
	if e.from != nil {
		e.from.ClearDirty()
	}
	if e.to != nil {
		e.to.ClearDirty()
	}
}

func (e *MarchEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if e.from != nil && e.from.Dirty() {
		trace[FieldMarch_from] = true
	}
	if e.to != nil && e.to.Dirty() {
		trace[FieldMarch_to] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *MarchEntity) DirtyChanges() map[Field]MarchEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]MarchEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := MarchEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneMarchEntityCollectionChange(in MarchEntityCollectionChange) MarchEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *MarchEntity) Save() MarchState {
	var s MarchState
	if e == nil {
		return s
	}
	s.PlayerId = e.playerId
	s.AllianceId = e.allianceId
	s.ArmyID = e.armyID
	if e.from != nil {
		s.From = e.from.Save()
	} else {
		var z PosState
		s.From = z
	}
	if e.to != nil {
		s.To = e.to.Save()
	} else {
		var z PosState
		s.To = z
	}
	s.StartAt = e.startAt
	s.ArriveAt = e.arriveAt
	return s
}

func NewMarchEntitySnap(version uint64, e *MarchEntity) *MarchEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &MarchEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *MarchEntitySnap) Clone() *MarchEntitySnap {
	if s == nil {
		return nil
	}
	out := &MarchEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]MarchEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneMarchEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *MarchEntity) PlayerId() PlayerID {
	if e == nil {
		var z PlayerID
		return z
	}
	return e.playerId
}

func (e *MarchEntity) SetPlayerId(v PlayerID) bool {
	if e == nil {
		return false
	}
	if e.playerId == v {
		return false
	}
	e.playerId = v
	e._dt.mark(FieldMarch_playerId)
	return true
}

func (e *MarchEntity) AllianceId() AllianceID {
	if e == nil {
		var z AllianceID
		return z
	}
	return e.allianceId
}

func (e *MarchEntity) SetAllianceId(v AllianceID) bool {
	if e == nil {
		return false
	}
	if e.allianceId == v {
		return false
	}
	e.allianceId = v
	e._dt.mark(FieldMarch_allianceId)
	return true
}

func (e *MarchEntity) ArmyID() ArmyID {
	if e == nil {
		var z ArmyID
		return z
	}
	return e.armyID
}

func (e *MarchEntity) SetArmyID(v ArmyID) bool {
	if e == nil {
		return false
	}
	if e.armyID == v {
		return false
	}
	e.armyID = v
	e._dt.mark(FieldMarch_armyID)
	return true
}

func (e *MarchEntity) From() *PosEntity {
	if e == nil {
		return nil
	}
	return e.from
}

func (e *MarchEntity) SetFrom(v PosState) bool {
	if e == nil {
		return false
	}
	next := HydratePosEntity(v)
	if e.from == next {
		return false
	}
	e.from = next
	e._dt.mark(FieldMarch_from)
	return true
}

func (e *MarchEntity) SetFromEntity(v *PosEntity) bool {
	if e == nil {
		return false
	}
	if e.from == v {
		return false
	}
	e.from = v
	e._dt.mark(FieldMarch_from)
	return true
}

func (e *MarchEntity) UpdateFrom(fn func(value *PosEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.from == nil {
		e.from = &PosEntity{}
	}
	fn(e.from)
	e._dt.mark(FieldMarch_from)
	return true
}

func (e *MarchEntity) To() *PosEntity {
	if e == nil {
		return nil
	}
	return e.to
}

func (e *MarchEntity) SetTo(v PosState) bool {
	if e == nil {
		return false
	}
	next := HydratePosEntity(v)
	if e.to == next {
		return false
	}
	e.to = next
	e._dt.mark(FieldMarch_to)
	return true
}

func (e *MarchEntity) SetToEntity(v *PosEntity) bool {
	if e == nil {
		return false
	}
	if e.to == v {
		return false
	}
	e.to = v
	e._dt.mark(FieldMarch_to)
	return true
}

func (e *MarchEntity) UpdateTo(fn func(value *PosEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.to == nil {
		e.to = &PosEntity{}
	}
	fn(e.to)
	e._dt.mark(FieldMarch_to)
	return true
}

func (e *MarchEntity) StartAt() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.startAt
}

func (e *MarchEntity) SetStartAt(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.startAt.Equal(v) {
		return false
	}
	e.startAt = v
	e._dt.mark(FieldMarch_startAt)
	return true
}

func (e *MarchEntity) ArriveAt() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.arriveAt
}

func (e *MarchEntity) SetArriveAt(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.arriveAt.Equal(v) {
		return false
	}
	e.arriveAt = v
	e._dt.mark(FieldMarch_arriveAt)
	return true
}
