// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldOccupancy_kind      Field = "kind"
	FieldOccupancy_refId     Field = "refId"
	FieldOccupancy_owner     Field = "owner"
	FieldOccupancy_roleNick  Field = "roleNick"
	FieldOccupancy_unionId   Field = "unionId"
	FieldOccupancy_unionName Field = "unionName"
	FieldOccupancy_parentId  Field = "parentId"
	FieldOccupancy_garrison  Field = "garrison"
)

var emptyOccupancyEntity = &OccupancyEntity{}

type OccupancyEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type OccupancyEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type OccupancyEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*OccupancyEntityCollectionChangeInner
}

func (t *OccupancyEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *OccupancyEntityTrace) ensureChange(f Field) *OccupancyEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*OccupancyEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &OccupancyEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *OccupancyEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *OccupancyEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *OccupancyEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *OccupancyEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *OccupancyEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *OccupancyEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *OccupancyEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type OccupancyState struct {
	Kind      int8
	RefId     int
	Owner     int
	RoleNick  string
	UnionId   int
	UnionName string
	ParentId  int
	Garrison  GarrisonState
}

type OccupancyEntitySnap struct {
	Version     uint64
	State       OccupancyState
	DirtyFields []Field
	Changes     map[Field]OccupancyEntityCollectionChange
}

type OccupancyEntity struct {
	kind      int8
	refId     int
	owner     int
	roleNick  string
	unionId   int
	unionName string
	parentId  int
	garrison  *GarrisonEntity
	_dt       OccupancyEntityTrace
}

func HydrateOccupancyEntity(s OccupancyState) *OccupancyEntity {
	return &OccupancyEntity{
		kind:      s.Kind,
		refId:     s.RefId,
		owner:     s.Owner,
		roleNick:  s.RoleNick,
		unionId:   s.UnionId,
		unionName: s.UnionName,
		parentId:  s.ParentId,
		garrison:  HydrateGarrisonEntity(s.Garrison),
	}
}

func (e *OccupancyEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	if e.garrison != nil && e.garrison.Dirty() {
		return true
	}
	return false
}

func (e *OccupancyEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = OccupancyEntityTrace{}
	if e.garrison != nil {
		e.garrison.ClearDirty()
	}
}

func (e *OccupancyEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if e.garrison != nil && e.garrison.Dirty() {
		trace[FieldOccupancy_garrison] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *OccupancyEntity) DirtyChanges() map[Field]OccupancyEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]OccupancyEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := OccupancyEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneOccupancyEntityCollectionChange(in OccupancyEntityCollectionChange) OccupancyEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *OccupancyEntity) Save() OccupancyState {
	var s OccupancyState
	if e == nil {
		return s
	}
	s.Kind = e.kind
	s.RefId = e.refId
	s.Owner = e.owner
	s.RoleNick = e.roleNick
	s.UnionId = e.unionId
	s.UnionName = e.unionName
	s.ParentId = e.parentId
	if e.garrison != nil {
		s.Garrison = e.garrison.Save()
	} else {
		var z GarrisonState
		s.Garrison = z
	}
	return s
}

func NewOccupancyEntitySnap(version uint64, e *OccupancyEntity) *OccupancyEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &OccupancyEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *OccupancyEntitySnap) Clone() *OccupancyEntitySnap {
	if s == nil {
		return nil
	}
	out := &OccupancyEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]OccupancyEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneOccupancyEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *OccupancyEntity) Kind() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.kind
}

func (e *OccupancyEntity) SetKind(v int8) bool {
	if e == nil {
		return false
	}
	if e.kind == v {
		return false
	}
	e.kind = v
	e._dt.mark(FieldOccupancy_kind)
	return true
}

func (e *OccupancyEntity) RefId() int {
	if e == nil {
		var z int
		return z
	}
	return e.refId
}

func (e *OccupancyEntity) SetRefId(v int) bool {
	if e == nil {
		return false
	}
	if e.refId == v {
		return false
	}
	e.refId = v
	e._dt.mark(FieldOccupancy_refId)
	return true
}

func (e *OccupancyEntity) Owner() int {
	if e == nil {
		var z int
		return z
	}
	return e.owner
}

func (e *OccupancyEntity) SetOwner(v int) bool {
	if e == nil {
		return false
	}
	if e.owner == v {
		return false
	}
	e.owner = v
	e._dt.mark(FieldOccupancy_owner)
	return true
}

func (e *OccupancyEntity) RoleNick() string {
	if e == nil {
		var z string
		return z
	}
	return e.roleNick
}

func (e *OccupancyEntity) SetRoleNick(v string) bool {
	if e == nil {
		return false
	}
	if e.roleNick == v {
		return false
	}
	e.roleNick = v
	e._dt.mark(FieldOccupancy_roleNick)
	return true
}

func (e *OccupancyEntity) UnionId() int {
	if e == nil {
		var z int
		return z
	}
	return e.unionId
}

func (e *OccupancyEntity) SetUnionId(v int) bool {
	if e == nil {
		return false
	}
	if e.unionId == v {
		return false
	}
	e.unionId = v
	e._dt.mark(FieldOccupancy_unionId)
	return true
}

func (e *OccupancyEntity) UnionName() string {
	if e == nil {
		var z string
		return z
	}
	return e.unionName
}

func (e *OccupancyEntity) SetUnionName(v string) bool {
	if e == nil {
		return false
	}
	if e.unionName == v {
		return false
	}
	e.unionName = v
	e._dt.mark(FieldOccupancy_unionName)
	return true
}

func (e *OccupancyEntity) ParentId() int {
	if e == nil {
		var z int
		return z
	}
	return e.parentId
}

func (e *OccupancyEntity) SetParentId(v int) bool {
	if e == nil {
		return false
	}
	if e.parentId == v {
		return false
	}
	e.parentId = v
	e._dt.mark(FieldOccupancy_parentId)
	return true
}

func (e *OccupancyEntity) Garrison() *GarrisonEntity {
	if e == nil {
		return nil
	}
	return e.garrison
}

func (e *OccupancyEntity) SetGarrison(v GarrisonState) bool {
	if e == nil {
		return false
	}
	next := HydrateGarrisonEntity(v)
	if e.garrison == next {
		return false
	}
	e.garrison = next
	e._dt.mark(FieldOccupancy_garrison)
	return true
}

func (e *OccupancyEntity) SetGarrisonEntity(v *GarrisonEntity) bool {
	if e == nil {
		return false
	}
	if e.garrison == v {
		return false
	}
	e.garrison = v
	e._dt.mark(FieldOccupancy_garrison)
	return true
}

func (e *OccupancyEntity) UpdateGarrison(fn func(value *GarrisonEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.garrison == nil {
		e.garrison = &GarrisonEntity{}
	}
	fn(e.garrison)
	e._dt.mark(FieldOccupancy_garrison)
	return true
}
