// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldSkill_id             Field = "id"
	FieldSkill_cfgId          Field = "cfgId"
	FieldSkill_belongGenerals Field = "belongGenerals"
	FieldSkill_generals       Field = "generals"
)

var emptySkillEntity = &SkillEntity{}

type SkillEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type SkillEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type SkillEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*SkillEntityCollectionChangeInner
}

func (t *SkillEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *SkillEntityTrace) ensureChange(f Field) *SkillEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*SkillEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &SkillEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *SkillEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *SkillEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *SkillEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *SkillEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *SkillEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *SkillEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *SkillEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type SkillState struct {
	Id             int
	CfgId          int
	BelongGenerals string
	Generals       []int
}

type SkillEntitySnap struct {
	Version     uint64
	State       SkillState
	DirtyFields []Field
	Changes     map[Field]SkillEntityCollectionChange
}

type SkillEntity struct {
	id             int
	cfgId          int
	belongGenerals string
	generals       []int
	_dt            SkillEntityTrace
}

func (e *SkillEntity) slicesEqualGenerals(a, b []int) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func HydrateSkillEntity(s SkillState) *SkillEntity {
	return &SkillEntity{
		id:             s.Id,
		cfgId:          s.CfgId,
		belongGenerals: s.BelongGenerals,
		generals:       append([]int(nil), s.Generals...),
	}
}

func (e *SkillEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *SkillEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = SkillEntityTrace{}
}

func (e *SkillEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *SkillEntity) DirtyChanges() map[Field]SkillEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]SkillEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := SkillEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneSkillEntityCollectionChange(in SkillEntityCollectionChange) SkillEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *SkillEntity) Save() SkillState {
	var s SkillState
	if e == nil {
		return s
	}
	s.Id = e.id
	s.CfgId = e.cfgId
	s.BelongGenerals = e.belongGenerals
	s.Generals = append([]int(nil), e.generals...)
	return s
}

func NewSkillEntitySnap(version uint64, e *SkillEntity) *SkillEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &SkillEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *SkillEntitySnap) Clone() *SkillEntitySnap {
	if s == nil {
		return nil
	}
	out := &SkillEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]SkillEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneSkillEntityCollectionChange(ch)
		}
	}
	out.State.Generals = append([]int(nil), s.State.Generals...)
	return out
}

func (e *SkillEntity) Id() int {
	if e == nil {
		var z int
		return z
	}
	return e.id
}

func (e *SkillEntity) SetId(v int) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldSkill_id)
	return true
}

func (e *SkillEntity) CfgId() int {
	if e == nil {
		var z int
		return z
	}
	return e.cfgId
}

func (e *SkillEntity) SetCfgId(v int) bool {
	if e == nil {
		return false
	}
	if e.cfgId == v {
		return false
	}
	e.cfgId = v
	e._dt.mark(FieldSkill_cfgId)
	return true
}

func (e *SkillEntity) BelongGenerals() string {
	if e == nil {
		var z string
		return z
	}
	return e.belongGenerals
}

func (e *SkillEntity) SetBelongGenerals(v string) bool {
	if e == nil {
		return false
	}
	if e.belongGenerals == v {
		return false
	}
	e.belongGenerals = v
	e._dt.mark(FieldSkill_belongGenerals)
	return true
}

func (e *SkillEntity) LenGenerals() int {
	if e == nil {
		return 0
	}
	return len(e.generals)
}

func (e *SkillEntity) AtGenerals(index int) (int, bool) {
	var z int
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.generals) {
		return z, false
	}
	return e.generals[index], true
}

func (e *SkillEntity) ForEachGenerals(fn func(index int, value int)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.generals {
		fn(i, v)
	}
}

func (e *SkillEntity) RangeGenerals(fn func(index int, value int) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.generals {
		if !fn(i, v) {
			return
		}
	}
}

func (e *SkillEntity) ReplaceGenerals(v []int) bool {
	if e == nil {
		return false
	}
	if e.slicesEqualGenerals(e.generals, v) {
		return false
	}
	e.generals = append([]int(nil), v...)
	e._dt.markFullReplace(FieldSkill_generals)
	return true
}

func (e *SkillEntity) AppendGenerals(values ...int) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	e.generals = append(e.generals, values...)
	for _, v := range values {
		e._dt.markSliceAppend(FieldSkill_generals, v)
	}
	return true
}

func (e *SkillEntity) SetGeneralsAt(index int, value int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.generals) {
		return false
	}
	if e.generals[index] == value {
		return false
	}
	e.generals[index] = value
	e._dt.markSliceSet(FieldSkill_generals, index, value)
	return true
}

func (e *SkillEntity) RemoveGeneralsAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.generals) {
		return false
	}
	e.generals = append(e.generals[:index], e.generals[index+1:]...)
	e._dt.markSliceRemoveAt(FieldSkill_generals, index)
	return true
}

func (e *SkillEntity) SwapRemoveGeneralsAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.generals) {
		return false
	}
	last := len(e.generals) - 1
	if index != last {
		e.generals[index] = e.generals[last]
	}
	e.generals = e.generals[:last]
	e._dt.markSliceSwapRemoveAt(FieldSkill_generals, index)
	return true
}

func (e *SkillEntity) ClearGenerals() bool {
	if e == nil {
		return false
	}
	if len(e.generals) == 0 {
		return false
	}
	e.generals = nil
	e._dt.markFullReplace(FieldSkill_generals)
	return true
}
