// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"fmt"
	"reflect"
	"sort"
)

const (
	FieldWorld_worldId      Field = "worldId"
	FieldWorld_cityByPlayer Field = "cityByPlayer"
	FieldWorld_worldMap     Field = "worldMap"
	FieldWorld_armies       Field = "armies"
	FieldWorld_marches      Field = "marches"
	FieldWorld_cellToMarch  Field = "cellToMarch"
)

var emptyWorldEntity = &WorldEntity{}

type WorldEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type WorldEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type WorldEntityTrace struct {
	dirty               bool
	trace               map[Field]bool
	changes             map[Field]*WorldEntityCollectionChangeInner
	childDirty_worldMap map[int]struct{}
}

func (t *WorldEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *WorldEntityTrace) ensureChange(f Field) *WorldEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*WorldEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &WorldEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *WorldEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *WorldEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *WorldEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *WorldEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *WorldEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *WorldEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *WorldEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

func (t *WorldEntityTrace) markChildDirty_worldMap(f Field, key int) {
	t.mark(f)
	if t.childDirty_worldMap == nil {
		t.childDirty_worldMap = make(map[int]struct{}, 8)
	}
	t.childDirty_worldMap[key] = struct{}{}
}

func (t *WorldEntityTrace) clearChildDirty_worldMap(key int) {
	if t.childDirty_worldMap == nil {
		return
	}
	delete(t.childDirty_worldMap, key)
}

func (t *WorldEntityTrace) childDirtyKeys_worldMap() []int {
	if len(t.childDirty_worldMap) == 0 {
		return nil
	}
	out := make([]int, 0, len(t.childDirty_worldMap))
	for key := range t.childDirty_worldMap {
		out = append(out, key)
	}
	sort.Slice(out, func(i, j int) bool { return fmt.Sprint(out[i]) < fmt.Sprint(out[j]) })
	return out
}

type WorldState struct {
	WorldId      WorldID
	CityByPlayer map[PlayerID]map[CityID]CityState
	WorldMap     map[int]CellState
	Armies       map[PlayerID]map[ArmyID]ArmyState
	Marches      map[PlayerID]map[ArmyID]MarchState
	CellToMarch  map[int][]MarchState
}

type WorldEntitySnap struct {
	Version           uint64
	State             WorldState
	DirtyFields       []Field
	Changes           map[Field]WorldEntityCollectionChange
	WorldMapDirtyKeys []int
}

type WorldEntity struct {
	worldId      WorldID
	cityByPlayer map[PlayerID]map[CityID]*CityEntity
	worldMap     map[int]*CellEntity
	armies       map[PlayerID]map[ArmyID]*ArmyEntity
	marches      map[PlayerID]map[ArmyID]*MarchEntity
	cellToMarch  map[int][]*MarchEntity
	_dt          WorldEntityTrace
}

func (e *WorldEntity) copyMapValueCityByPlayer(in map[CityID]CityState) map[CityID]CityState {
	var out map[CityID]CityState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[CityID]CityState, len(in))
		for k1, v2 := range in {
			out0[k1] = v2
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) hydrateMapValueCityByPlayer(in map[CityID]CityState) map[CityID]*CityEntity {
	var out map[CityID]*CityEntity
	if in == nil {
		out = nil
	} else {
		out0 := make(map[CityID]*CityEntity, len(in))
		for k1, v2 := range in {
			out0[k1] = HydrateCityEntity(v2)
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) snapshotMapValueCityByPlayer(in map[CityID]*CityEntity) map[CityID]CityState {
	var out map[CityID]CityState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[CityID]CityState, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				var z CityState
				out0[k1] = z
			} else {
				out0[k1] = v2.Save()
			}
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) copyMapCityByPlayer(in map[PlayerID]map[CityID]CityState) map[PlayerID]map[CityID]CityState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[CityID]CityState, len(in))
	for k, v := range in {
		out[k] = e.copyMapValueCityByPlayer(v)
	}
	return out
}

func (e *WorldEntity) mapsEqualCityByPlayer(a, b map[PlayerID]map[CityID]CityState) bool {
	return reflect.DeepEqual(a, b)
}

func (e *WorldEntity) hydrateMapCityByPlayer(in map[PlayerID]map[CityID]CityState) map[PlayerID]map[CityID]*CityEntity {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[CityID]*CityEntity, len(in))
	for k, v := range in {
		out[k] = e.hydrateMapValueCityByPlayer(v)
	}
	return out
}

func (e *WorldEntity) snapshotMapCityByPlayer(in map[PlayerID]map[CityID]*CityEntity) map[PlayerID]map[CityID]CityState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[CityID]CityState, len(in))
	for k, v := range in {
		var sv map[CityID]CityState
		sv = e.snapshotMapValueCityByPlayer(v)
		out[k] = sv
	}
	return out
}

func (e *WorldEntity) copyMapWorldMap(in map[int]CellState) map[int]CellState {
	if in == nil {
		return nil
	}
	out := make(map[int]CellState, len(in))
	for k, v := range in {
		out[k] = v
	}
	return out
}

func (e *WorldEntity) mapsEqualWorldMap(a, b map[int]CellState) bool {
	if a == nil && b == nil {
		return true
	}
	return false
}

func (e *WorldEntity) hydrateMapWorldMap(in map[int]CellState) map[int]*CellEntity {
	if in == nil {
		return nil
	}
	out := make(map[int]*CellEntity, len(in))
	for k, v := range in {
		out[k] = HydrateCellEntity(v)
	}
	return out
}

func (e *WorldEntity) snapshotMapWorldMap(in map[int]*CellEntity) map[int]CellState {
	if in == nil {
		return nil
	}
	out := make(map[int]CellState, len(in))
	for k, v := range in {
		if v == nil {
			var z CellState
			out[k] = z
			continue
		}
		out[k] = v.Save()
	}
	return out
}

func (e *WorldEntity) copyMapValueArmies(in map[ArmyID]ArmyState) map[ArmyID]ArmyState {
	var out map[ArmyID]ArmyState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[ArmyID]ArmyState, len(in))
		for k1, v2 := range in {
			out0[k1] = v2
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) hydrateMapValueArmies(in map[ArmyID]ArmyState) map[ArmyID]*ArmyEntity {
	var out map[ArmyID]*ArmyEntity
	if in == nil {
		out = nil
	} else {
		out0 := make(map[ArmyID]*ArmyEntity, len(in))
		for k1, v2 := range in {
			out0[k1] = HydrateArmyEntity(v2)
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) snapshotMapValueArmies(in map[ArmyID]*ArmyEntity) map[ArmyID]ArmyState {
	var out map[ArmyID]ArmyState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[ArmyID]ArmyState, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				var z ArmyState
				out0[k1] = z
			} else {
				out0[k1] = v2.Save()
			}
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) copyMapArmies(in map[PlayerID]map[ArmyID]ArmyState) map[PlayerID]map[ArmyID]ArmyState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[ArmyID]ArmyState, len(in))
	for k, v := range in {
		out[k] = e.copyMapValueArmies(v)
	}
	return out
}

func (e *WorldEntity) mapsEqualArmies(a, b map[PlayerID]map[ArmyID]ArmyState) bool {
	return reflect.DeepEqual(a, b)
}

func (e *WorldEntity) hydrateMapArmies(in map[PlayerID]map[ArmyID]ArmyState) map[PlayerID]map[ArmyID]*ArmyEntity {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[ArmyID]*ArmyEntity, len(in))
	for k, v := range in {
		out[k] = e.hydrateMapValueArmies(v)
	}
	return out
}

func (e *WorldEntity) snapshotMapArmies(in map[PlayerID]map[ArmyID]*ArmyEntity) map[PlayerID]map[ArmyID]ArmyState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[ArmyID]ArmyState, len(in))
	for k, v := range in {
		var sv map[ArmyID]ArmyState
		sv = e.snapshotMapValueArmies(v)
		out[k] = sv
	}
	return out
}

func (e *WorldEntity) copyMapValueMarches(in map[ArmyID]MarchState) map[ArmyID]MarchState {
	var out map[ArmyID]MarchState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[ArmyID]MarchState, len(in))
		for k1, v2 := range in {
			out0[k1] = v2
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) hydrateMapValueMarches(in map[ArmyID]MarchState) map[ArmyID]*MarchEntity {
	var out map[ArmyID]*MarchEntity
	if in == nil {
		out = nil
	} else {
		out0 := make(map[ArmyID]*MarchEntity, len(in))
		for k1, v2 := range in {
			out0[k1] = HydrateMarchEntity(v2)
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) snapshotMapValueMarches(in map[ArmyID]*MarchEntity) map[ArmyID]MarchState {
	var out map[ArmyID]MarchState
	if in == nil {
		out = nil
	} else {
		out0 := make(map[ArmyID]MarchState, len(in))
		for k1, v2 := range in {
			if v2 == nil {
				var z MarchState
				out0[k1] = z
			} else {
				out0[k1] = v2.Save()
			}
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) copyMapMarches(in map[PlayerID]map[ArmyID]MarchState) map[PlayerID]map[ArmyID]MarchState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[ArmyID]MarchState, len(in))
	for k, v := range in {
		out[k] = e.copyMapValueMarches(v)
	}
	return out
}

func (e *WorldEntity) mapsEqualMarches(a, b map[PlayerID]map[ArmyID]MarchState) bool {
	return reflect.DeepEqual(a, b)
}

func (e *WorldEntity) hydrateMapMarches(in map[PlayerID]map[ArmyID]MarchState) map[PlayerID]map[ArmyID]*MarchEntity {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[ArmyID]*MarchEntity, len(in))
	for k, v := range in {
		out[k] = e.hydrateMapValueMarches(v)
	}
	return out
}

func (e *WorldEntity) snapshotMapMarches(in map[PlayerID]map[ArmyID]*MarchEntity) map[PlayerID]map[ArmyID]MarchState {
	if in == nil {
		return nil
	}
	out := make(map[PlayerID]map[ArmyID]MarchState, len(in))
	for k, v := range in {
		var sv map[ArmyID]MarchState
		sv = e.snapshotMapValueMarches(v)
		out[k] = sv
	}
	return out
}

func (e *WorldEntity) copyMapValueCellToMarch(in []MarchState) []MarchState {
	var out []MarchState
	if in == nil {
		out = nil
	} else {
		out0 := make([]MarchState, len(in))
		for i1, v2 := range in {
			out0[i1] = v2
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) hydrateMapValueCellToMarch(in []MarchState) []*MarchEntity {
	var out []*MarchEntity
	if in == nil {
		out = nil
	} else {
		out0 := make([]*MarchEntity, len(in))
		for i1, v2 := range in {
			out0[i1] = HydrateMarchEntity(v2)
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) snapshotMapValueCellToMarch(in []*MarchEntity) []MarchState {
	var out []MarchState
	if in == nil {
		out = nil
	} else {
		out0 := make([]MarchState, len(in))
		for i1, v2 := range in {
			if v2 == nil {
				var z MarchState
				out0[i1] = z
			} else {
				out0[i1] = v2.Save()
			}
		}
		out = out0
	}
	return out
}

func (e *WorldEntity) copyMapCellToMarch(in map[int][]MarchState) map[int][]MarchState {
	if in == nil {
		return nil
	}
	out := make(map[int][]MarchState, len(in))
	for k, v := range in {
		out[k] = e.copyMapValueCellToMarch(v)
	}
	return out
}

func (e *WorldEntity) mapsEqualCellToMarch(a, b map[int][]MarchState) bool {
	return reflect.DeepEqual(a, b)
}

func (e *WorldEntity) hydrateMapCellToMarch(in map[int][]MarchState) map[int][]*MarchEntity {
	if in == nil {
		return nil
	}
	out := make(map[int][]*MarchEntity, len(in))
	for k, v := range in {
		out[k] = e.hydrateMapValueCellToMarch(v)
	}
	return out
}

func (e *WorldEntity) snapshotMapCellToMarch(in map[int][]*MarchEntity) map[int][]MarchState {
	if in == nil {
		return nil
	}
	out := make(map[int][]MarchState, len(in))
	for k, v := range in {
		var sv []MarchState
		sv = e.snapshotMapValueCellToMarch(v)
		out[k] = sv
	}
	return out
}

func HydrateWorldEntity(s WorldState) *WorldEntity {
	return &WorldEntity{
		worldId:      s.WorldId,
		cityByPlayer: emptyWorldEntity.hydrateMapCityByPlayer(s.CityByPlayer),
		worldMap:     emptyWorldEntity.hydrateMapWorldMap(s.WorldMap),
		armies:       emptyWorldEntity.hydrateMapArmies(s.Armies),
		marches:      emptyWorldEntity.hydrateMapMarches(s.Marches),
		cellToMarch:  emptyWorldEntity.hydrateMapCellToMarch(s.CellToMarch),
	}
}

func (e *WorldEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *WorldEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = WorldEntityTrace{}
}

func (e *WorldEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *WorldEntity) DirtyChanges() map[Field]WorldEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]WorldEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := WorldEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneWorldEntityCollectionChange(in WorldEntityCollectionChange) WorldEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *WorldEntity) Save() WorldState {
	var s WorldState
	if e == nil {
		return s
	}
	s.WorldId = e.worldId
	s.CityByPlayer = e.snapshotMapCityByPlayer(e.cityByPlayer)
	s.WorldMap = e.snapshotMapWorldMap(e.worldMap)
	s.Armies = e.snapshotMapArmies(e.armies)
	s.Marches = e.snapshotMapMarches(e.marches)
	s.CellToMarch = e.snapshotMapCellToMarch(e.cellToMarch)
	return s
}

func NewWorldEntitySnap(version uint64, e *WorldEntity) *WorldEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &WorldEntitySnap{
		Version:           version,
		State:             e.Save(),
		DirtyFields:       dirtyFields,
		Changes:           changes,
		WorldMapDirtyKeys: e._dt.childDirtyKeys_worldMap(),
	}
}

func (s *WorldEntitySnap) Clone() *WorldEntitySnap {
	if s == nil {
		return nil
	}
	out := &WorldEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]WorldEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneWorldEntityCollectionChange(ch)
		}
	}
	out.WorldMapDirtyKeys = append([]int(nil), s.WorldMapDirtyKeys...)
	out.State.CityByPlayer = emptyWorldEntity.copyMapCityByPlayer(s.State.CityByPlayer)
	out.State.WorldMap = emptyWorldEntity.copyMapWorldMap(s.State.WorldMap)
	out.State.Armies = emptyWorldEntity.copyMapArmies(s.State.Armies)
	out.State.Marches = emptyWorldEntity.copyMapMarches(s.State.Marches)
	out.State.CellToMarch = emptyWorldEntity.copyMapCellToMarch(s.State.CellToMarch)
	return out
}

func (e *WorldEntity) WorldId() WorldID {
	if e == nil {
		var z WorldID
		return z
	}
	return e.worldId
}

func (e *WorldEntity) SetWorldId(v WorldID) bool {
	if e == nil {
		return false
	}
	if e.worldId == v {
		return false
	}
	e.worldId = v
	e._dt.mark(FieldWorld_worldId)
	return true
}

func (e *WorldEntity) GetCityByPlayer(key PlayerID) (map[CityID]CityState, bool) {
	var z map[CityID]CityState
	if e == nil || e.cityByPlayer == nil {
		return z, false
	}
	v, ok := e.cityByPlayer[key]
	if !ok {
		return z, false
	}
	return e.snapshotMapValueCityByPlayer(v), true
}

func (e *WorldEntity) LenCityByPlayer() int {
	if e == nil || e.cityByPlayer == nil {
		return 0
	}
	return len(e.cityByPlayer)
}

func (e *WorldEntity) ForEachCityByPlayer(fn func(key PlayerID, value map[CityID]CityState)) {
	if e == nil || e.cityByPlayer == nil || fn == nil {
		return
	}
	for k, v := range e.cityByPlayer {
		fn(k, e.snapshotMapValueCityByPlayer(v))
	}
}

func (e *WorldEntity) RangeCityByPlayer(fn func(key PlayerID, value map[CityID]CityState) bool) {
	if e == nil || e.cityByPlayer == nil || fn == nil {
		return
	}
	for k, v := range e.cityByPlayer {
		if !fn(k, e.snapshotMapValueCityByPlayer(v)) {
			return
		}
	}
}

func (e *WorldEntity) ReplaceCityByPlayer(v map[PlayerID]map[CityID]CityState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualCityByPlayer(e.snapshotMapCityByPlayer(e.cityByPlayer), v) {
		return false
	}
	e.cityByPlayer = e.hydrateMapCityByPlayer(v)
	e._dt.markFullReplace(FieldWorld_cityByPlayer)
	return true
}

func (e *WorldEntity) PutCityByPlayer(key PlayerID, value map[CityID]CityState) bool {
	if e == nil {
		return false
	}
	if e.cityByPlayer == nil {
		e.cityByPlayer = make(map[PlayerID]map[CityID]*CityEntity)
	}
	if old, ok := e.cityByPlayer[key]; ok && reflect.DeepEqual(e.snapshotMapValueCityByPlayer(old), value) {
		return false
	}
	e.cityByPlayer[key] = e.hydrateMapValueCityByPlayer(value)
	e._dt.markMapSet(FieldWorld_cityByPlayer, fmt.Sprint(key), e.copyMapValueCityByPlayer(value))
	return true
}

func (e *WorldEntity) PutCityByPlayerMany(entries map[PlayerID]map[CityID]CityState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.cityByPlayer == nil {
		e.cityByPlayer = make(map[PlayerID]map[CityID]*CityEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		if old, ok := e.cityByPlayer[k]; ok && reflect.DeepEqual(e.snapshotMapValueCityByPlayer(old), v) {
			continue
		}
		e.cityByPlayer[k] = e.hydrateMapValueCityByPlayer(v)
		e._dt.markMapSet(FieldWorld_cityByPlayer, fmt.Sprint(k), e.copyMapValueCityByPlayer(v))
		changed = true
	}
	return changed
}

func (e *WorldEntity) UpdateCityByPlayer(key PlayerID, fn func(value map[CityID]*CityEntity)) bool {
	if e == nil || fn == nil || e.cityByPlayer == nil {
		return false
	}
	v, ok := e.cityByPlayer[key]
	if !ok {
		return false
	}
	before := e.snapshotMapValueCityByPlayer(v)
	fn(v)
	after := e.snapshotMapValueCityByPlayer(v)
	if reflect.DeepEqual(before, after) {
		return false
	}
	e._dt.markMapSet(FieldWorld_cityByPlayer, fmt.Sprint(key), e.copyMapValueCityByPlayer(after))
	return true
}

func (e *WorldEntity) DelCityByPlayer(key PlayerID) bool {
	if e == nil || e.cityByPlayer == nil {
		return false
	}
	if _, ok := e.cityByPlayer[key]; !ok {
		return false
	}
	delete(e.cityByPlayer, key)
	e._dt.markMapDelete(FieldWorld_cityByPlayer, fmt.Sprint(key))
	return true
}

func (e *WorldEntity) DelCityByPlayerMany(keys []PlayerID) bool {
	if e == nil || e.cityByPlayer == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.cityByPlayer[key]; !ok {
			continue
		}
		delete(e.cityByPlayer, key)
		e._dt.markMapDelete(FieldWorld_cityByPlayer, fmt.Sprint(key))
		changed = true
	}
	return changed
}

func (e *WorldEntity) ClearCityByPlayer() bool {
	if e == nil {
		return false
	}
	if len(e.cityByPlayer) == 0 {
		return false
	}
	e.cityByPlayer = nil
	e._dt.markFullReplace(FieldWorld_cityByPlayer)
	return true
}

func (e *WorldEntity) GetWorldMap(key int) (CellState, bool) {
	var z CellState
	if e == nil || e.worldMap == nil {
		return z, false
	}
	v, ok := e.worldMap[key]
	if !ok || v == nil {
		return z, false
	}
	return v.Save(), true
}

func (e *WorldEntity) LenWorldMap() int {
	if e == nil || e.worldMap == nil {
		return 0
	}
	return len(e.worldMap)
}

func (e *WorldEntity) ForEachWorldMap(fn func(key int, value CellState)) {
	if e == nil || e.worldMap == nil || fn == nil {
		return
	}
	for k, v := range e.worldMap {
		if v == nil {
			continue
		}
		fn(k, v.Save())
	}
}

func (e *WorldEntity) RangeWorldMap(fn func(key int, value CellState) bool) {
	if e == nil || e.worldMap == nil || fn == nil {
		return
	}
	for k, v := range e.worldMap {
		if v == nil {
			continue
		}
		if !fn(k, v.Save()) {
			return
		}
	}
}

func (e *WorldEntity) DirtyWorldMapKeys() []int {
	if e == nil {
		return nil
	}
	return e._dt.childDirtyKeys_worldMap()
}

func (e *WorldEntity) ReplaceWorldMap(v map[int]CellState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualWorldMap(e.snapshotMapWorldMap(e.worldMap), v) {
		return false
	}
	e.worldMap = e.hydrateMapWorldMap(v)
	e._dt.markFullReplace(FieldWorld_worldMap)
	return true
}

func (e *WorldEntity) PutWorldMap(key int, value CellState) bool {
	if e == nil {
		return false
	}
	if e.worldMap == nil {
		e.worldMap = make(map[int]*CellEntity)
	}
	e.worldMap[key] = HydrateCellEntity(value)
	e._dt.markMapSet(FieldWorld_worldMap, fmt.Sprint(key), value)
	e._dt.markChildDirty_worldMap(FieldWorld_worldMap, key)
	return true
}

func (e *WorldEntity) PutWorldMapMany(entries map[int]CellState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.worldMap == nil {
		e.worldMap = make(map[int]*CellEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		e.worldMap[k] = HydrateCellEntity(v)
		e._dt.markMapSet(FieldWorld_worldMap, fmt.Sprint(k), v)
		e._dt.markChildDirty_worldMap(FieldWorld_worldMap, k)
		changed = true
	}
	return changed
}

func (e *WorldEntity) UpdateWorldMap(key int, fn func(value *CellEntity)) bool {
	if e == nil || fn == nil || e.worldMap == nil {
		return false
	}
	v, ok := e.worldMap[key]
	if !ok || v == nil {
		return false
	}
	fn(v)
	e._dt.markChildDirty_worldMap(FieldWorld_worldMap, key)
	return true
}

func (e *WorldEntity) DelWorldMap(key int) bool {
	if e == nil || e.worldMap == nil {
		return false
	}
	if _, ok := e.worldMap[key]; !ok {
		return false
	}
	delete(e.worldMap, key)
	e._dt.markMapDelete(FieldWorld_worldMap, fmt.Sprint(key))
	e._dt.clearChildDirty_worldMap(key)
	return true
}

func (e *WorldEntity) DelWorldMapMany(keys []int) bool {
	if e == nil || e.worldMap == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.worldMap[key]; !ok {
			continue
		}
		delete(e.worldMap, key)
		e._dt.markMapDelete(FieldWorld_worldMap, fmt.Sprint(key))
		e._dt.clearChildDirty_worldMap(key)
		changed = true
	}
	return changed
}

func (e *WorldEntity) ClearWorldMap() bool {
	if e == nil {
		return false
	}
	if len(e.worldMap) == 0 {
		return false
	}
	e.worldMap = nil
	e._dt.markFullReplace(FieldWorld_worldMap)
	e._dt.childDirty_worldMap = nil
	return true
}

func (e *WorldEntity) GetArmies(key PlayerID) (map[ArmyID]ArmyState, bool) {
	var z map[ArmyID]ArmyState
	if e == nil || e.armies == nil {
		return z, false
	}
	v, ok := e.armies[key]
	if !ok {
		return z, false
	}
	return e.snapshotMapValueArmies(v), true
}

func (e *WorldEntity) LenArmies() int {
	if e == nil || e.armies == nil {
		return 0
	}
	return len(e.armies)
}

func (e *WorldEntity) ForEachArmies(fn func(key PlayerID, value map[ArmyID]ArmyState)) {
	if e == nil || e.armies == nil || fn == nil {
		return
	}
	for k, v := range e.armies {
		fn(k, e.snapshotMapValueArmies(v))
	}
}

func (e *WorldEntity) RangeArmies(fn func(key PlayerID, value map[ArmyID]ArmyState) bool) {
	if e == nil || e.armies == nil || fn == nil {
		return
	}
	for k, v := range e.armies {
		if !fn(k, e.snapshotMapValueArmies(v)) {
			return
		}
	}
}

func (e *WorldEntity) ReplaceArmies(v map[PlayerID]map[ArmyID]ArmyState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualArmies(e.snapshotMapArmies(e.armies), v) {
		return false
	}
	e.armies = e.hydrateMapArmies(v)
	e._dt.markFullReplace(FieldWorld_armies)
	return true
}

func (e *WorldEntity) PutArmies(key PlayerID, value map[ArmyID]ArmyState) bool {
	if e == nil {
		return false
	}
	if e.armies == nil {
		e.armies = make(map[PlayerID]map[ArmyID]*ArmyEntity)
	}
	if old, ok := e.armies[key]; ok && reflect.DeepEqual(e.snapshotMapValueArmies(old), value) {
		return false
	}
	e.armies[key] = e.hydrateMapValueArmies(value)
	e._dt.markMapSet(FieldWorld_armies, fmt.Sprint(key), e.copyMapValueArmies(value))
	return true
}

func (e *WorldEntity) PutArmiesMany(entries map[PlayerID]map[ArmyID]ArmyState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.armies == nil {
		e.armies = make(map[PlayerID]map[ArmyID]*ArmyEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		if old, ok := e.armies[k]; ok && reflect.DeepEqual(e.snapshotMapValueArmies(old), v) {
			continue
		}
		e.armies[k] = e.hydrateMapValueArmies(v)
		e._dt.markMapSet(FieldWorld_armies, fmt.Sprint(k), e.copyMapValueArmies(v))
		changed = true
	}
	return changed
}

func (e *WorldEntity) UpdateArmies(key PlayerID, fn func(value map[ArmyID]*ArmyEntity)) bool {
	if e == nil || fn == nil || e.armies == nil {
		return false
	}
	v, ok := e.armies[key]
	if !ok {
		return false
	}
	before := e.snapshotMapValueArmies(v)
	fn(v)
	after := e.snapshotMapValueArmies(v)
	if reflect.DeepEqual(before, after) {
		return false
	}
	e._dt.markMapSet(FieldWorld_armies, fmt.Sprint(key), e.copyMapValueArmies(after))
	return true
}

func (e *WorldEntity) DelArmies(key PlayerID) bool {
	if e == nil || e.armies == nil {
		return false
	}
	if _, ok := e.armies[key]; !ok {
		return false
	}
	delete(e.armies, key)
	e._dt.markMapDelete(FieldWorld_armies, fmt.Sprint(key))
	return true
}

func (e *WorldEntity) DelArmiesMany(keys []PlayerID) bool {
	if e == nil || e.armies == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.armies[key]; !ok {
			continue
		}
		delete(e.armies, key)
		e._dt.markMapDelete(FieldWorld_armies, fmt.Sprint(key))
		changed = true
	}
	return changed
}

func (e *WorldEntity) ClearArmies() bool {
	if e == nil {
		return false
	}
	if len(e.armies) == 0 {
		return false
	}
	e.armies = nil
	e._dt.markFullReplace(FieldWorld_armies)
	return true
}

func (e *WorldEntity) GetMarches(key PlayerID) (map[ArmyID]MarchState, bool) {
	var z map[ArmyID]MarchState
	if e == nil || e.marches == nil {
		return z, false
	}
	v, ok := e.marches[key]
	if !ok {
		return z, false
	}
	return e.snapshotMapValueMarches(v), true
}

func (e *WorldEntity) LenMarches() int {
	if e == nil || e.marches == nil {
		return 0
	}
	return len(e.marches)
}

func (e *WorldEntity) ForEachMarches(fn func(key PlayerID, value map[ArmyID]MarchState)) {
	if e == nil || e.marches == nil || fn == nil {
		return
	}
	for k, v := range e.marches {
		fn(k, e.snapshotMapValueMarches(v))
	}
}

func (e *WorldEntity) RangeMarches(fn func(key PlayerID, value map[ArmyID]MarchState) bool) {
	if e == nil || e.marches == nil || fn == nil {
		return
	}
	for k, v := range e.marches {
		if !fn(k, e.snapshotMapValueMarches(v)) {
			return
		}
	}
}

func (e *WorldEntity) ReplaceMarches(v map[PlayerID]map[ArmyID]MarchState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualMarches(e.snapshotMapMarches(e.marches), v) {
		return false
	}
	e.marches = e.hydrateMapMarches(v)
	e._dt.markFullReplace(FieldWorld_marches)
	return true
}

func (e *WorldEntity) PutMarches(key PlayerID, value map[ArmyID]MarchState) bool {
	if e == nil {
		return false
	}
	if e.marches == nil {
		e.marches = make(map[PlayerID]map[ArmyID]*MarchEntity)
	}
	if old, ok := e.marches[key]; ok && reflect.DeepEqual(e.snapshotMapValueMarches(old), value) {
		return false
	}
	e.marches[key] = e.hydrateMapValueMarches(value)
	e._dt.markMapSet(FieldWorld_marches, fmt.Sprint(key), e.copyMapValueMarches(value))
	return true
}

func (e *WorldEntity) PutMarchesMany(entries map[PlayerID]map[ArmyID]MarchState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.marches == nil {
		e.marches = make(map[PlayerID]map[ArmyID]*MarchEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		if old, ok := e.marches[k]; ok && reflect.DeepEqual(e.snapshotMapValueMarches(old), v) {
			continue
		}
		e.marches[k] = e.hydrateMapValueMarches(v)
		e._dt.markMapSet(FieldWorld_marches, fmt.Sprint(k), e.copyMapValueMarches(v))
		changed = true
	}
	return changed
}

func (e *WorldEntity) UpdateMarches(key PlayerID, fn func(value map[ArmyID]*MarchEntity)) bool {
	if e == nil || fn == nil || e.marches == nil {
		return false
	}
	v, ok := e.marches[key]
	if !ok {
		return false
	}
	before := e.snapshotMapValueMarches(v)
	fn(v)
	after := e.snapshotMapValueMarches(v)
	if reflect.DeepEqual(before, after) {
		return false
	}
	e._dt.markMapSet(FieldWorld_marches, fmt.Sprint(key), e.copyMapValueMarches(after))
	return true
}

func (e *WorldEntity) DelMarches(key PlayerID) bool {
	if e == nil || e.marches == nil {
		return false
	}
	if _, ok := e.marches[key]; !ok {
		return false
	}
	delete(e.marches, key)
	e._dt.markMapDelete(FieldWorld_marches, fmt.Sprint(key))
	return true
}

func (e *WorldEntity) DelMarchesMany(keys []PlayerID) bool {
	if e == nil || e.marches == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.marches[key]; !ok {
			continue
		}
		delete(e.marches, key)
		e._dt.markMapDelete(FieldWorld_marches, fmt.Sprint(key))
		changed = true
	}
	return changed
}

func (e *WorldEntity) ClearMarches() bool {
	if e == nil {
		return false
	}
	if len(e.marches) == 0 {
		return false
	}
	e.marches = nil
	e._dt.markFullReplace(FieldWorld_marches)
	return true
}

func (e *WorldEntity) GetCellToMarch(key int) ([]MarchState, bool) {
	var z []MarchState
	if e == nil || e.cellToMarch == nil {
		return z, false
	}
	v, ok := e.cellToMarch[key]
	if !ok {
		return z, false
	}
	return e.snapshotMapValueCellToMarch(v), true
}

func (e *WorldEntity) LenCellToMarch() int {
	if e == nil || e.cellToMarch == nil {
		return 0
	}
	return len(e.cellToMarch)
}

func (e *WorldEntity) ForEachCellToMarch(fn func(key int, value []MarchState)) {
	if e == nil || e.cellToMarch == nil || fn == nil {
		return
	}
	for k, v := range e.cellToMarch {
		fn(k, e.snapshotMapValueCellToMarch(v))
	}
}

func (e *WorldEntity) RangeCellToMarch(fn func(key int, value []MarchState) bool) {
	if e == nil || e.cellToMarch == nil || fn == nil {
		return
	}
	for k, v := range e.cellToMarch {
		if !fn(k, e.snapshotMapValueCellToMarch(v)) {
			return
		}
	}
}

func (e *WorldEntity) ReplaceCellToMarch(v map[int][]MarchState) bool {
	if e == nil {
		return false
	}
	if e.mapsEqualCellToMarch(e.snapshotMapCellToMarch(e.cellToMarch), v) {
		return false
	}
	e.cellToMarch = e.hydrateMapCellToMarch(v)
	e._dt.markFullReplace(FieldWorld_cellToMarch)
	return true
}

func (e *WorldEntity) PutCellToMarch(key int, value []MarchState) bool {
	if e == nil {
		return false
	}
	if e.cellToMarch == nil {
		e.cellToMarch = make(map[int][]*MarchEntity)
	}
	if old, ok := e.cellToMarch[key]; ok && reflect.DeepEqual(e.snapshotMapValueCellToMarch(old), value) {
		return false
	}
	e.cellToMarch[key] = e.hydrateMapValueCellToMarch(value)
	e._dt.markMapSet(FieldWorld_cellToMarch, fmt.Sprint(key), e.copyMapValueCellToMarch(value))
	return true
}

func (e *WorldEntity) PutCellToMarchMany(entries map[int][]MarchState) bool {
	if e == nil || len(entries) == 0 {
		return false
	}
	if e.cellToMarch == nil {
		e.cellToMarch = make(map[int][]*MarchEntity, len(entries))
	}
	changed := false
	for k, v := range entries {
		if old, ok := e.cellToMarch[k]; ok && reflect.DeepEqual(e.snapshotMapValueCellToMarch(old), v) {
			continue
		}
		e.cellToMarch[k] = e.hydrateMapValueCellToMarch(v)
		e._dt.markMapSet(FieldWorld_cellToMarch, fmt.Sprint(k), e.copyMapValueCellToMarch(v))
		changed = true
	}
	return changed
}

func (e *WorldEntity) UpdateCellToMarch(key int, fn func(value []*MarchEntity)) bool {
	if e == nil || fn == nil || e.cellToMarch == nil {
		return false
	}
	v, ok := e.cellToMarch[key]
	if !ok {
		return false
	}
	before := e.snapshotMapValueCellToMarch(v)
	fn(v)
	after := e.snapshotMapValueCellToMarch(v)
	if reflect.DeepEqual(before, after) {
		return false
	}
	e._dt.markMapSet(FieldWorld_cellToMarch, fmt.Sprint(key), e.copyMapValueCellToMarch(after))
	return true
}

func (e *WorldEntity) DelCellToMarch(key int) bool {
	if e == nil || e.cellToMarch == nil {
		return false
	}
	if _, ok := e.cellToMarch[key]; !ok {
		return false
	}
	delete(e.cellToMarch, key)
	e._dt.markMapDelete(FieldWorld_cellToMarch, fmt.Sprint(key))
	return true
}

func (e *WorldEntity) DelCellToMarchMany(keys []int) bool {
	if e == nil || e.cellToMarch == nil || len(keys) == 0 {
		return false
	}
	changed := false
	for _, key := range keys {
		if _, ok := e.cellToMarch[key]; !ok {
			continue
		}
		delete(e.cellToMarch, key)
		e._dt.markMapDelete(FieldWorld_cellToMarch, fmt.Sprint(key))
		changed = true
	}
	return changed
}

func (e *WorldEntity) ClearCellToMarch() bool {
	if e == nil {
		return false
	}
	if len(e.cellToMarch) == 0 {
		return false
	}
	e.cellToMarch = nil
	e._dt.markFullReplace(FieldWorld_cellToMarch)
	return true
}
