// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
	"time"
)

const (
	FieldArmy_id                Field = "id"
	FieldArmy_cityId            Field = "cityId"
	FieldArmy_playerId          Field = "playerId"
	FieldArmy_allianceId        Field = "allianceId"
	FieldArmy_order             Field = "order"
	FieldArmy_generals          Field = "generals"
	FieldArmy_soldiers          Field = "soldiers"
	FieldArmy_cmd               Field = "cmd"
	FieldArmy_fromX             Field = "fromX"
	FieldArmy_fromY             Field = "fromY"
	FieldArmy_toX               Field = "toX"
	FieldArmy_toY               Field = "toY"
	FieldArmy_startTime         Field = "startTime"
	FieldArmy_endTime           Field = "endTime"
	FieldArmy_state             Field = "state"
	FieldArmy_frozen            Field = "frozen"
	FieldArmy_conscriptEndTimes Field = "conscriptEndTimes"
	FieldArmy_conscriptCounts   Field = "conscriptCounts"
	FieldArmy_cellX             Field = "cellX"
	FieldArmy_cellY             Field = "cellY"
)

var emptyArmyEntity = &ArmyEntity{}

type ArmyEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type ArmyEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type ArmyEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*ArmyEntityCollectionChangeInner
}

func (t *ArmyEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *ArmyEntityTrace) ensureChange(f Field) *ArmyEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*ArmyEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &ArmyEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *ArmyEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *ArmyEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *ArmyEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *ArmyEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *ArmyEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *ArmyEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *ArmyEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type ArmyState struct {
	Id                int
	CityId            CityID
	PlayerId          PlayerID
	AllianceId        AllianceID
	Order             int8
	Generals          []int
	Soldiers          []int
	Cmd               int8
	FromX             int
	FromY             int
	ToX               int
	ToY               int
	StartTime         time.Time
	EndTime           time.Time
	State             int8
	Frozen            bool
	ConscriptEndTimes []int64
	ConscriptCounts   []int
	CellX             int
	CellY             int
}

type ArmyEntitySnap struct {
	Version     uint64
	State       ArmyState
	DirtyFields []Field
	Changes     map[Field]ArmyEntityCollectionChange
}

type ArmyEntity struct {
	id                int
	cityId            CityID
	playerId          PlayerID
	allianceId        AllianceID
	order             int8
	generals          []int
	soldiers          []int
	cmd               int8
	fromX             int
	fromY             int
	toX               int
	toY               int
	startTime         time.Time
	endTime           time.Time
	state             int8
	frozen            bool
	conscriptEndTimes []int64
	conscriptCounts   []int
	cellX             int
	cellY             int
	_dt               ArmyEntityTrace
}

func (e *ArmyEntity) slicesEqualGenerals(a, b []int) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func (e *ArmyEntity) slicesEqualSoldiers(a, b []int) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func (e *ArmyEntity) slicesEqualConscriptEndTimes(a, b []int64) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func (e *ArmyEntity) slicesEqualConscriptCounts(a, b []int) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func HydrateArmyEntity(s ArmyState) *ArmyEntity {
	return &ArmyEntity{
		id:                s.Id,
		cityId:            s.CityId,
		playerId:          s.PlayerId,
		allianceId:        s.AllianceId,
		order:             s.Order,
		generals:          append([]int(nil), s.Generals...),
		soldiers:          append([]int(nil), s.Soldiers...),
		cmd:               s.Cmd,
		fromX:             s.FromX,
		fromY:             s.FromY,
		toX:               s.ToX,
		toY:               s.ToY,
		startTime:         s.StartTime,
		endTime:           s.EndTime,
		state:             s.State,
		frozen:            s.Frozen,
		conscriptEndTimes: append([]int64(nil), s.ConscriptEndTimes...),
		conscriptCounts:   append([]int(nil), s.ConscriptCounts...),
		cellX:             s.CellX,
		cellY:             s.CellY,
	}
}

func (e *ArmyEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *ArmyEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = ArmyEntityTrace{}
}

func (e *ArmyEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *ArmyEntity) DirtyChanges() map[Field]ArmyEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]ArmyEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := ArmyEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneArmyEntityCollectionChange(in ArmyEntityCollectionChange) ArmyEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *ArmyEntity) Save() ArmyState {
	var s ArmyState
	if e == nil {
		return s
	}
	s.Id = e.id
	s.CityId = e.cityId
	s.PlayerId = e.playerId
	s.AllianceId = e.allianceId
	s.Order = e.order
	s.Generals = append([]int(nil), e.generals...)
	s.Soldiers = append([]int(nil), e.soldiers...)
	s.Cmd = e.cmd
	s.FromX = e.fromX
	s.FromY = e.fromY
	s.ToX = e.toX
	s.ToY = e.toY
	s.StartTime = e.startTime
	s.EndTime = e.endTime
	s.State = e.state
	s.Frozen = e.frozen
	s.ConscriptEndTimes = append([]int64(nil), e.conscriptEndTimes...)
	s.ConscriptCounts = append([]int(nil), e.conscriptCounts...)
	s.CellX = e.cellX
	s.CellY = e.cellY
	return s
}

func NewArmyEntitySnap(version uint64, e *ArmyEntity) *ArmyEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &ArmyEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *ArmyEntitySnap) Clone() *ArmyEntitySnap {
	if s == nil {
		return nil
	}
	out := &ArmyEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]ArmyEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneArmyEntityCollectionChange(ch)
		}
	}
	out.State.Generals = append([]int(nil), s.State.Generals...)
	out.State.Soldiers = append([]int(nil), s.State.Soldiers...)
	out.State.ConscriptEndTimes = append([]int64(nil), s.State.ConscriptEndTimes...)
	out.State.ConscriptCounts = append([]int(nil), s.State.ConscriptCounts...)
	return out
}

func (e *ArmyEntity) Id() int {
	if e == nil {
		var z int
		return z
	}
	return e.id
}

func (e *ArmyEntity) SetId(v int) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldArmy_id)
	return true
}

func (e *ArmyEntity) CityId() CityID {
	if e == nil {
		var z CityID
		return z
	}
	return e.cityId
}

func (e *ArmyEntity) SetCityId(v CityID) bool {
	if e == nil {
		return false
	}
	if e.cityId == v {
		return false
	}
	e.cityId = v
	e._dt.mark(FieldArmy_cityId)
	return true
}

func (e *ArmyEntity) PlayerId() PlayerID {
	if e == nil {
		var z PlayerID
		return z
	}
	return e.playerId
}

func (e *ArmyEntity) SetPlayerId(v PlayerID) bool {
	if e == nil {
		return false
	}
	if e.playerId == v {
		return false
	}
	e.playerId = v
	e._dt.mark(FieldArmy_playerId)
	return true
}

func (e *ArmyEntity) AllianceId() AllianceID {
	if e == nil {
		var z AllianceID
		return z
	}
	return e.allianceId
}

func (e *ArmyEntity) SetAllianceId(v AllianceID) bool {
	if e == nil {
		return false
	}
	if e.allianceId == v {
		return false
	}
	e.allianceId = v
	e._dt.mark(FieldArmy_allianceId)
	return true
}

func (e *ArmyEntity) Order() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.order
}

func (e *ArmyEntity) SetOrder(v int8) bool {
	if e == nil {
		return false
	}
	if e.order == v {
		return false
	}
	e.order = v
	e._dt.mark(FieldArmy_order)
	return true
}

func (e *ArmyEntity) LenGenerals() int {
	if e == nil {
		return 0
	}
	return len(e.generals)
}

func (e *ArmyEntity) AtGenerals(index int) (int, bool) {
	var z int
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.generals) {
		return z, false
	}
	return e.generals[index], true
}

func (e *ArmyEntity) ForEachGenerals(fn func(index int, value int)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.generals {
		fn(i, v)
	}
}

func (e *ArmyEntity) RangeGenerals(fn func(index int, value int) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.generals {
		if !fn(i, v) {
			return
		}
	}
}

func (e *ArmyEntity) ReplaceGenerals(v []int) bool {
	if e == nil {
		return false
	}
	if e.slicesEqualGenerals(e.generals, v) {
		return false
	}
	e.generals = append([]int(nil), v...)
	e._dt.markFullReplace(FieldArmy_generals)
	return true
}

func (e *ArmyEntity) AppendGenerals(values ...int) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	e.generals = append(e.generals, values...)
	for _, v := range values {
		e._dt.markSliceAppend(FieldArmy_generals, v)
	}
	return true
}

func (e *ArmyEntity) SetGeneralsAt(index int, value int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.generals) {
		return false
	}
	if e.generals[index] == value {
		return false
	}
	e.generals[index] = value
	e._dt.markSliceSet(FieldArmy_generals, index, value)
	return true
}

func (e *ArmyEntity) RemoveGeneralsAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.generals) {
		return false
	}
	e.generals = append(e.generals[:index], e.generals[index+1:]...)
	e._dt.markSliceRemoveAt(FieldArmy_generals, index)
	return true
}

func (e *ArmyEntity) SwapRemoveGeneralsAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.generals) {
		return false
	}
	last := len(e.generals) - 1
	if index != last {
		e.generals[index] = e.generals[last]
	}
	e.generals = e.generals[:last]
	e._dt.markSliceSwapRemoveAt(FieldArmy_generals, index)
	return true
}

func (e *ArmyEntity) ClearGenerals() bool {
	if e == nil {
		return false
	}
	if len(e.generals) == 0 {
		return false
	}
	e.generals = nil
	e._dt.markFullReplace(FieldArmy_generals)
	return true
}

func (e *ArmyEntity) LenSoldiers() int {
	if e == nil {
		return 0
	}
	return len(e.soldiers)
}

func (e *ArmyEntity) AtSoldiers(index int) (int, bool) {
	var z int
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.soldiers) {
		return z, false
	}
	return e.soldiers[index], true
}

func (e *ArmyEntity) ForEachSoldiers(fn func(index int, value int)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.soldiers {
		fn(i, v)
	}
}

func (e *ArmyEntity) RangeSoldiers(fn func(index int, value int) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.soldiers {
		if !fn(i, v) {
			return
		}
	}
}

func (e *ArmyEntity) ReplaceSoldiers(v []int) bool {
	if e == nil {
		return false
	}
	if e.slicesEqualSoldiers(e.soldiers, v) {
		return false
	}
	e.soldiers = append([]int(nil), v...)
	e._dt.markFullReplace(FieldArmy_soldiers)
	return true
}

func (e *ArmyEntity) AppendSoldiers(values ...int) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	e.soldiers = append(e.soldiers, values...)
	for _, v := range values {
		e._dt.markSliceAppend(FieldArmy_soldiers, v)
	}
	return true
}

func (e *ArmyEntity) SetSoldiersAt(index int, value int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.soldiers) {
		return false
	}
	if e.soldiers[index] == value {
		return false
	}
	e.soldiers[index] = value
	e._dt.markSliceSet(FieldArmy_soldiers, index, value)
	return true
}

func (e *ArmyEntity) RemoveSoldiersAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.soldiers) {
		return false
	}
	e.soldiers = append(e.soldiers[:index], e.soldiers[index+1:]...)
	e._dt.markSliceRemoveAt(FieldArmy_soldiers, index)
	return true
}

func (e *ArmyEntity) SwapRemoveSoldiersAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.soldiers) {
		return false
	}
	last := len(e.soldiers) - 1
	if index != last {
		e.soldiers[index] = e.soldiers[last]
	}
	e.soldiers = e.soldiers[:last]
	e._dt.markSliceSwapRemoveAt(FieldArmy_soldiers, index)
	return true
}

func (e *ArmyEntity) ClearSoldiers() bool {
	if e == nil {
		return false
	}
	if len(e.soldiers) == 0 {
		return false
	}
	e.soldiers = nil
	e._dt.markFullReplace(FieldArmy_soldiers)
	return true
}

func (e *ArmyEntity) Cmd() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.cmd
}

func (e *ArmyEntity) SetCmd(v int8) bool {
	if e == nil {
		return false
	}
	if e.cmd == v {
		return false
	}
	e.cmd = v
	e._dt.mark(FieldArmy_cmd)
	return true
}

func (e *ArmyEntity) FromX() int {
	if e == nil {
		var z int
		return z
	}
	return e.fromX
}

func (e *ArmyEntity) SetFromX(v int) bool {
	if e == nil {
		return false
	}
	if e.fromX == v {
		return false
	}
	e.fromX = v
	e._dt.mark(FieldArmy_fromX)
	return true
}

func (e *ArmyEntity) FromY() int {
	if e == nil {
		var z int
		return z
	}
	return e.fromY
}

func (e *ArmyEntity) SetFromY(v int) bool {
	if e == nil {
		return false
	}
	if e.fromY == v {
		return false
	}
	e.fromY = v
	e._dt.mark(FieldArmy_fromY)
	return true
}

func (e *ArmyEntity) ToX() int {
	if e == nil {
		var z int
		return z
	}
	return e.toX
}

func (e *ArmyEntity) SetToX(v int) bool {
	if e == nil {
		return false
	}
	if e.toX == v {
		return false
	}
	e.toX = v
	e._dt.mark(FieldArmy_toX)
	return true
}

func (e *ArmyEntity) ToY() int {
	if e == nil {
		var z int
		return z
	}
	return e.toY
}

func (e *ArmyEntity) SetToY(v int) bool {
	if e == nil {
		return false
	}
	if e.toY == v {
		return false
	}
	e.toY = v
	e._dt.mark(FieldArmy_toY)
	return true
}

func (e *ArmyEntity) StartTime() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.startTime
}

func (e *ArmyEntity) SetStartTime(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.startTime.Equal(v) {
		return false
	}
	e.startTime = v
	e._dt.mark(FieldArmy_startTime)
	return true
}

func (e *ArmyEntity) EndTime() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.endTime
}

func (e *ArmyEntity) SetEndTime(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.endTime.Equal(v) {
		return false
	}
	e.endTime = v
	e._dt.mark(FieldArmy_endTime)
	return true
}

func (e *ArmyEntity) State() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.state
}

func (e *ArmyEntity) SetState(v int8) bool {
	if e == nil {
		return false
	}
	if e.state == v {
		return false
	}
	e.state = v
	e._dt.mark(FieldArmy_state)
	return true
}

func (e *ArmyEntity) Frozen() bool {
	if e == nil {
		var z bool
		return z
	}
	return e.frozen
}

func (e *ArmyEntity) SetFrozen(v bool) bool {
	if e == nil {
		return false
	}
	if e.frozen == v {
		return false
	}
	e.frozen = v
	e._dt.mark(FieldArmy_frozen)
	return true
}

func (e *ArmyEntity) LenConscriptEndTimes() int {
	if e == nil {
		return 0
	}
	return len(e.conscriptEndTimes)
}

func (e *ArmyEntity) AtConscriptEndTimes(index int) (int64, bool) {
	var z int64
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.conscriptEndTimes) {
		return z, false
	}
	return e.conscriptEndTimes[index], true
}

func (e *ArmyEntity) ForEachConscriptEndTimes(fn func(index int, value int64)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.conscriptEndTimes {
		fn(i, v)
	}
}

func (e *ArmyEntity) RangeConscriptEndTimes(fn func(index int, value int64) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.conscriptEndTimes {
		if !fn(i, v) {
			return
		}
	}
}

func (e *ArmyEntity) ReplaceConscriptEndTimes(v []int64) bool {
	if e == nil {
		return false
	}
	if e.slicesEqualConscriptEndTimes(e.conscriptEndTimes, v) {
		return false
	}
	e.conscriptEndTimes = append([]int64(nil), v...)
	e._dt.markFullReplace(FieldArmy_conscriptEndTimes)
	return true
}

func (e *ArmyEntity) AppendConscriptEndTimes(values ...int64) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	e.conscriptEndTimes = append(e.conscriptEndTimes, values...)
	for _, v := range values {
		e._dt.markSliceAppend(FieldArmy_conscriptEndTimes, v)
	}
	return true
}

func (e *ArmyEntity) SetConscriptEndTimesAt(index int, value int64) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.conscriptEndTimes) {
		return false
	}
	if e.conscriptEndTimes[index] == value {
		return false
	}
	e.conscriptEndTimes[index] = value
	e._dt.markSliceSet(FieldArmy_conscriptEndTimes, index, value)
	return true
}

func (e *ArmyEntity) RemoveConscriptEndTimesAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.conscriptEndTimes) {
		return false
	}
	e.conscriptEndTimes = append(e.conscriptEndTimes[:index], e.conscriptEndTimes[index+1:]...)
	e._dt.markSliceRemoveAt(FieldArmy_conscriptEndTimes, index)
	return true
}

func (e *ArmyEntity) SwapRemoveConscriptEndTimesAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.conscriptEndTimes) {
		return false
	}
	last := len(e.conscriptEndTimes) - 1
	if index != last {
		e.conscriptEndTimes[index] = e.conscriptEndTimes[last]
	}
	e.conscriptEndTimes = e.conscriptEndTimes[:last]
	e._dt.markSliceSwapRemoveAt(FieldArmy_conscriptEndTimes, index)
	return true
}

func (e *ArmyEntity) ClearConscriptEndTimes() bool {
	if e == nil {
		return false
	}
	if len(e.conscriptEndTimes) == 0 {
		return false
	}
	e.conscriptEndTimes = nil
	e._dt.markFullReplace(FieldArmy_conscriptEndTimes)
	return true
}

func (e *ArmyEntity) LenConscriptCounts() int {
	if e == nil {
		return 0
	}
	return len(e.conscriptCounts)
}

func (e *ArmyEntity) AtConscriptCounts(index int) (int, bool) {
	var z int
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.conscriptCounts) {
		return z, false
	}
	return e.conscriptCounts[index], true
}

func (e *ArmyEntity) ForEachConscriptCounts(fn func(index int, value int)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.conscriptCounts {
		fn(i, v)
	}
}

func (e *ArmyEntity) RangeConscriptCounts(fn func(index int, value int) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.conscriptCounts {
		if !fn(i, v) {
			return
		}
	}
}

func (e *ArmyEntity) ReplaceConscriptCounts(v []int) bool {
	if e == nil {
		return false
	}
	if e.slicesEqualConscriptCounts(e.conscriptCounts, v) {
		return false
	}
	e.conscriptCounts = append([]int(nil), v...)
	e._dt.markFullReplace(FieldArmy_conscriptCounts)
	return true
}

func (e *ArmyEntity) AppendConscriptCounts(values ...int) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	e.conscriptCounts = append(e.conscriptCounts, values...)
	for _, v := range values {
		e._dt.markSliceAppend(FieldArmy_conscriptCounts, v)
	}
	return true
}

func (e *ArmyEntity) SetConscriptCountsAt(index int, value int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.conscriptCounts) {
		return false
	}
	if e.conscriptCounts[index] == value {
		return false
	}
	e.conscriptCounts[index] = value
	e._dt.markSliceSet(FieldArmy_conscriptCounts, index, value)
	return true
}

func (e *ArmyEntity) RemoveConscriptCountsAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.conscriptCounts) {
		return false
	}
	e.conscriptCounts = append(e.conscriptCounts[:index], e.conscriptCounts[index+1:]...)
	e._dt.markSliceRemoveAt(FieldArmy_conscriptCounts, index)
	return true
}

func (e *ArmyEntity) SwapRemoveConscriptCountsAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.conscriptCounts) {
		return false
	}
	last := len(e.conscriptCounts) - 1
	if index != last {
		e.conscriptCounts[index] = e.conscriptCounts[last]
	}
	e.conscriptCounts = e.conscriptCounts[:last]
	e._dt.markSliceSwapRemoveAt(FieldArmy_conscriptCounts, index)
	return true
}

func (e *ArmyEntity) ClearConscriptCounts() bool {
	if e == nil {
		return false
	}
	if len(e.conscriptCounts) == 0 {
		return false
	}
	e.conscriptCounts = nil
	e._dt.markFullReplace(FieldArmy_conscriptCounts)
	return true
}

func (e *ArmyEntity) CellX() int {
	if e == nil {
		var z int
		return z
	}
	return e.cellX
}

func (e *ArmyEntity) SetCellX(v int) bool {
	if e == nil {
		return false
	}
	if e.cellX == v {
		return false
	}
	e.cellX = v
	e._dt.mark(FieldArmy_cellX)
	return true
}

func (e *ArmyEntity) CellY() int {
	if e == nil {
		var z int
		return z
	}
	return e.cellY
}

func (e *ArmyEntity) SetCellY(v int) bool {
	if e == nil {
		return false
	}
	if e.cellY == v {
		return false
	}
	e.cellY = v
	e._dt.mark(FieldArmy_cellY)
	return true
}
