// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldFacility_id           Field = "id"
	FieldFacility_name         Field = "name"
	FieldFacility_privateLevel Field = "privateLevel"
	FieldFacility_fType        Field = "fType"
	FieldFacility_upTime       Field = "upTime"
)

type FacilityEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type FacilityEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type FacilityEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*FacilityEntityCollectionChangeInner
}

func (t *FacilityEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *FacilityEntityTrace) ensureChange(f Field) *FacilityEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*FacilityEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &FacilityEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *FacilityEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *FacilityEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *FacilityEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *FacilityEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *FacilityEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *FacilityEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *FacilityEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type FacilityState struct {
	Id           int
	Name         string
	PrivateLevel int8
	FType        int8
	UpTime       int64
}

type FacilityEntitySnap struct {
	Version     uint64
	State       FacilityState
	DirtyFields []Field
	Changes     map[Field]FacilityEntityCollectionChange
}

type FacilityEntity struct {
	id           int
	name         string
	privateLevel int8
	fType        int8
	upTime       int64
	_dt          FacilityEntityTrace
}

func HydrateFacilityEntity(s FacilityState) *FacilityEntity {
	return &FacilityEntity{
		id:           s.Id,
		name:         s.Name,
		privateLevel: s.PrivateLevel,
		fType:        s.FType,
		upTime:       s.UpTime,
	}
}

func (e *FacilityEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *FacilityEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = FacilityEntityTrace{}
}

func (e *FacilityEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *FacilityEntity) DirtyChanges() map[Field]FacilityEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]FacilityEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := FacilityEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneFacilityEntityCollectionChange(in FacilityEntityCollectionChange) FacilityEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *FacilityEntity) Save() FacilityState {
	var s FacilityState
	if e == nil {
		return s
	}
	s.Id = e.id
	s.Name = e.name
	s.PrivateLevel = e.privateLevel
	s.FType = e.fType
	s.UpTime = e.upTime
	return s
}

func NewFacilityEntitySnap(version uint64, e *FacilityEntity) *FacilityEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &FacilityEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *FacilityEntitySnap) Clone() *FacilityEntitySnap {
	if s == nil {
		return nil
	}
	out := &FacilityEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]FacilityEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneFacilityEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *FacilityEntity) Id() int {
	if e == nil {
		var z int
		return z
	}
	return e.id
}

func (e *FacilityEntity) SetId(v int) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldFacility_id)
	return true
}

func (e *FacilityEntity) Name() string {
	if e == nil {
		var z string
		return z
	}
	return e.name
}

func (e *FacilityEntity) SetName(v string) bool {
	if e == nil {
		return false
	}
	if e.name == v {
		return false
	}
	e.name = v
	e._dt.mark(FieldFacility_name)
	return true
}

func (e *FacilityEntity) PrivateLevel() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.privateLevel
}

func (e *FacilityEntity) SetPrivateLevel(v int8) bool {
	if e == nil {
		return false
	}
	if e.privateLevel == v {
		return false
	}
	e.privateLevel = v
	e._dt.mark(FieldFacility_privateLevel)
	return true
}

func (e *FacilityEntity) FType() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.fType
}

func (e *FacilityEntity) SetFType(v int8) bool {
	if e == nil {
		return false
	}
	if e.fType == v {
		return false
	}
	e.fType = v
	e._dt.mark(FieldFacility_fType)
	return true
}

func (e *FacilityEntity) UpTime() int64 {
	if e == nil {
		var z int64
		return z
	}
	return e.upTime
}

func (e *FacilityEntity) SetUpTime(v int64) bool {
	if e == nil {
		return false
	}
	if e.upTime == v {
		return false
	}
	e.upTime = v
	e._dt.mark(FieldFacility_upTime)
	return true
}
