// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"reflect"
	"sort"
	"time"
)

const (
	FieldGeneral_id             Field = "id"
	FieldGeneral_cfgId          Field = "cfgId"
	FieldGeneral_power          Field = "power"
	FieldGeneral_level          Field = "level"
	FieldGeneral_exp            Field = "exp"
	FieldGeneral_order          Field = "order"
	FieldGeneral_cityId         Field = "cityId"
	FieldGeneral_createdAt      Field = "createdAt"
	FieldGeneral_curArms        Field = "curArms"
	FieldGeneral_hasPrPoint     Field = "hasPrPoint"
	FieldGeneral_usePrPoint     Field = "usePrPoint"
	FieldGeneral_attackDistance Field = "attackDistance"
	FieldGeneral_forceAdded     Field = "forceAdded"
	FieldGeneral_strategyAdded  Field = "strategyAdded"
	FieldGeneral_defenseAdded   Field = "defenseAdded"
	FieldGeneral_speedAdded     Field = "speedAdded"
	FieldGeneral_destroyAdded   Field = "destroyAdded"
	FieldGeneral_starLv         Field = "starLv"
	FieldGeneral_star           Field = "star"
	FieldGeneral_parentId       Field = "parentId"
	FieldGeneral_skills         Field = "skills"
	FieldGeneral_skillsArray    Field = "skillsArray"
	FieldGeneral_state          Field = "state"
)

type GeneralEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type GeneralEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type GeneralEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*GeneralEntityCollectionChangeInner
}

func (t *GeneralEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *GeneralEntityTrace) ensureChange(f Field) *GeneralEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*GeneralEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &GeneralEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *GeneralEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *GeneralEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *GeneralEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *GeneralEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *GeneralEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *GeneralEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *GeneralEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type GeneralState struct {
	Id             int
	CfgId          int
	Power          int
	Level          int8
	Exp            int
	Order          int8
	CityId         int
	CreatedAt      time.Time
	CurArms        int
	HasPrPoint     int
	UsePrPoint     int
	AttackDistance int
	ForceAdded     int
	StrategyAdded  int
	DefenseAdded   int
	SpeedAdded     int
	DestroyAdded   int
	StarLv         int8
	Star           int8
	ParentId       int
	Skills         string
	SkillsArray    []GSkillState
	State          int8
}

type GeneralEntitySnap struct {
	Version     uint64
	State       GeneralState
	DirtyFields []Field
	Changes     map[Field]GeneralEntityCollectionChange
}

type GeneralEntity struct {
	id             int
	cfgId          int
	power          int
	level          int8
	exp            int
	order          int8
	cityId         int
	createdAt      time.Time
	curArms        int
	hasPrPoint     int
	usePrPoint     int
	attackDistance int
	forceAdded     int
	strategyAdded  int
	defenseAdded   int
	speedAdded     int
	destroyAdded   int
	starLv         int8
	star           int8
	parentId       int
	skills         string
	skillsArray    []*GSkillEntity
	state          int8
	_dt            GeneralEntityTrace
}

func hydrateSlice_skillsArray(in []GSkillState) []*GSkillEntity {
	if in == nil {
		return nil
	}
	out := make([]*GSkillEntity, len(in))
	for i, v := range in {
		out[i] = HydrateGSkillEntity(v)
	}
	return out
}

func snapshotSlice_skillsArray(in []*GSkillEntity) []GSkillState {
	if in == nil {
		return nil
	}
	out := make([]GSkillState, len(in))
	for i, v := range in {
		if v == nil {
			var z GSkillState
			out[i] = z
			continue
		}
		out[i] = v.Save()
	}
	return out
}

func slicesEqual_skillsArray(a, b []GSkillState) bool {
	if a == nil && b == nil {
		return true
	}
	if (a == nil) != (b == nil) {
		return false
	}
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !reflect.DeepEqual(a[i], b[i]) {
			return false
		}
	}
	return true
}

func HydrateGeneralEntity(s GeneralState) *GeneralEntity {
	return &GeneralEntity{
		id:             s.Id,
		cfgId:          s.CfgId,
		power:          s.Power,
		level:          s.Level,
		exp:            s.Exp,
		order:          s.Order,
		cityId:         s.CityId,
		createdAt:      s.CreatedAt,
		curArms:        s.CurArms,
		hasPrPoint:     s.HasPrPoint,
		usePrPoint:     s.UsePrPoint,
		attackDistance: s.AttackDistance,
		forceAdded:     s.ForceAdded,
		strategyAdded:  s.StrategyAdded,
		defenseAdded:   s.DefenseAdded,
		speedAdded:     s.SpeedAdded,
		destroyAdded:   s.DestroyAdded,
		starLv:         s.StarLv,
		star:           s.Star,
		parentId:       s.ParentId,
		skills:         s.Skills,
		skillsArray:    hydrateSlice_skillsArray(s.SkillsArray),
		state:          s.State,
	}
}

func (e *GeneralEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *GeneralEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = GeneralEntityTrace{}
}

func (e *GeneralEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *GeneralEntity) DirtyChanges() map[Field]GeneralEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]GeneralEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := GeneralEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneGeneralEntityCollectionChange(in GeneralEntityCollectionChange) GeneralEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *GeneralEntity) Save() GeneralState {
	var s GeneralState
	if e == nil {
		return s
	}
	s.Id = e.id
	s.CfgId = e.cfgId
	s.Power = e.power
	s.Level = e.level
	s.Exp = e.exp
	s.Order = e.order
	s.CityId = e.cityId
	s.CreatedAt = e.createdAt
	s.CurArms = e.curArms
	s.HasPrPoint = e.hasPrPoint
	s.UsePrPoint = e.usePrPoint
	s.AttackDistance = e.attackDistance
	s.ForceAdded = e.forceAdded
	s.StrategyAdded = e.strategyAdded
	s.DefenseAdded = e.defenseAdded
	s.SpeedAdded = e.speedAdded
	s.DestroyAdded = e.destroyAdded
	s.StarLv = e.starLv
	s.Star = e.star
	s.ParentId = e.parentId
	s.Skills = e.skills
	s.SkillsArray = snapshotSlice_skillsArray(e.skillsArray)
	s.State = e.state
	return s
}

func NewGeneralEntitySnap(version uint64, e *GeneralEntity) *GeneralEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &GeneralEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *GeneralEntitySnap) Clone() *GeneralEntitySnap {
	if s == nil {
		return nil
	}
	out := &GeneralEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]GeneralEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneGeneralEntityCollectionChange(ch)
		}
	}
	out.State.SkillsArray = append([]GSkillState(nil), s.State.SkillsArray...)
	return out
}

func (e *GeneralEntity) Id() int {
	if e == nil {
		var z int
		return z
	}
	return e.id
}

func (e *GeneralEntity) SetId(v int) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldGeneral_id)
	return true
}

func (e *GeneralEntity) CfgId() int {
	if e == nil {
		var z int
		return z
	}
	return e.cfgId
}

func (e *GeneralEntity) SetCfgId(v int) bool {
	if e == nil {
		return false
	}
	if e.cfgId == v {
		return false
	}
	e.cfgId = v
	e._dt.mark(FieldGeneral_cfgId)
	return true
}

func (e *GeneralEntity) Power() int {
	if e == nil {
		var z int
		return z
	}
	return e.power
}

func (e *GeneralEntity) SetPower(v int) bool {
	if e == nil {
		return false
	}
	if e.power == v {
		return false
	}
	e.power = v
	e._dt.mark(FieldGeneral_power)
	return true
}

func (e *GeneralEntity) Level() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.level
}

func (e *GeneralEntity) SetLevel(v int8) bool {
	if e == nil {
		return false
	}
	if e.level == v {
		return false
	}
	e.level = v
	e._dt.mark(FieldGeneral_level)
	return true
}

func (e *GeneralEntity) Exp() int {
	if e == nil {
		var z int
		return z
	}
	return e.exp
}

func (e *GeneralEntity) SetExp(v int) bool {
	if e == nil {
		return false
	}
	if e.exp == v {
		return false
	}
	e.exp = v
	e._dt.mark(FieldGeneral_exp)
	return true
}

func (e *GeneralEntity) Order() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.order
}

func (e *GeneralEntity) SetOrder(v int8) bool {
	if e == nil {
		return false
	}
	if e.order == v {
		return false
	}
	e.order = v
	e._dt.mark(FieldGeneral_order)
	return true
}

func (e *GeneralEntity) CityId() int {
	if e == nil {
		var z int
		return z
	}
	return e.cityId
}

func (e *GeneralEntity) SetCityId(v int) bool {
	if e == nil {
		return false
	}
	if e.cityId == v {
		return false
	}
	e.cityId = v
	e._dt.mark(FieldGeneral_cityId)
	return true
}

func (e *GeneralEntity) CreatedAt() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.createdAt
}

func (e *GeneralEntity) SetCreatedAt(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.createdAt.Equal(v) {
		return false
	}
	e.createdAt = v
	e._dt.mark(FieldGeneral_createdAt)
	return true
}

func (e *GeneralEntity) CurArms() int {
	if e == nil {
		var z int
		return z
	}
	return e.curArms
}

func (e *GeneralEntity) SetCurArms(v int) bool {
	if e == nil {
		return false
	}
	if e.curArms == v {
		return false
	}
	e.curArms = v
	e._dt.mark(FieldGeneral_curArms)
	return true
}

func (e *GeneralEntity) HasPrPoint() int {
	if e == nil {
		var z int
		return z
	}
	return e.hasPrPoint
}

func (e *GeneralEntity) SetHasPrPoint(v int) bool {
	if e == nil {
		return false
	}
	if e.hasPrPoint == v {
		return false
	}
	e.hasPrPoint = v
	e._dt.mark(FieldGeneral_hasPrPoint)
	return true
}

func (e *GeneralEntity) UsePrPoint() int {
	if e == nil {
		var z int
		return z
	}
	return e.usePrPoint
}

func (e *GeneralEntity) SetUsePrPoint(v int) bool {
	if e == nil {
		return false
	}
	if e.usePrPoint == v {
		return false
	}
	e.usePrPoint = v
	e._dt.mark(FieldGeneral_usePrPoint)
	return true
}

func (e *GeneralEntity) AttackDistance() int {
	if e == nil {
		var z int
		return z
	}
	return e.attackDistance
}

func (e *GeneralEntity) SetAttackDistance(v int) bool {
	if e == nil {
		return false
	}
	if e.attackDistance == v {
		return false
	}
	e.attackDistance = v
	e._dt.mark(FieldGeneral_attackDistance)
	return true
}

func (e *GeneralEntity) ForceAdded() int {
	if e == nil {
		var z int
		return z
	}
	return e.forceAdded
}

func (e *GeneralEntity) SetForceAdded(v int) bool {
	if e == nil {
		return false
	}
	if e.forceAdded == v {
		return false
	}
	e.forceAdded = v
	e._dt.mark(FieldGeneral_forceAdded)
	return true
}

func (e *GeneralEntity) StrategyAdded() int {
	if e == nil {
		var z int
		return z
	}
	return e.strategyAdded
}

func (e *GeneralEntity) SetStrategyAdded(v int) bool {
	if e == nil {
		return false
	}
	if e.strategyAdded == v {
		return false
	}
	e.strategyAdded = v
	e._dt.mark(FieldGeneral_strategyAdded)
	return true
}

func (e *GeneralEntity) DefenseAdded() int {
	if e == nil {
		var z int
		return z
	}
	return e.defenseAdded
}

func (e *GeneralEntity) SetDefenseAdded(v int) bool {
	if e == nil {
		return false
	}
	if e.defenseAdded == v {
		return false
	}
	e.defenseAdded = v
	e._dt.mark(FieldGeneral_defenseAdded)
	return true
}

func (e *GeneralEntity) SpeedAdded() int {
	if e == nil {
		var z int
		return z
	}
	return e.speedAdded
}

func (e *GeneralEntity) SetSpeedAdded(v int) bool {
	if e == nil {
		return false
	}
	if e.speedAdded == v {
		return false
	}
	e.speedAdded = v
	e._dt.mark(FieldGeneral_speedAdded)
	return true
}

func (e *GeneralEntity) DestroyAdded() int {
	if e == nil {
		var z int
		return z
	}
	return e.destroyAdded
}

func (e *GeneralEntity) SetDestroyAdded(v int) bool {
	if e == nil {
		return false
	}
	if e.destroyAdded == v {
		return false
	}
	e.destroyAdded = v
	e._dt.mark(FieldGeneral_destroyAdded)
	return true
}

func (e *GeneralEntity) StarLv() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.starLv
}

func (e *GeneralEntity) SetStarLv(v int8) bool {
	if e == nil {
		return false
	}
	if e.starLv == v {
		return false
	}
	e.starLv = v
	e._dt.mark(FieldGeneral_starLv)
	return true
}

func (e *GeneralEntity) Star() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.star
}

func (e *GeneralEntity) SetStar(v int8) bool {
	if e == nil {
		return false
	}
	if e.star == v {
		return false
	}
	e.star = v
	e._dt.mark(FieldGeneral_star)
	return true
}

func (e *GeneralEntity) ParentId() int {
	if e == nil {
		var z int
		return z
	}
	return e.parentId
}

func (e *GeneralEntity) SetParentId(v int) bool {
	if e == nil {
		return false
	}
	if e.parentId == v {
		return false
	}
	e.parentId = v
	e._dt.mark(FieldGeneral_parentId)
	return true
}

func (e *GeneralEntity) Skills() string {
	if e == nil {
		var z string
		return z
	}
	return e.skills
}

func (e *GeneralEntity) SetSkills(v string) bool {
	if e == nil {
		return false
	}
	if e.skills == v {
		return false
	}
	e.skills = v
	e._dt.mark(FieldGeneral_skills)
	return true
}

func (e *GeneralEntity) LenSkillsArray() int {
	if e == nil {
		return 0
	}
	return len(e.skillsArray)
}

func (e *GeneralEntity) AtSkillsArray(index int) (GSkillState, bool) {
	var z GSkillState
	if e == nil {
		return z, false
	}
	if index < 0 || index >= len(e.skillsArray) {
		return z, false
	}
	v := e.skillsArray[index]
	if v == nil {
		return z, true
	}
	return v.Save(), true
}

func (e *GeneralEntity) ForEachSkillsArray(fn func(index int, value GSkillState)) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.skillsArray {
		var state GSkillState
		if v != nil {
			state = v.Save()
		}
		fn(i, state)
	}
}

func (e *GeneralEntity) RangeSkillsArray(fn func(index int, value GSkillState) bool) {
	if e == nil || fn == nil {
		return
	}
	for i, v := range e.skillsArray {
		var state GSkillState
		if v != nil {
			state = v.Save()
		}
		if !fn(i, state) {
			return
		}
	}
}

func (e *GeneralEntity) ReplaceSkillsArray(v []GSkillState) bool {
	if e == nil {
		return false
	}
	if slicesEqual_skillsArray(snapshotSlice_skillsArray(e.skillsArray), v) {
		return false
	}
	e.skillsArray = hydrateSlice_skillsArray(v)
	e._dt.markFullReplace(FieldGeneral_skillsArray)
	return true
}

func (e *GeneralEntity) AppendSkillsArray(values ...GSkillState) bool {
	if e == nil || len(values) == 0 {
		return false
	}
	for _, v := range values {
		rv := HydrateGSkillEntity(v)
		e.skillsArray = append(e.skillsArray, rv)
		e._dt.markSliceAppend(FieldGeneral_skillsArray, v)
	}
	return true
}

func (e *GeneralEntity) SetSkillsArrayAt(index int, value GSkillState) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.skillsArray) {
		return false
	}
	var oldState GSkillState
	if e.skillsArray[index] != nil {
		oldState = e.skillsArray[index].Save()
	}
	if reflect.DeepEqual(oldState, value) {
		return false
	}
	e.skillsArray[index] = HydrateGSkillEntity(value)
	e._dt.markSliceSet(FieldGeneral_skillsArray, index, value)
	return true
}

func (e *GeneralEntity) UpdateSkillsArrayAt(index int, fn func(value *GSkillEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if index < 0 || index >= len(e.skillsArray) {
		return false
	}
	v := e.skillsArray[index]
	if v == nil {
		return false
	}
	before := v.Save()
	fn(v)
	after := v.Save()
	if reflect.DeepEqual(before, after) {
		return false
	}
	e._dt.markSliceSet(FieldGeneral_skillsArray, index, after)
	return true
}

func (e *GeneralEntity) RemoveSkillsArrayAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.skillsArray) {
		return false
	}
	e.skillsArray = append(e.skillsArray[:index], e.skillsArray[index+1:]...)
	e._dt.markSliceRemoveAt(FieldGeneral_skillsArray, index)
	return true
}

func (e *GeneralEntity) SwapRemoveSkillsArrayAt(index int) bool {
	if e == nil {
		return false
	}
	if index < 0 || index >= len(e.skillsArray) {
		return false
	}
	last := len(e.skillsArray) - 1
	if index != last {
		e.skillsArray[index] = e.skillsArray[last]
	}
	e.skillsArray = e.skillsArray[:last]
	e._dt.markSliceSwapRemoveAt(FieldGeneral_skillsArray, index)
	return true
}

func (e *GeneralEntity) ClearSkillsArray() bool {
	if e == nil {
		return false
	}
	if len(e.skillsArray) == 0 {
		return false
	}
	e.skillsArray = nil
	e._dt.markFullReplace(FieldGeneral_skillsArray)
	return true
}

func (e *GeneralEntity) State() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.state
}

func (e *GeneralEntity) SetState(v int8) bool {
	if e == nil {
		return false
	}
	if e.state == v {
		return false
	}
	e.state = v
	e._dt.mark(FieldGeneral_state)
	return true
}
