// Code generated by gen_persistence_mappers; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldResource_id     Field = "id"
	FieldResource_rid    Field = "rid"
	FieldResource_wood   Field = "wood"
	FieldResource_iron   Field = "iron"
	FieldResource_stone  Field = "stone"
	FieldResource_grain  Field = "grain"
	FieldResource_gold   Field = "gold"
	FieldResource_decree Field = "decree"
)

type ResourceEntityTrace struct {
	dirty bool
	trace map[Field]bool
}

func (t *ResourceEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

type ResourceEntitySnapshot struct {
	Id     uint32
	Rid    uint32
	Wood   uint32
	Iron   uint32
	Stone  uint32
	Grain  uint32
	Gold   uint32
	Decree uint32
}

type ResourceEntity struct {
	id     uint32
	rid    uint32
	wood   uint32
	iron   uint32
	stone  uint32
	grain  uint32
	gold   uint32
	decree uint32
	_dt    ResourceEntityTrace
}

func HydrateResourceEntity(s ResourceEntitySnapshot) *ResourceEntity {
	return &ResourceEntity{
		id:     s.Id,
		rid:    s.Rid,
		wood:   s.Wood,
		iron:   s.Iron,
		stone:  s.Stone,
		grain:  s.Grain,
		gold:   s.Gold,
		decree: s.Decree,
	}
}

func (e *ResourceEntity) Dirty() bool {
	if e == nil {
		return false
	}
	return e._dt.dirty
}

func (e *ResourceEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = ResourceEntityTrace{}
}

func (e *ResourceEntity) DirtyFields() []Field {
	if e == nil || e._dt.trace == nil {
		return nil
	}
	out := make([]Field, 0, len(e._dt.trace))
	for k := range e._dt.trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *ResourceEntity) Snapshot() ResourceEntitySnapshot {
	var s ResourceEntitySnapshot
	if e == nil {
		return s
	}
	s.Id = e.id
	s.Rid = e.rid
	s.Wood = e.wood
	s.Iron = e.iron
	s.Stone = e.stone
	s.Grain = e.grain
	s.Gold = e.gold
	s.Decree = e.decree
	return s
}

func (e *ResourceEntity) Id() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.id
}

func (e *ResourceEntity) SetId(v uint32) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldResource_id)
	return true
}

func (e *ResourceEntity) Rid() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.rid
}

func (e *ResourceEntity) SetRid(v uint32) bool {
	if e == nil {
		return false
	}
	if e.rid == v {
		return false
	}
	e.rid = v
	e._dt.mark(FieldResource_rid)
	return true
}

func (e *ResourceEntity) Wood() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.wood
}

func (e *ResourceEntity) SetWood(v uint32) bool {
	if e == nil {
		return false
	}
	if e.wood == v {
		return false
	}
	e.wood = v
	e._dt.mark(FieldResource_wood)
	return true
}

func (e *ResourceEntity) Iron() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.iron
}

func (e *ResourceEntity) SetIron(v uint32) bool {
	if e == nil {
		return false
	}
	if e.iron == v {
		return false
	}
	e.iron = v
	e._dt.mark(FieldResource_iron)
	return true
}

func (e *ResourceEntity) Stone() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.stone
}

func (e *ResourceEntity) SetStone(v uint32) bool {
	if e == nil {
		return false
	}
	if e.stone == v {
		return false
	}
	e.stone = v
	e._dt.mark(FieldResource_stone)
	return true
}

func (e *ResourceEntity) Grain() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.grain
}

func (e *ResourceEntity) SetGrain(v uint32) bool {
	if e == nil {
		return false
	}
	if e.grain == v {
		return false
	}
	e.grain = v
	e._dt.mark(FieldResource_grain)
	return true
}

func (e *ResourceEntity) Gold() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.gold
}

func (e *ResourceEntity) SetGold(v uint32) bool {
	if e == nil {
		return false
	}
	if e.gold == v {
		return false
	}
	e.gold = v
	e._dt.mark(FieldResource_gold)
	return true
}

func (e *ResourceEntity) Decree() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.decree
}

func (e *ResourceEntity) SetDecree(v uint32) bool {
	if e == nil {
		return false
	}
	if e.decree == v {
		return false
	}
	e.decree = v
	e._dt.mark(FieldResource_decree)
	return true
}
