// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldResource_wood   Field = "wood"
	FieldResource_iron   Field = "iron"
	FieldResource_stone  Field = "stone"
	FieldResource_grain  Field = "grain"
	FieldResource_gold   Field = "gold"
	FieldResource_decree Field = "decree"
)

type ResourceEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type ResourceEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type ResourceEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*ResourceEntityCollectionChangeInner
}

func (t *ResourceEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *ResourceEntityTrace) ensureChange(f Field) *ResourceEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*ResourceEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &ResourceEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *ResourceEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *ResourceEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *ResourceEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *ResourceEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *ResourceEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *ResourceEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *ResourceEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type ResourceState struct {
	Wood   int
	Iron   int
	Stone  int
	Grain  int
	Gold   int
	Decree int
}

type ResourceEntitySnap struct {
	Version     uint64
	State       ResourceState
	DirtyFields []Field
	Changes     map[Field]ResourceEntityCollectionChange
}

type ResourceEntity struct {
	wood   int
	iron   int
	stone  int
	grain  int
	gold   int
	decree int
	_dt    ResourceEntityTrace
}

func HydrateResourceEntity(s ResourceState) *ResourceEntity {
	return &ResourceEntity{
		wood:   s.Wood,
		iron:   s.Iron,
		stone:  s.Stone,
		grain:  s.Grain,
		gold:   s.Gold,
		decree: s.Decree,
	}
}

func (e *ResourceEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *ResourceEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = ResourceEntityTrace{}
}

func (e *ResourceEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *ResourceEntity) DirtyChanges() map[Field]ResourceEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]ResourceEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := ResourceEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneResourceEntityCollectionChange(in ResourceEntityCollectionChange) ResourceEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *ResourceEntity) Save() ResourceState {
	var s ResourceState
	if e == nil {
		return s
	}
	s.Wood = e.wood
	s.Iron = e.iron
	s.Stone = e.stone
	s.Grain = e.grain
	s.Gold = e.gold
	s.Decree = e.decree
	return s
}

func NewResourceEntitySnap(version uint64, e *ResourceEntity) *ResourceEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &ResourceEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *ResourceEntitySnap) Clone() *ResourceEntitySnap {
	if s == nil {
		return nil
	}
	out := &ResourceEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]ResourceEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneResourceEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *ResourceEntity) Wood() int {
	if e == nil {
		var z int
		return z
	}
	return e.wood
}

func (e *ResourceEntity) SetWood(v int) bool {
	if e == nil {
		return false
	}
	if e.wood == v {
		return false
	}
	e.wood = v
	e._dt.mark(FieldResource_wood)
	return true
}

func (e *ResourceEntity) Iron() int {
	if e == nil {
		var z int
		return z
	}
	return e.iron
}

func (e *ResourceEntity) SetIron(v int) bool {
	if e == nil {
		return false
	}
	if e.iron == v {
		return false
	}
	e.iron = v
	e._dt.mark(FieldResource_iron)
	return true
}

func (e *ResourceEntity) Stone() int {
	if e == nil {
		var z int
		return z
	}
	return e.stone
}

func (e *ResourceEntity) SetStone(v int) bool {
	if e == nil {
		return false
	}
	if e.stone == v {
		return false
	}
	e.stone = v
	e._dt.mark(FieldResource_stone)
	return true
}

func (e *ResourceEntity) Grain() int {
	if e == nil {
		var z int
		return z
	}
	return e.grain
}

func (e *ResourceEntity) SetGrain(v int) bool {
	if e == nil {
		return false
	}
	if e.grain == v {
		return false
	}
	e.grain = v
	e._dt.mark(FieldResource_grain)
	return true
}

func (e *ResourceEntity) Gold() int {
	if e == nil {
		var z int
		return z
	}
	return e.gold
}

func (e *ResourceEntity) SetGold(v int) bool {
	if e == nil {
		return false
	}
	if e.gold == v {
		return false
	}
	e.gold = v
	e._dt.mark(FieldResource_gold)
	return true
}

func (e *ResourceEntity) Decree() int {
	if e == nil {
		var z int
		return z
	}
	return e.decree
}

func (e *ResourceEntity) SetDecree(v int) bool {
	if e == nil {
		return false
	}
	if e.decree == v {
		return false
	}
	e.decree = v
	e._dt.mark(FieldResource_decree)
	return true
}
