// Code generated by gen_persistence_mappers; DO NOT EDIT.
package entity

import (
	"sort"
	"time"
)

const (
	FieldRole_rid        Field = "rid"
	FieldRole_uid        Field = "uid"
	FieldRole_headid     Field = "headid"
	FieldRole_sex        Field = "sex"
	FieldRole_nickName   Field = "nickName"
	FieldRole_balance    Field = "balance"
	FieldRole_loginTime  Field = "loginTime"
	FieldRole_logoutTime Field = "logoutTime"
	FieldRole_profile    Field = "profile"
	FieldRole_createdAt  Field = "createdAt"
)

type RoleEntityTrace struct {
	dirty bool
	trace map[Field]bool
}

func (t *RoleEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

type RoleEntitySnapshot struct {
	Rid        uint32
	Uid        uint32
	Headid     uint32
	Sex        uint8
	NickName   string
	Balance    uint32
	LoginTime  time.Time
	LogoutTime time.Time
	Profile    string
	CreatedAt  time.Time
}

type RoleEntity struct {
	rid        uint32
	uid        uint32
	headid     uint32
	sex        uint8
	nickName   string
	balance    uint32
	loginTime  time.Time
	logoutTime time.Time
	profile    string
	createdAt  time.Time
	_dt        RoleEntityTrace
}

func HydrateRoleEntity(s RoleEntitySnapshot) *RoleEntity {
	return &RoleEntity{
		rid:        s.Rid,
		uid:        s.Uid,
		headid:     s.Headid,
		sex:        s.Sex,
		nickName:   s.NickName,
		balance:    s.Balance,
		loginTime:  s.LoginTime,
		logoutTime: s.LogoutTime,
		profile:    s.Profile,
		createdAt:  s.CreatedAt,
	}
}

func (e *RoleEntity) Dirty() bool {
	if e == nil {
		return false
	}
	return e._dt.dirty
}

func (e *RoleEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = RoleEntityTrace{}
}

func (e *RoleEntity) DirtyFields() []Field {
	if e == nil || e._dt.trace == nil {
		return nil
	}
	out := make([]Field, 0, len(e._dt.trace))
	for k := range e._dt.trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *RoleEntity) Snapshot() RoleEntitySnapshot {
	var s RoleEntitySnapshot
	if e == nil {
		return s
	}
	s.Rid = e.rid
	s.Uid = e.uid
	s.Headid = e.headid
	s.Sex = e.sex
	s.NickName = e.nickName
	s.Balance = e.balance
	s.LoginTime = e.loginTime
	s.LogoutTime = e.logoutTime
	s.Profile = e.profile
	s.CreatedAt = e.createdAt
	return s
}

func (e *RoleEntity) Rid() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.rid
}

func (e *RoleEntity) SetRid(v uint32) bool {
	if e == nil {
		return false
	}
	if e.rid == v {
		return false
	}
	e.rid = v
	e._dt.mark(FieldRole_rid)
	return true
}

func (e *RoleEntity) Uid() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.uid
}

func (e *RoleEntity) SetUid(v uint32) bool {
	if e == nil {
		return false
	}
	if e.uid == v {
		return false
	}
	e.uid = v
	e._dt.mark(FieldRole_uid)
	return true
}

func (e *RoleEntity) Headid() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.headid
}

func (e *RoleEntity) SetHeadid(v uint32) bool {
	if e == nil {
		return false
	}
	if e.headid == v {
		return false
	}
	e.headid = v
	e._dt.mark(FieldRole_headid)
	return true
}

func (e *RoleEntity) Sex() uint8 {
	if e == nil {
		var z uint8
		return z
	}
	return e.sex
}

func (e *RoleEntity) SetSex(v uint8) bool {
	if e == nil {
		return false
	}
	if e.sex == v {
		return false
	}
	e.sex = v
	e._dt.mark(FieldRole_sex)
	return true
}

func (e *RoleEntity) NickName() string {
	if e == nil {
		var z string
		return z
	}
	return e.nickName
}

func (e *RoleEntity) SetNickName(v string) bool {
	if e == nil {
		return false
	}
	if e.nickName == v {
		return false
	}
	e.nickName = v
	e._dt.mark(FieldRole_nickName)
	return true
}

func (e *RoleEntity) Balance() uint32 {
	if e == nil {
		var z uint32
		return z
	}
	return e.balance
}

func (e *RoleEntity) SetBalance(v uint32) bool {
	if e == nil {
		return false
	}
	if e.balance == v {
		return false
	}
	e.balance = v
	e._dt.mark(FieldRole_balance)
	return true
}

func (e *RoleEntity) LoginTime() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.loginTime
}

func (e *RoleEntity) SetLoginTime(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.loginTime.Equal(v) {
		return false
	}
	e.loginTime = v
	e._dt.mark(FieldRole_loginTime)
	return true
}

func (e *RoleEntity) LogoutTime() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.logoutTime
}

func (e *RoleEntity) SetLogoutTime(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.logoutTime.Equal(v) {
		return false
	}
	e.logoutTime = v
	e._dt.mark(FieldRole_logoutTime)
	return true
}

func (e *RoleEntity) Profile() string {
	if e == nil {
		var z string
		return z
	}
	return e.profile
}

func (e *RoleEntity) SetProfile(v string) bool {
	if e == nil {
		return false
	}
	if e.profile == v {
		return false
	}
	e.profile = v
	e._dt.mark(FieldRole_profile)
	return true
}

func (e *RoleEntity) CreatedAt() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.createdAt
}

func (e *RoleEntity) SetCreatedAt(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.createdAt.Equal(v) {
		return false
	}
	e.createdAt = v
	e._dt.mark(FieldRole_createdAt)
	return true
}
