// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
	"time"
)

const (
	FieldRole_headid     Field = "headid"
	FieldRole_sex        Field = "sex"
	FieldRole_nickName   Field = "nickName"
	FieldRole_balance    Field = "balance"
	FieldRole_loginTime  Field = "loginTime"
	FieldRole_logoutTime Field = "logoutTime"
	FieldRole_profile    Field = "profile"
	FieldRole_createdAt  Field = "createdAt"
)

type RoleEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type RoleEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type RoleEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*RoleEntityCollectionChangeInner
}

func (t *RoleEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *RoleEntityTrace) ensureChange(f Field) *RoleEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*RoleEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &RoleEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *RoleEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *RoleEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *RoleEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *RoleEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *RoleEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *RoleEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *RoleEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type RoleState struct {
	Headid     int16
	Sex        int8
	NickName   string
	Balance    int
	LoginTime  time.Time
	LogoutTime time.Time
	Profile    string
	CreatedAt  time.Time
}

type RoleEntitySnap struct {
	Version     uint64
	State       RoleState
	DirtyFields []Field
	Changes     map[Field]RoleEntityCollectionChange
}

type RoleEntity struct {
	headid     int16
	sex        int8
	nickName   string
	balance    int
	loginTime  time.Time
	logoutTime time.Time
	profile    string
	createdAt  time.Time
	_dt        RoleEntityTrace
}

func HydrateRoleEntity(s RoleState) *RoleEntity {
	return &RoleEntity{
		headid:     s.Headid,
		sex:        s.Sex,
		nickName:   s.NickName,
		balance:    s.Balance,
		loginTime:  s.LoginTime,
		logoutTime: s.LogoutTime,
		profile:    s.Profile,
		createdAt:  s.CreatedAt,
	}
}

func (e *RoleEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	return false
}

func (e *RoleEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = RoleEntityTrace{}
}

func (e *RoleEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *RoleEntity) DirtyChanges() map[Field]RoleEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]RoleEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := RoleEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneRoleEntityCollectionChange(in RoleEntityCollectionChange) RoleEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *RoleEntity) Save() RoleState {
	var s RoleState
	if e == nil {
		return s
	}
	s.Headid = e.headid
	s.Sex = e.sex
	s.NickName = e.nickName
	s.Balance = e.balance
	s.LoginTime = e.loginTime
	s.LogoutTime = e.logoutTime
	s.Profile = e.profile
	s.CreatedAt = e.createdAt
	return s
}

func NewRoleEntitySnap(version uint64, e *RoleEntity) *RoleEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &RoleEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *RoleEntitySnap) Clone() *RoleEntitySnap {
	if s == nil {
		return nil
	}
	out := &RoleEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]RoleEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneRoleEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *RoleEntity) Headid() int16 {
	if e == nil {
		var z int16
		return z
	}
	return e.headid
}

func (e *RoleEntity) SetHeadid(v int16) bool {
	if e == nil {
		return false
	}
	if e.headid == v {
		return false
	}
	e.headid = v
	e._dt.mark(FieldRole_headid)
	return true
}

func (e *RoleEntity) Sex() int8 {
	if e == nil {
		var z int8
		return z
	}
	return e.sex
}

func (e *RoleEntity) SetSex(v int8) bool {
	if e == nil {
		return false
	}
	if e.sex == v {
		return false
	}
	e.sex = v
	e._dt.mark(FieldRole_sex)
	return true
}

func (e *RoleEntity) NickName() string {
	if e == nil {
		var z string
		return z
	}
	return e.nickName
}

func (e *RoleEntity) SetNickName(v string) bool {
	if e == nil {
		return false
	}
	if e.nickName == v {
		return false
	}
	e.nickName = v
	e._dt.mark(FieldRole_nickName)
	return true
}

func (e *RoleEntity) Balance() int {
	if e == nil {
		var z int
		return z
	}
	return e.balance
}

func (e *RoleEntity) SetBalance(v int) bool {
	if e == nil {
		return false
	}
	if e.balance == v {
		return false
	}
	e.balance = v
	e._dt.mark(FieldRole_balance)
	return true
}

func (e *RoleEntity) LoginTime() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.loginTime
}

func (e *RoleEntity) SetLoginTime(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.loginTime.Equal(v) {
		return false
	}
	e.loginTime = v
	e._dt.mark(FieldRole_loginTime)
	return true
}

func (e *RoleEntity) LogoutTime() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.logoutTime
}

func (e *RoleEntity) SetLogoutTime(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.logoutTime.Equal(v) {
		return false
	}
	e.logoutTime = v
	e._dt.mark(FieldRole_logoutTime)
	return true
}

func (e *RoleEntity) Profile() string {
	if e == nil {
		var z string
		return z
	}
	return e.profile
}

func (e *RoleEntity) SetProfile(v string) bool {
	if e == nil {
		return false
	}
	if e.profile == v {
		return false
	}
	e.profile = v
	e._dt.mark(FieldRole_profile)
	return true
}

func (e *RoleEntity) CreatedAt() time.Time {
	if e == nil {
		var z time.Time
		return z
	}
	return e.createdAt
}

func (e *RoleEntity) SetCreatedAt(v time.Time) bool {
	if e == nil {
		return false
	}
	if e.createdAt.Equal(v) {
		return false
	}
	e.createdAt = v
	e._dt.mark(FieldRole_createdAt)
	return true
}
