// Code generated by gen_entities; DO NOT EDIT.
package entity

type PlayerID int

type WorldID int

type RoleStatus int

type PosTag struct {
	X    int    `json:"x"`
	Y    int    `json:"y"`
	Name string `json:"name"`
}
