// Code generated by gen_entities; DO NOT EDIT.
package entity

import (
	"sort"
)

const (
	FieldWarReport_id                Field = "id"
	FieldWarReport_attacker          Field = "attacker"
	FieldWarReport_defender          Field = "defender"
	FieldWarReport_begAttackArmy     Field = "begAttackArmy"
	FieldWarReport_begDefenseArmy    Field = "begDefenseArmy"
	FieldWarReport_endAttackArmy     Field = "endAttackArmy"
	FieldWarReport_endDefenseArmy    Field = "endDefenseArmy"
	FieldWarReport_begAttackGeneral  Field = "begAttackGeneral"
	FieldWarReport_begDefenseGeneral Field = "begDefenseGeneral"
	FieldWarReport_endAttackGeneral  Field = "endAttackGeneral"
	FieldWarReport_endDefenseGeneral Field = "endDefenseGeneral"
	FieldWarReport_result            Field = "result"
	FieldWarReport_rounds            Field = "rounds"
	FieldWarReport_attackIsRead      Field = "attackIsRead"
	FieldWarReport_defenseIsRead     Field = "defenseIsRead"
	FieldWarReport_destroyDurable    Field = "destroyDurable"
	FieldWarReport_occupy            Field = "occupy"
	FieldWarReport_x                 Field = "x"
	FieldWarReport_y                 Field = "y"
	FieldWarReport_cTime             Field = "cTime"
)

type WarReportEntityCollectionChange struct {
	FullReplace       bool
	MapSet            map[string]any
	MapDeleteKeys     []string
	SliceSet          map[int]any
	SliceAppend       []any
	SliceRemoveAt     []int
	SliceSwapRemoveAt []int
}

type WarReportEntityCollectionChangeInner struct {
	fullReplace       bool
	mapSet            map[string]any
	mapDelete         map[string]struct{}
	sliceSet          map[int]any
	sliceAppend       []any
	sliceRemoveAt     []int
	sliceSwapRemoveAt []int
}

type WarReportEntityTrace struct {
	dirty   bool
	trace   map[Field]bool
	changes map[Field]*WarReportEntityCollectionChangeInner
}

func (t *WarReportEntityTrace) mark(f Field) {
	t.dirty = true
	if t.trace == nil {
		t.trace = make(map[Field]bool, 8)
	}
	t.trace[f] = true
}

func (t *WarReportEntityTrace) ensureChange(f Field) *WarReportEntityCollectionChangeInner {
	if t.changes == nil {
		t.changes = make(map[Field]*WarReportEntityCollectionChangeInner, 4)
	}
	ch, ok := t.changes[f]
	if !ok || ch == nil {
		ch = &WarReportEntityCollectionChangeInner{}
		t.changes[f] = ch
	}
	return ch
}

func (t *WarReportEntityTrace) markFullReplace(f Field) {
	t.mark(f)
	ch := t.ensureChange(f)
	ch.fullReplace = true
	ch.mapSet = nil
	ch.mapDelete = nil
	ch.sliceSet = nil
	ch.sliceAppend = nil
	ch.sliceRemoveAt = nil
	ch.sliceSwapRemoveAt = nil
}

func (t *WarReportEntityTrace) markMapSet(f Field, key string, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapSet == nil {
		ch.mapSet = make(map[string]any, 4)
	}
	ch.mapSet[key] = value
	if ch.mapDelete != nil {
		delete(ch.mapDelete, key)
	}
}

func (t *WarReportEntityTrace) markMapDelete(f Field, key string) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.mapDelete == nil {
		ch.mapDelete = make(map[string]struct{}, 4)
	}
	ch.mapDelete[key] = struct{}{}
	if ch.mapSet != nil {
		delete(ch.mapSet, key)
	}
}

func (t *WarReportEntityTrace) markSliceAppend(f Field, values ...any) {
	if len(values) == 0 {
		return
	}
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceAppend = append(ch.sliceAppend, values...)
}

func (t *WarReportEntityTrace) markSliceSet(f Field, index int, value any) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	if ch.sliceSet == nil {
		ch.sliceSet = make(map[int]any, 4)
	}
	ch.sliceSet[index] = value
}

func (t *WarReportEntityTrace) markSliceRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceRemoveAt = append(ch.sliceRemoveAt, index)
}

func (t *WarReportEntityTrace) markSliceSwapRemoveAt(f Field, index int) {
	t.mark(f)
	ch := t.ensureChange(f)
	if ch.fullReplace {
		return
	}
	ch.sliceSwapRemoveAt = append(ch.sliceSwapRemoveAt, index)
}

type WarReportState struct {
	Id                int
	Attacker          int
	Defender          int
	BegAttackArmy     ArmyState
	BegDefenseArmy    ArmyState
	EndAttackArmy     ArmyState
	EndDefenseArmy    ArmyState
	BegAttackGeneral  GeneralState
	BegDefenseGeneral GeneralState
	EndAttackGeneral  GeneralState
	EndDefenseGeneral GeneralState
	Result            int
	Rounds            string
	AttackIsRead      bool
	DefenseIsRead     bool
	DestroyDurable    int
	Occupy            int
	X                 int
	Y                 int
	CTime             int
}

type WarReportEntitySnap struct {
	Version     uint64
	State       WarReportState
	DirtyFields []Field
	Changes     map[Field]WarReportEntityCollectionChange
}

type WarReportEntity struct {
	id                int
	attacker          int
	defender          int
	begAttackArmy     *ArmyEntity
	begDefenseArmy    *ArmyEntity
	endAttackArmy     *ArmyEntity
	endDefenseArmy    *ArmyEntity
	begAttackGeneral  *GeneralEntity
	begDefenseGeneral *GeneralEntity
	endAttackGeneral  *GeneralEntity
	endDefenseGeneral *GeneralEntity
	result            int
	rounds            string
	attackIsRead      bool
	defenseIsRead     bool
	destroyDurable    int
	occupy            int
	x                 int
	y                 int
	cTime             int
	_dt               WarReportEntityTrace
}

func HydrateWarReportEntity(s WarReportState) *WarReportEntity {
	return &WarReportEntity{
		id:                s.Id,
		attacker:          s.Attacker,
		defender:          s.Defender,
		begAttackArmy:     HydrateArmyEntity(s.BegAttackArmy),
		begDefenseArmy:    HydrateArmyEntity(s.BegDefenseArmy),
		endAttackArmy:     HydrateArmyEntity(s.EndAttackArmy),
		endDefenseArmy:    HydrateArmyEntity(s.EndDefenseArmy),
		begAttackGeneral:  HydrateGeneralEntity(s.BegAttackGeneral),
		begDefenseGeneral: HydrateGeneralEntity(s.BegDefenseGeneral),
		endAttackGeneral:  HydrateGeneralEntity(s.EndAttackGeneral),
		endDefenseGeneral: HydrateGeneralEntity(s.EndDefenseGeneral),
		result:            s.Result,
		rounds:            s.Rounds,
		attackIsRead:      s.AttackIsRead,
		defenseIsRead:     s.DefenseIsRead,
		destroyDurable:    s.DestroyDurable,
		occupy:            s.Occupy,
		x:                 s.X,
		y:                 s.Y,
		cTime:             s.CTime,
	}
}

func (e *WarReportEntity) Dirty() bool {
	if e == nil {
		return false
	}
	if e._dt.dirty {
		return true
	}
	if e.begAttackArmy != nil && e.begAttackArmy.Dirty() {
		return true
	}
	if e.begDefenseArmy != nil && e.begDefenseArmy.Dirty() {
		return true
	}
	if e.endAttackArmy != nil && e.endAttackArmy.Dirty() {
		return true
	}
	if e.endDefenseArmy != nil && e.endDefenseArmy.Dirty() {
		return true
	}
	if e.begAttackGeneral != nil && e.begAttackGeneral.Dirty() {
		return true
	}
	if e.begDefenseGeneral != nil && e.begDefenseGeneral.Dirty() {
		return true
	}
	if e.endAttackGeneral != nil && e.endAttackGeneral.Dirty() {
		return true
	}
	if e.endDefenseGeneral != nil && e.endDefenseGeneral.Dirty() {
		return true
	}
	return false
}

func (e *WarReportEntity) ClearDirty() {
	if e == nil {
		return
	}
	e._dt = WarReportEntityTrace{}
	if e.begAttackArmy != nil {
		e.begAttackArmy.ClearDirty()
	}
	if e.begDefenseArmy != nil {
		e.begDefenseArmy.ClearDirty()
	}
	if e.endAttackArmy != nil {
		e.endAttackArmy.ClearDirty()
	}
	if e.endDefenseArmy != nil {
		e.endDefenseArmy.ClearDirty()
	}
	if e.begAttackGeneral != nil {
		e.begAttackGeneral.ClearDirty()
	}
	if e.begDefenseGeneral != nil {
		e.begDefenseGeneral.ClearDirty()
	}
	if e.endAttackGeneral != nil {
		e.endAttackGeneral.ClearDirty()
	}
	if e.endDefenseGeneral != nil {
		e.endDefenseGeneral.ClearDirty()
	}
}

func (e *WarReportEntity) DirtyFields() []Field {
	if e == nil {
		return nil
	}
	trace := make(map[Field]bool, len(e._dt.trace)+4)
	for k := range e._dt.trace {
		trace[k] = true
	}
	if e.begAttackArmy != nil && e.begAttackArmy.Dirty() {
		trace[FieldWarReport_begAttackArmy] = true
	}
	if e.begDefenseArmy != nil && e.begDefenseArmy.Dirty() {
		trace[FieldWarReport_begDefenseArmy] = true
	}
	if e.endAttackArmy != nil && e.endAttackArmy.Dirty() {
		trace[FieldWarReport_endAttackArmy] = true
	}
	if e.endDefenseArmy != nil && e.endDefenseArmy.Dirty() {
		trace[FieldWarReport_endDefenseArmy] = true
	}
	if e.begAttackGeneral != nil && e.begAttackGeneral.Dirty() {
		trace[FieldWarReport_begAttackGeneral] = true
	}
	if e.begDefenseGeneral != nil && e.begDefenseGeneral.Dirty() {
		trace[FieldWarReport_begDefenseGeneral] = true
	}
	if e.endAttackGeneral != nil && e.endAttackGeneral.Dirty() {
		trace[FieldWarReport_endAttackGeneral] = true
	}
	if e.endDefenseGeneral != nil && e.endDefenseGeneral.Dirty() {
		trace[FieldWarReport_endDefenseGeneral] = true
	}
	if len(trace) == 0 {
		return nil
	}
	out := make([]Field, 0, len(trace))
	for k := range trace {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func (e *WarReportEntity) DirtyChanges() map[Field]WarReportEntityCollectionChange {
	if e == nil || len(e._dt.changes) == 0 {
		return nil
	}
	out := make(map[Field]WarReportEntityCollectionChange, len(e._dt.changes))
	for f, ch := range e._dt.changes {
		if ch == nil {
			continue
		}
		item := WarReportEntityCollectionChange{
			FullReplace: ch.fullReplace,
		}
		if len(ch.mapSet) > 0 {
			item.MapSet = make(map[string]any, len(ch.mapSet))
			for k, v := range ch.mapSet {
				item.MapSet[k] = v
			}
		}
		if len(ch.mapDelete) > 0 {
			keys := make([]string, 0, len(ch.mapDelete))
			for k := range ch.mapDelete {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			item.MapDeleteKeys = keys
		}
		if len(ch.sliceSet) > 0 {
			item.SliceSet = make(map[int]any, len(ch.sliceSet))
			for idx, v := range ch.sliceSet {
				item.SliceSet[idx] = v
			}
		}
		if len(ch.sliceAppend) > 0 {
			item.SliceAppend = append([]any(nil), ch.sliceAppend...)
		}
		if len(ch.sliceRemoveAt) > 0 {
			item.SliceRemoveAt = append([]int(nil), ch.sliceRemoveAt...)
		}
		if len(ch.sliceSwapRemoveAt) > 0 {
			item.SliceSwapRemoveAt = append([]int(nil), ch.sliceSwapRemoveAt...)
		}
		out[f] = item
	}
	return out
}

func cloneWarReportEntityCollectionChange(in WarReportEntityCollectionChange) WarReportEntityCollectionChange {
	out := in
	if in.MapSet != nil {
		out.MapSet = make(map[string]any, len(in.MapSet))
		for k, v := range in.MapSet {
			out.MapSet[k] = v
		}
	}
	if in.MapDeleteKeys != nil {
		out.MapDeleteKeys = append([]string(nil), in.MapDeleteKeys...)
	}
	if in.SliceSet != nil {
		out.SliceSet = make(map[int]any, len(in.SliceSet))
		for idx, v := range in.SliceSet {
			out.SliceSet[idx] = v
		}
	}
	if in.SliceAppend != nil {
		out.SliceAppend = append([]any(nil), in.SliceAppend...)
	}
	if in.SliceRemoveAt != nil {
		out.SliceRemoveAt = append([]int(nil), in.SliceRemoveAt...)
	}
	if in.SliceSwapRemoveAt != nil {
		out.SliceSwapRemoveAt = append([]int(nil), in.SliceSwapRemoveAt...)
	}
	return out
}

func (e *WarReportEntity) Save() WarReportState {
	var s WarReportState
	if e == nil {
		return s
	}
	s.Id = e.id
	s.Attacker = e.attacker
	s.Defender = e.defender
	if e.begAttackArmy != nil {
		s.BegAttackArmy = e.begAttackArmy.Save()
	} else {
		var z ArmyState
		s.BegAttackArmy = z
	}
	if e.begDefenseArmy != nil {
		s.BegDefenseArmy = e.begDefenseArmy.Save()
	} else {
		var z ArmyState
		s.BegDefenseArmy = z
	}
	if e.endAttackArmy != nil {
		s.EndAttackArmy = e.endAttackArmy.Save()
	} else {
		var z ArmyState
		s.EndAttackArmy = z
	}
	if e.endDefenseArmy != nil {
		s.EndDefenseArmy = e.endDefenseArmy.Save()
	} else {
		var z ArmyState
		s.EndDefenseArmy = z
	}
	if e.begAttackGeneral != nil {
		s.BegAttackGeneral = e.begAttackGeneral.Save()
	} else {
		var z GeneralState
		s.BegAttackGeneral = z
	}
	if e.begDefenseGeneral != nil {
		s.BegDefenseGeneral = e.begDefenseGeneral.Save()
	} else {
		var z GeneralState
		s.BegDefenseGeneral = z
	}
	if e.endAttackGeneral != nil {
		s.EndAttackGeneral = e.endAttackGeneral.Save()
	} else {
		var z GeneralState
		s.EndAttackGeneral = z
	}
	if e.endDefenseGeneral != nil {
		s.EndDefenseGeneral = e.endDefenseGeneral.Save()
	} else {
		var z GeneralState
		s.EndDefenseGeneral = z
	}
	s.Result = e.result
	s.Rounds = e.rounds
	s.AttackIsRead = e.attackIsRead
	s.DefenseIsRead = e.defenseIsRead
	s.DestroyDurable = e.destroyDurable
	s.Occupy = e.occupy
	s.X = e.x
	s.Y = e.y
	s.CTime = e.cTime
	return s
}

func NewWarReportEntitySnap(version uint64, e *WarReportEntity) *WarReportEntitySnap {
	if e == nil {
		return nil
	}
	dirtyFields := e.DirtyFields()
	changes := e.DirtyChanges()
	return &WarReportEntitySnap{
		Version:     version,
		State:       e.Save(),
		DirtyFields: dirtyFields,
		Changes:     changes,
	}
}

func (s *WarReportEntitySnap) Clone() *WarReportEntitySnap {
	if s == nil {
		return nil
	}
	out := &WarReportEntitySnap{Version: s.Version}
	out.State = s.State
	out.DirtyFields = append([]Field(nil), s.DirtyFields...)
	if len(s.Changes) > 0 {
		out.Changes = make(map[Field]WarReportEntityCollectionChange, len(s.Changes))
		for f, ch := range s.Changes {
			out.Changes[f] = cloneWarReportEntityCollectionChange(ch)
		}
	}
	return out
}

func (e *WarReportEntity) Id() int {
	if e == nil {
		var z int
		return z
	}
	return e.id
}

func (e *WarReportEntity) SetId(v int) bool {
	if e == nil {
		return false
	}
	if e.id == v {
		return false
	}
	e.id = v
	e._dt.mark(FieldWarReport_id)
	return true
}

func (e *WarReportEntity) Attacker() int {
	if e == nil {
		var z int
		return z
	}
	return e.attacker
}

func (e *WarReportEntity) SetAttacker(v int) bool {
	if e == nil {
		return false
	}
	if e.attacker == v {
		return false
	}
	e.attacker = v
	e._dt.mark(FieldWarReport_attacker)
	return true
}

func (e *WarReportEntity) Defender() int {
	if e == nil {
		var z int
		return z
	}
	return e.defender
}

func (e *WarReportEntity) SetDefender(v int) bool {
	if e == nil {
		return false
	}
	if e.defender == v {
		return false
	}
	e.defender = v
	e._dt.mark(FieldWarReport_defender)
	return true
}

func (e *WarReportEntity) BegAttackArmy() *ArmyEntity {
	if e == nil {
		return nil
	}
	return e.begAttackArmy
}

func (e *WarReportEntity) SetBegAttackArmy(v ArmyState) bool {
	if e == nil {
		return false
	}
	next := HydrateArmyEntity(v)
	if e.begAttackArmy == next {
		return false
	}
	e.begAttackArmy = next
	e._dt.mark(FieldWarReport_begAttackArmy)
	return true
}

func (e *WarReportEntity) SetBegAttackArmyEntity(v *ArmyEntity) bool {
	if e == nil {
		return false
	}
	if e.begAttackArmy == v {
		return false
	}
	e.begAttackArmy = v
	e._dt.mark(FieldWarReport_begAttackArmy)
	return true
}

func (e *WarReportEntity) UpdateBegAttackArmy(fn func(value *ArmyEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.begAttackArmy == nil {
		e.begAttackArmy = &ArmyEntity{}
	}
	fn(e.begAttackArmy)
	e._dt.mark(FieldWarReport_begAttackArmy)
	return true
}

func (e *WarReportEntity) BegDefenseArmy() *ArmyEntity {
	if e == nil {
		return nil
	}
	return e.begDefenseArmy
}

func (e *WarReportEntity) SetBegDefenseArmy(v ArmyState) bool {
	if e == nil {
		return false
	}
	next := HydrateArmyEntity(v)
	if e.begDefenseArmy == next {
		return false
	}
	e.begDefenseArmy = next
	e._dt.mark(FieldWarReport_begDefenseArmy)
	return true
}

func (e *WarReportEntity) SetBegDefenseArmyEntity(v *ArmyEntity) bool {
	if e == nil {
		return false
	}
	if e.begDefenseArmy == v {
		return false
	}
	e.begDefenseArmy = v
	e._dt.mark(FieldWarReport_begDefenseArmy)
	return true
}

func (e *WarReportEntity) UpdateBegDefenseArmy(fn func(value *ArmyEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.begDefenseArmy == nil {
		e.begDefenseArmy = &ArmyEntity{}
	}
	fn(e.begDefenseArmy)
	e._dt.mark(FieldWarReport_begDefenseArmy)
	return true
}

func (e *WarReportEntity) EndAttackArmy() *ArmyEntity {
	if e == nil {
		return nil
	}
	return e.endAttackArmy
}

func (e *WarReportEntity) SetEndAttackArmy(v ArmyState) bool {
	if e == nil {
		return false
	}
	next := HydrateArmyEntity(v)
	if e.endAttackArmy == next {
		return false
	}
	e.endAttackArmy = next
	e._dt.mark(FieldWarReport_endAttackArmy)
	return true
}

func (e *WarReportEntity) SetEndAttackArmyEntity(v *ArmyEntity) bool {
	if e == nil {
		return false
	}
	if e.endAttackArmy == v {
		return false
	}
	e.endAttackArmy = v
	e._dt.mark(FieldWarReport_endAttackArmy)
	return true
}

func (e *WarReportEntity) UpdateEndAttackArmy(fn func(value *ArmyEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.endAttackArmy == nil {
		e.endAttackArmy = &ArmyEntity{}
	}
	fn(e.endAttackArmy)
	e._dt.mark(FieldWarReport_endAttackArmy)
	return true
}

func (e *WarReportEntity) EndDefenseArmy() *ArmyEntity {
	if e == nil {
		return nil
	}
	return e.endDefenseArmy
}

func (e *WarReportEntity) SetEndDefenseArmy(v ArmyState) bool {
	if e == nil {
		return false
	}
	next := HydrateArmyEntity(v)
	if e.endDefenseArmy == next {
		return false
	}
	e.endDefenseArmy = next
	e._dt.mark(FieldWarReport_endDefenseArmy)
	return true
}

func (e *WarReportEntity) SetEndDefenseArmyEntity(v *ArmyEntity) bool {
	if e == nil {
		return false
	}
	if e.endDefenseArmy == v {
		return false
	}
	e.endDefenseArmy = v
	e._dt.mark(FieldWarReport_endDefenseArmy)
	return true
}

func (e *WarReportEntity) UpdateEndDefenseArmy(fn func(value *ArmyEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.endDefenseArmy == nil {
		e.endDefenseArmy = &ArmyEntity{}
	}
	fn(e.endDefenseArmy)
	e._dt.mark(FieldWarReport_endDefenseArmy)
	return true
}

func (e *WarReportEntity) BegAttackGeneral() *GeneralEntity {
	if e == nil {
		return nil
	}
	return e.begAttackGeneral
}

func (e *WarReportEntity) SetBegAttackGeneral(v GeneralState) bool {
	if e == nil {
		return false
	}
	next := HydrateGeneralEntity(v)
	if e.begAttackGeneral == next {
		return false
	}
	e.begAttackGeneral = next
	e._dt.mark(FieldWarReport_begAttackGeneral)
	return true
}

func (e *WarReportEntity) SetBegAttackGeneralEntity(v *GeneralEntity) bool {
	if e == nil {
		return false
	}
	if e.begAttackGeneral == v {
		return false
	}
	e.begAttackGeneral = v
	e._dt.mark(FieldWarReport_begAttackGeneral)
	return true
}

func (e *WarReportEntity) UpdateBegAttackGeneral(fn func(value *GeneralEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.begAttackGeneral == nil {
		e.begAttackGeneral = &GeneralEntity{}
	}
	fn(e.begAttackGeneral)
	e._dt.mark(FieldWarReport_begAttackGeneral)
	return true
}

func (e *WarReportEntity) BegDefenseGeneral() *GeneralEntity {
	if e == nil {
		return nil
	}
	return e.begDefenseGeneral
}

func (e *WarReportEntity) SetBegDefenseGeneral(v GeneralState) bool {
	if e == nil {
		return false
	}
	next := HydrateGeneralEntity(v)
	if e.begDefenseGeneral == next {
		return false
	}
	e.begDefenseGeneral = next
	e._dt.mark(FieldWarReport_begDefenseGeneral)
	return true
}

func (e *WarReportEntity) SetBegDefenseGeneralEntity(v *GeneralEntity) bool {
	if e == nil {
		return false
	}
	if e.begDefenseGeneral == v {
		return false
	}
	e.begDefenseGeneral = v
	e._dt.mark(FieldWarReport_begDefenseGeneral)
	return true
}

func (e *WarReportEntity) UpdateBegDefenseGeneral(fn func(value *GeneralEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.begDefenseGeneral == nil {
		e.begDefenseGeneral = &GeneralEntity{}
	}
	fn(e.begDefenseGeneral)
	e._dt.mark(FieldWarReport_begDefenseGeneral)
	return true
}

func (e *WarReportEntity) EndAttackGeneral() *GeneralEntity {
	if e == nil {
		return nil
	}
	return e.endAttackGeneral
}

func (e *WarReportEntity) SetEndAttackGeneral(v GeneralState) bool {
	if e == nil {
		return false
	}
	next := HydrateGeneralEntity(v)
	if e.endAttackGeneral == next {
		return false
	}
	e.endAttackGeneral = next
	e._dt.mark(FieldWarReport_endAttackGeneral)
	return true
}

func (e *WarReportEntity) SetEndAttackGeneralEntity(v *GeneralEntity) bool {
	if e == nil {
		return false
	}
	if e.endAttackGeneral == v {
		return false
	}
	e.endAttackGeneral = v
	e._dt.mark(FieldWarReport_endAttackGeneral)
	return true
}

func (e *WarReportEntity) UpdateEndAttackGeneral(fn func(value *GeneralEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.endAttackGeneral == nil {
		e.endAttackGeneral = &GeneralEntity{}
	}
	fn(e.endAttackGeneral)
	e._dt.mark(FieldWarReport_endAttackGeneral)
	return true
}

func (e *WarReportEntity) EndDefenseGeneral() *GeneralEntity {
	if e == nil {
		return nil
	}
	return e.endDefenseGeneral
}

func (e *WarReportEntity) SetEndDefenseGeneral(v GeneralState) bool {
	if e == nil {
		return false
	}
	next := HydrateGeneralEntity(v)
	if e.endDefenseGeneral == next {
		return false
	}
	e.endDefenseGeneral = next
	e._dt.mark(FieldWarReport_endDefenseGeneral)
	return true
}

func (e *WarReportEntity) SetEndDefenseGeneralEntity(v *GeneralEntity) bool {
	if e == nil {
		return false
	}
	if e.endDefenseGeneral == v {
		return false
	}
	e.endDefenseGeneral = v
	e._dt.mark(FieldWarReport_endDefenseGeneral)
	return true
}

func (e *WarReportEntity) UpdateEndDefenseGeneral(fn func(value *GeneralEntity)) bool {
	if e == nil || fn == nil {
		return false
	}
	if e.endDefenseGeneral == nil {
		e.endDefenseGeneral = &GeneralEntity{}
	}
	fn(e.endDefenseGeneral)
	e._dt.mark(FieldWarReport_endDefenseGeneral)
	return true
}

func (e *WarReportEntity) Result() int {
	if e == nil {
		var z int
		return z
	}
	return e.result
}

func (e *WarReportEntity) SetResult(v int) bool {
	if e == nil {
		return false
	}
	if e.result == v {
		return false
	}
	e.result = v
	e._dt.mark(FieldWarReport_result)
	return true
}

func (e *WarReportEntity) Rounds() string {
	if e == nil {
		var z string
		return z
	}
	return e.rounds
}

func (e *WarReportEntity) SetRounds(v string) bool {
	if e == nil {
		return false
	}
	if e.rounds == v {
		return false
	}
	e.rounds = v
	e._dt.mark(FieldWarReport_rounds)
	return true
}

func (e *WarReportEntity) AttackIsRead() bool {
	if e == nil {
		var z bool
		return z
	}
	return e.attackIsRead
}

func (e *WarReportEntity) SetAttackIsRead(v bool) bool {
	if e == nil {
		return false
	}
	if e.attackIsRead == v {
		return false
	}
	e.attackIsRead = v
	e._dt.mark(FieldWarReport_attackIsRead)
	return true
}

func (e *WarReportEntity) DefenseIsRead() bool {
	if e == nil {
		var z bool
		return z
	}
	return e.defenseIsRead
}

func (e *WarReportEntity) SetDefenseIsRead(v bool) bool {
	if e == nil {
		return false
	}
	if e.defenseIsRead == v {
		return false
	}
	e.defenseIsRead = v
	e._dt.mark(FieldWarReport_defenseIsRead)
	return true
}

func (e *WarReportEntity) DestroyDurable() int {
	if e == nil {
		var z int
		return z
	}
	return e.destroyDurable
}

func (e *WarReportEntity) SetDestroyDurable(v int) bool {
	if e == nil {
		return false
	}
	if e.destroyDurable == v {
		return false
	}
	e.destroyDurable = v
	e._dt.mark(FieldWarReport_destroyDurable)
	return true
}

func (e *WarReportEntity) Occupy() int {
	if e == nil {
		var z int
		return z
	}
	return e.occupy
}

func (e *WarReportEntity) SetOccupy(v int) bool {
	if e == nil {
		return false
	}
	if e.occupy == v {
		return false
	}
	e.occupy = v
	e._dt.mark(FieldWarReport_occupy)
	return true
}

func (e *WarReportEntity) X() int {
	if e == nil {
		var z int
		return z
	}
	return e.x
}

func (e *WarReportEntity) SetX(v int) bool {
	if e == nil {
		return false
	}
	if e.x == v {
		return false
	}
	e.x = v
	e._dt.mark(FieldWarReport_x)
	return true
}

func (e *WarReportEntity) Y() int {
	if e == nil {
		var z int
		return z
	}
	return e.y
}

func (e *WarReportEntity) SetY(v int) bool {
	if e == nil {
		return false
	}
	if e.y == v {
		return false
	}
	e.y = v
	e._dt.mark(FieldWarReport_y)
	return true
}

func (e *WarReportEntity) CTime() int {
	if e == nil {
		var z int
		return z
	}
	return e.cTime
}

func (e *WarReportEntity) SetCTime(v int) bool {
	if e == nil {
		return false
	}
	if e.cTime == v {
		return false
	}
	e.cTime = v
	e._dt.mark(FieldWarReport_cTime)
	return true
}
